package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Accesos generated by hbm2java
 */
@Entity
@Table(name = "ACCESOS", schema = "WEB")
public class Accesos implements java.io.Serializable {

	private int acccesoId;
	private Integer accesoUsuario;
	private Integer accesoModulo;
	private Integer accesoEstado;
	private Integer accesoAutor;

	public Accesos() {
	}

	public Accesos(int acccesoId) {
		this.acccesoId = acccesoId;
	}

	public Accesos(int acccesoId, Integer accesoUsuario, Integer accesoModulo,
			Integer accesoEstado, Integer accesoAutor) {
		this.acccesoId = acccesoId;
		this.accesoUsuario = accesoUsuario;
		this.accesoModulo = accesoModulo;
		this.accesoEstado = accesoEstado;
		this.accesoAutor = accesoAutor;
	}

	@Id
	@Column(name = "accceso_id", nullable = false)
	public int getAcccesoId() {
		return this.acccesoId;
	}

	public void setAcccesoId(int acccesoId) {
		this.acccesoId = acccesoId;
	}

	@Column(name = "acceso_usuario")
	public Integer getAccesoUsuario() {
		return this.accesoUsuario;
	}

	public void setAccesoUsuario(Integer accesoUsuario) {
		this.accesoUsuario = accesoUsuario;
	}

	@Column(name = "acceso_modulo")
	public Integer getAccesoModulo() {
		return this.accesoModulo;
	}

	public void setAccesoModulo(Integer accesoModulo) {
		this.accesoModulo = accesoModulo;
	}

	@Column(name = "acceso_estado")
	public Integer getAccesoEstado() {
		return this.accesoEstado;
	}

	public void setAccesoEstado(Integer accesoEstado) {
		this.accesoEstado = accesoEstado;
	}

	@Column(name = "acceso_autor")
	public Integer getAccesoAutor() {
		return this.accesoAutor;
	}

	public void setAccesoAutor(Integer accesoAutor) {
		this.accesoAutor = accesoAutor;
	}

}
