package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CategoriasEncuesta generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIAS_ENCUESTA", schema = "WEB")
public class CategoriasEncuesta implements java.io.Serializable {

	private CategoriasEncuestaId id;

	public CategoriasEncuesta() {
	}

	public CategoriasEncuesta(CategoriasEncuestaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codCateg", column = @Column(name = "COD_CATEG")),
			@AttributeOverride(name = "desCateg", column = @Column(name = "DES_CATEG", length = 50)),
			@AttributeOverride(name = "flaRegistro", column = @Column(name = "fla_registro")) })
	public CategoriasEncuestaId getId() {
		return this.id;
	}

	public void setId(CategoriasEncuestaId id) {
		this.id = id;
	}

}
