package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoriasEncuestaId generated by hbm2java
 */
@Embeddable
public class CategoriasEncuestaId implements java.io.Serializable {

	private Integer codCateg;
	private String desCateg;
	private Integer flaRegistro;

	public CategoriasEncuestaId() {
	}

	public CategoriasEncuestaId(Integer codCateg, String desCateg,
			Integer flaRegistro) {
		this.codCateg = codCateg;
		this.desCateg = desCateg;
		this.flaRegistro = flaRegistro;
	}

	@Column(name = "COD_CATEG")
	public Integer getCodCateg() {
		return this.codCateg;
	}

	public void setCodCateg(Integer codCateg) {
		this.codCateg = codCateg;
	}

	@Column(name = "DES_CATEG", length = 50)
	public String getDesCateg() {
		return this.desCateg;
	}

	public void setDesCateg(String desCateg) {
		this.desCateg = desCateg;
	}

	@Column(name = "fla_registro")
	public Integer getFlaRegistro() {
		return this.flaRegistro;
	}

	public void setFlaRegistro(Integer flaRegistro) {
		this.flaRegistro = flaRegistro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoriasEncuestaId))
			return false;
		CategoriasEncuestaId castOther = (CategoriasEncuestaId) other;

		return ((this.getCodCateg() == castOther.getCodCateg()) || (this
				.getCodCateg() != null && castOther.getCodCateg() != null && this
				.getCodCateg().equals(castOther.getCodCateg())))
				&& ((this.getDesCateg() == castOther.getDesCateg()) || (this
						.getDesCateg() != null
						&& castOther.getDesCateg() != null && this
						.getDesCateg().equals(castOther.getDesCateg())))
				&& ((this.getFlaRegistro() == castOther.getFlaRegistro()) || (this
						.getFlaRegistro() != null
						&& castOther.getFlaRegistro() != null && this
						.getFlaRegistro().equals(castOther.getFlaRegistro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodCateg() == null ? 0 : this.getCodCateg().hashCode());
		result = 37 * result
				+ (getDesCateg() == null ? 0 : this.getDesCateg().hashCode());
		result = 37
				* result
				+ (getFlaRegistro() == null ? 0 : this.getFlaRegistro()
						.hashCode());
		return result;
	}

}
