package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoNoticia generated by hbm2java
 */
@Entity
@Table(name = "estado_noticia", schema = "WEB")
public class EstadoNoticia implements java.io.Serializable {

	private int codEst;
	private String descrip;
	private Integer flaActivo;

	public EstadoNoticia() {
	}

	public EstadoNoticia(int codEst) {
		this.codEst = codEst;
	}

	public EstadoNoticia(int codEst, String descrip, Integer flaActivo) {
		this.codEst = codEst;
		this.descrip = descrip;
		this.flaActivo = flaActivo;
	}

	@Id
	@Column(name = "cod_est", nullable = false)
	public int getCodEst() {
		return this.codEst;
	}

	public void setCodEst(int codEst) {
		this.codEst = codEst;
	}

	@Column(name = "descrip", length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	@Column(name = "fla_activo")
	public Integer getFlaActivo() {
		return this.flaActivo;
	}

	public void setFlaActivo(Integer flaActivo) {
		this.flaActivo = flaActivo;
	}

}
