package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MasterEncuestaDatosId generated by hbm2java
 */
@Embeddable
public class MasterEncuestaDatosId implements java.io.Serializable {

	private Integer id;
	private String doc;
	private String nom;
	private Integer categ;
	private Date fecha;
	private Integer distJud;
	private String orgJuris;
	private Integer espec;
	private String obs;
	private Integer flaRegistro;

	public MasterEncuestaDatosId() {
	}

	public MasterEncuestaDatosId(Integer id, String doc, String nom,
			Integer categ, Date fecha, Integer distJud, String orgJuris,
			Integer espec, String obs, Integer flaRegistro) {
		this.id = id;
		this.doc = doc;
		this.nom = nom;
		this.categ = categ;
		this.fecha = fecha;
		this.distJud = distJud;
		this.orgJuris = orgJuris;
		this.espec = espec;
		this.obs = obs;
		this.flaRegistro = flaRegistro;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "doc", length = 20)
	public String getDoc() {
		return this.doc;
	}

	public void setDoc(String doc) {
		this.doc = doc;
	}

	@Column(name = "nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "categ")
	public Integer getCateg() {
		return this.categ;
	}

	public void setCateg(Integer categ) {
		this.categ = categ;
	}

	@Column(name = "fecha", length = 26)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "dist_jud")
	public Integer getDistJud() {
		return this.distJud;
	}

	public void setDistJud(Integer distJud) {
		this.distJud = distJud;
	}

	@Column(name = "org_juris", length = 50)
	public String getOrgJuris() {
		return this.orgJuris;
	}

	public void setOrgJuris(String orgJuris) {
		this.orgJuris = orgJuris;
	}

	@Column(name = "espec")
	public Integer getEspec() {
		return this.espec;
	}

	public void setEspec(Integer espec) {
		this.espec = espec;
	}

	@Column(name = "obs")
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "fla_registro")
	public Integer getFlaRegistro() {
		return this.flaRegistro;
	}

	public void setFlaRegistro(Integer flaRegistro) {
		this.flaRegistro = flaRegistro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MasterEncuestaDatosId))
			return false;
		MasterEncuestaDatosId castOther = (MasterEncuestaDatosId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDoc() == castOther.getDoc()) || (this.getDoc() != null
						&& castOther.getDoc() != null && this.getDoc().equals(
						castOther.getDoc())))
				&& ((this.getNom() == castOther.getNom()) || (this.getNom() != null
						&& castOther.getNom() != null && this.getNom().equals(
						castOther.getNom())))
				&& ((this.getCateg() == castOther.getCateg()) || (this
						.getCateg() != null && castOther.getCateg() != null && this
						.getCateg().equals(castOther.getCateg())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getDistJud() == castOther.getDistJud()) || (this
						.getDistJud() != null && castOther.getDistJud() != null && this
						.getDistJud().equals(castOther.getDistJud())))
				&& ((this.getOrgJuris() == castOther.getOrgJuris()) || (this
						.getOrgJuris() != null
						&& castOther.getOrgJuris() != null && this
						.getOrgJuris().equals(castOther.getOrgJuris())))
				&& ((this.getEspec() == castOther.getEspec()) || (this
						.getEspec() != null && castOther.getEspec() != null && this
						.getEspec().equals(castOther.getEspec())))
				&& ((this.getObs() == castOther.getObs()) || (this.getObs() != null
						&& castOther.getObs() != null && this.getObs().equals(
						castOther.getObs())))
				&& ((this.getFlaRegistro() == castOther.getFlaRegistro()) || (this
						.getFlaRegistro() != null
						&& castOther.getFlaRegistro() != null && this
						.getFlaRegistro().equals(castOther.getFlaRegistro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getDoc() == null ? 0 : this.getDoc().hashCode());
		result = 37 * result
				+ (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result
				+ (getCateg() == null ? 0 : this.getCateg().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getDistJud() == null ? 0 : this.getDistJud().hashCode());
		result = 37 * result
				+ (getOrgJuris() == null ? 0 : this.getOrgJuris().hashCode());
		result = 37 * result
				+ (getEspec() == null ? 0 : this.getEspec().hashCode());
		result = 37 * result
				+ (getObs() == null ? 0 : this.getObs().hashCode());
		result = 37
				* result
				+ (getFlaRegistro() == null ? 0 : this.getFlaRegistro()
						.hashCode());
		return result;
	}

}
