package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MasterEncuestaDatosDetalle generated by hbm2java
 */
@Entity
@Table(name = "master_encuesta_datos_detalle", schema = "WEB")
public class MasterEncuestaDatosDetalle implements java.io.Serializable {

	private MasterEncuestaDatosDetalleId id;

	public MasterEncuestaDatosDetalle() {
	}

	public MasterEncuestaDatosDetalle(MasterEncuestaDatosDetalleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "codPreg", column = @Column(name = "cod_preg")),
			@AttributeOverride(name = "codOpc", column = @Column(name = "cod_opc")),
			@AttributeOverride(name = "flaRegistro", column = @Column(name = "fla_registro")) })
	public MasterEncuestaDatosDetalleId getId() {
		return this.id;
	}

	public void setId(MasterEncuestaDatosDetalleId id) {
		this.id = id;
	}

}
