package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MasterEncuestaDatosDetalleId generated by hbm2java
 */
@Embeddable
public class MasterEncuestaDatosDetalleId implements java.io.Serializable {

	private Integer id;
	private Integer codPreg;
	private Integer codOpc;
	private Integer flaRegistro;

	public MasterEncuestaDatosDetalleId() {
	}

	public MasterEncuestaDatosDetalleId(Integer id, Integer codPreg,
			Integer codOpc, Integer flaRegistro) {
		this.id = id;
		this.codPreg = codPreg;
		this.codOpc = codOpc;
		this.flaRegistro = flaRegistro;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cod_preg")
	public Integer getCodPreg() {
		return this.codPreg;
	}

	public void setCodPreg(Integer codPreg) {
		this.codPreg = codPreg;
	}

	@Column(name = "cod_opc")
	public Integer getCodOpc() {
		return this.codOpc;
	}

	public void setCodOpc(Integer codOpc) {
		this.codOpc = codOpc;
	}

	@Column(name = "fla_registro")
	public Integer getFlaRegistro() {
		return this.flaRegistro;
	}

	public void setFlaRegistro(Integer flaRegistro) {
		this.flaRegistro = flaRegistro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MasterEncuestaDatosDetalleId))
			return false;
		MasterEncuestaDatosDetalleId castOther = (MasterEncuestaDatosDetalleId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCodPreg() == castOther.getCodPreg()) || (this
						.getCodPreg() != null && castOther.getCodPreg() != null && this
						.getCodPreg().equals(castOther.getCodPreg())))
				&& ((this.getCodOpc() == castOther.getCodOpc()) || (this
						.getCodOpc() != null && castOther.getCodOpc() != null && this
						.getCodOpc().equals(castOther.getCodOpc())))
				&& ((this.getFlaRegistro() == castOther.getFlaRegistro()) || (this
						.getFlaRegistro() != null
						&& castOther.getFlaRegistro() != null && this
						.getFlaRegistro().equals(castOther.getFlaRegistro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCodPreg() == null ? 0 : this.getCodPreg().hashCode());
		result = 37 * result
				+ (getCodOpc() == null ? 0 : this.getCodOpc().hashCode());
		result = 37
				* result
				+ (getFlaRegistro() == null ? 0 : this.getFlaRegistro()
						.hashCode());
		return result;
	}

}
