package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TabEspecialidad generated by hbm2java
 */
@Entity
@Table(name = "TAB_ESPECIALIDAD", schema = "WEB")
public class TabEspecialidad implements java.io.Serializable {

	private int idEspecialidad;
	private String descripcion;
	private String abreviatura;
	private Set<TQuejasMaster> TQuejasMasters = new HashSet<TQuejasMaster>(0);

	public TabEspecialidad() {
	}

	public TabEspecialidad(int idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	public TabEspecialidad(int idEspecialidad, String descripcion,
			String abreviatura, Set<TQuejasMaster> TQuejasMasters) {
		this.idEspecialidad = idEspecialidad;
		this.descripcion = descripcion;
		this.abreviatura = abreviatura;
		this.TQuejasMasters = TQuejasMasters;
	}

	@Id
	@Column(name = "id_especialidad", nullable = false)
	public int getIdEspecialidad() {
		return this.idEspecialidad;
	}

	public void setIdEspecialidad(int idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "abreviatura", length = 4)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tabEspecialidad")
	public Set<TQuejasMaster> getTQuejasMasters() {
		return this.TQuejasMasters;
	}

	public void setTQuejasMasters(Set<TQuejasMaster> TQuejasMasters) {
		this.TQuejasMasters = TQuejasMasters;
	}

}
