package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TabProcesoJudicial generated by hbm2java
 */
@Entity
@Table(name = "TAB_PROCESO_JUDICIAL", schema = "WEB")
public class TabProcesoJudicial implements java.io.Serializable {

	private int idProcesoJudicial;
	private String descripcion;
	private String abreviatura;
	private Set<TQuejasMaster> TQuejasMasters = new HashSet<TQuejasMaster>(0);

	public TabProcesoJudicial() {
	}

	public TabProcesoJudicial(int idProcesoJudicial) {
		this.idProcesoJudicial = idProcesoJudicial;
	}

	public TabProcesoJudicial(int idProcesoJudicial, String descripcion,
			String abreviatura, Set<TQuejasMaster> TQuejasMasters) {
		this.idProcesoJudicial = idProcesoJudicial;
		this.descripcion = descripcion;
		this.abreviatura = abreviatura;
		this.TQuejasMasters = TQuejasMasters;
	}

	@Id
	@Column(name = "id_proceso_judicial", nullable = false)
	public int getIdProcesoJudicial() {
		return this.idProcesoJudicial;
	}

	public void setIdProcesoJudicial(int idProcesoJudicial) {
		this.idProcesoJudicial = idProcesoJudicial;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "abreviatura", length = 5)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tabProcesoJudicial")
	public Set<TQuejasMaster> getTQuejasMasters() {
		return this.TQuejasMasters;
	}

	public void setTQuejasMasters(Set<TQuejasMaster> TQuejasMasters) {
		this.TQuejasMasters = TQuejasMasters;
	}

}
