package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TArea generated by hbm2java
 */
@Entity
@Table(name = "T_AREA", schema = "WEB")
public class TArea implements java.io.Serializable {

	private int idArea;
	private String desArea;
	private String abrArea;
	private Set<TIntegrante> TIntegrantes = new HashSet<TIntegrante>(0);

	public TArea() {
	}

	public TArea(int idArea, String desArea, String abrArea) {
		this.idArea = idArea;
		this.desArea = desArea;
		this.abrArea = abrArea;
	}

	public TArea(int idArea, String desArea, String abrArea,
			Set<TIntegrante> TIntegrantes) {
		this.idArea = idArea;
		this.desArea = desArea;
		this.abrArea = abrArea;
		this.TIntegrantes = TIntegrantes;
	}

	@Id
	@Column(name = "id_area", nullable = false)
	public int getIdArea() {
		return this.idArea;
	}

	public void setIdArea(int idArea) {
		this.idArea = idArea;
	}

	@Column(name = "des_area", nullable = false, length = 200)
	public String getDesArea() {
		return this.desArea;
	}

	public void setDesArea(String desArea) {
		this.desArea = desArea;
	}

	@Column(name = "abr_area", nullable = false, length = 5)
	public String getAbrArea() {
		return this.abrArea;
	}

	public void setAbrArea(String abrArea) {
		this.abrArea = abrArea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArea")
	public Set<TIntegrante> getTIntegrantes() {
		return this.TIntegrantes;
	}

	public void setTIntegrantes(Set<TIntegrante> TIntegrantes) {
		this.TIntegrantes = TIntegrantes;
	}

}
