package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TCargos generated by hbm2java
 */
@Entity
@Table(name = "T_CARGOS", schema = "WEB")
public class TCargos implements java.io.Serializable {

	private TCargosId id;

	public TCargos() {
	}

	public TCargos(TCargosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codCargo", column = @Column(name = "cod_cargo", nullable = false)),
			@AttributeOverride(name = "desCargo", column = @Column(name = "des_cargo")) })
	public TCargosId getId() {
		return this.id;
	}

	public void setId(TCargosId id) {
		this.id = id;
	}

}
