package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TDiccionarioId generated by hbm2java
 */
@Embeddable
public class TDiccionarioId implements java.io.Serializable {

	private int codPalabra;
	private String detPalabra;
	private String sigPalabra;
	private String autor;
	private String mailAutor;
	private Integer estadoPalabra;

	public TDiccionarioId() {
	}

	public TDiccionarioId(int codPalabra) {
		this.codPalabra = codPalabra;
	}

	public TDiccionarioId(int codPalabra, String detPalabra, String sigPalabra,
			String autor, String mailAutor, Integer estadoPalabra) {
		this.codPalabra = codPalabra;
		this.detPalabra = detPalabra;
		this.sigPalabra = sigPalabra;
		this.autor = autor;
		this.mailAutor = mailAutor;
		this.estadoPalabra = estadoPalabra;
	}

	@Column(name = "cod_palabra", nullable = false)
	public int getCodPalabra() {
		return this.codPalabra;
	}

	public void setCodPalabra(int codPalabra) {
		this.codPalabra = codPalabra;
	}

	@Column(name = "det_palabra")
	public String getDetPalabra() {
		return this.detPalabra;
	}

	public void setDetPalabra(String detPalabra) {
		this.detPalabra = detPalabra;
	}

	@Column(name = "sig_palabra")
	public String getSigPalabra() {
		return this.sigPalabra;
	}

	public void setSigPalabra(String sigPalabra) {
		this.sigPalabra = sigPalabra;
	}

	@Column(name = "autor", length = 50)
	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@Column(name = "mail_autor", length = 50)
	public String getMailAutor() {
		return this.mailAutor;
	}

	public void setMailAutor(String mailAutor) {
		this.mailAutor = mailAutor;
	}

	@Column(name = "estado_palabra")
	public Integer getEstadoPalabra() {
		return this.estadoPalabra;
	}

	public void setEstadoPalabra(Integer estadoPalabra) {
		this.estadoPalabra = estadoPalabra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TDiccionarioId))
			return false;
		TDiccionarioId castOther = (TDiccionarioId) other;

		return (this.getCodPalabra() == castOther.getCodPalabra())
				&& ((this.getDetPalabra() == castOther.getDetPalabra()) || (this
						.getDetPalabra() != null
						&& castOther.getDetPalabra() != null && this
						.getDetPalabra().equals(castOther.getDetPalabra())))
				&& ((this.getSigPalabra() == castOther.getSigPalabra()) || (this
						.getSigPalabra() != null
						&& castOther.getSigPalabra() != null && this
						.getSigPalabra().equals(castOther.getSigPalabra())))
				&& ((this.getAutor() == castOther.getAutor()) || (this
						.getAutor() != null && castOther.getAutor() != null && this
						.getAutor().equals(castOther.getAutor())))
				&& ((this.getMailAutor() == castOther.getMailAutor()) || (this
						.getMailAutor() != null
						&& castOther.getMailAutor() != null && this
						.getMailAutor().equals(castOther.getMailAutor())))
				&& ((this.getEstadoPalabra() == castOther.getEstadoPalabra()) || (this
						.getEstadoPalabra() != null
						&& castOther.getEstadoPalabra() != null && this
						.getEstadoPalabra()
						.equals(castOther.getEstadoPalabra())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodPalabra();
		result = 37
				* result
				+ (getDetPalabra() == null ? 0 : this.getDetPalabra()
						.hashCode());
		result = 37
				* result
				+ (getSigPalabra() == null ? 0 : this.getSigPalabra()
						.hashCode());
		result = 37 * result
				+ (getAutor() == null ? 0 : this.getAutor().hashCode());
		result = 37 * result
				+ (getMailAutor() == null ? 0 : this.getMailAutor().hashCode());
		result = 37
				* result
				+ (getEstadoPalabra() == null ? 0 : this.getEstadoPalabra()
						.hashCode());
		return result;
	}

}
