package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TDiccionario generated by hbm2java
 */
@Entity
@Table(name = "T_DICCIONARIO", schema = "WEB")
public class TDiccionario implements java.io.Serializable {

	private TDiccionarioId id;

	public TDiccionario() {
	}

	public TDiccionario(TDiccionarioId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codPalabra", column = @Column(name = "cod_palabra", nullable = false)),
			@AttributeOverride(name = "detPalabra", column = @Column(name = "det_palabra")),
			@AttributeOverride(name = "sigPalabra", column = @Column(name = "sig_palabra")),
			@AttributeOverride(name = "autor", column = @Column(name = "autor", length = 50)),
			@AttributeOverride(name = "mailAutor", column = @Column(name = "mail_autor", length = 50)),
			@AttributeOverride(name = "estadoPalabra", column = @Column(name = "estado_palabra")) })
	public TDiccionarioId getId() {
		return this.id;
	}

	public void setId(TDiccionarioId id) {
		this.id = id;
	}

}
