package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TDistritos generated by hbm2java
 */
@Entity
@Table(name = "T_DISTRITOS", schema = "WEB")
public class TDistritos implements java.io.Serializable {

	private int codDistri;
	private String desDistri;
	private Integer flaEstado;
	private String desDireccion;
	private Integer codDistritojudicial;
	private Set<TPrensa> TPrensas = new HashSet<TPrensa>(0);

	public TDistritos() {
	}

	public TDistritos(int codDistri) {
		this.codDistri = codDistri;
	}

	public TDistritos(int codDistri, String desDistri, Integer flaEstado,
			String desDireccion, Integer codDistritojudicial,
			Set<TPrensa> TPrensas) {
		this.codDistri = codDistri;
		this.desDistri = desDistri;
		this.flaEstado = flaEstado;
		this.desDireccion = desDireccion;
		this.codDistritojudicial = codDistritojudicial;
		this.TPrensas = TPrensas;
	}

	@Id
	@Column(name = "cod_distri", nullable = false)
	public int getCodDistri() {
		return this.codDistri;
	}

	public void setCodDistri(int codDistri) {
		this.codDistri = codDistri;
	}

	@Column(name = "des_distri", length = 100)
	public String getDesDistri() {
		return this.desDistri;
	}

	public void setDesDistri(String desDistri) {
		this.desDistri = desDistri;
	}

	@Column(name = "fla_estado")
	public Integer getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Integer flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "des_direccion", length = 100)
	public String getDesDireccion() {
		return this.desDireccion;
	}

	public void setDesDireccion(String desDireccion) {
		this.desDireccion = desDireccion;
	}

	@Column(name = "cod_distritojudicial")
	public Integer getCodDistritojudicial() {
		return this.codDistritojudicial;
	}

	public void setCodDistritojudicial(Integer codDistritojudicial) {
		this.codDistritojudicial = codDistritojudicial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDistritos")
	public Set<TPrensa> getTPrensas() {
		return this.TPrensas;
	}

	public void setTPrensas(Set<TPrensa> TPrensas) {
		this.TPrensas = TPrensas;
	}

}
