package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDocumentos generated by hbm2java
 */
@Entity
@Table(name = "T_DOCUMENTOS", schema = "WEB")
public class TDocumentos implements java.io.Serializable {

	private int cod;
	private String concepto;
	private String extencion;
	private String iconoNew;
	private String tipo;
	private String nivel;
	private Date fecha;
	private String nombArchivo;

	public TDocumentos() {
	}

	public TDocumentos(int cod) {
		this.cod = cod;
	}

	public TDocumentos(int cod, String concepto, String extencion,
			String iconoNew, String tipo, String nivel, Date fecha,
			String nombArchivo) {
		this.cod = cod;
		this.concepto = concepto;
		this.extencion = extencion;
		this.iconoNew = iconoNew;
		this.tipo = tipo;
		this.nivel = nivel;
		this.fecha = fecha;
		this.nombArchivo = nombArchivo;
	}

	@Id
	@Column(name = "COD", nullable = false)
	public int getCod() {
		return this.cod;
	}

	public void setCod(int cod) {
		this.cod = cod;
	}

	@Column(name = "CONCEPTO", length = 500)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "EXTENCION", length = 500)
	public String getExtencion() {
		return this.extencion;
	}

	public void setExtencion(String extencion) {
		this.extencion = extencion;
	}

	@Column(name = "ICONO_NEW", length = 500)
	public String getIconoNew() {
		return this.iconoNew;
	}

	public void setIconoNew(String iconoNew) {
		this.iconoNew = iconoNew;
	}

	@Column(name = "TIPO", length = 500)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "NIVEL", length = 500)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "NOMB_ARCHIVO", length = 500)
	public String getNombArchivo() {
		return this.nombArchivo;
	}

	public void setNombArchivo(String nombArchivo) {
		this.nombArchivo = nombArchivo;
	}

}
