package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDocumentosCab generated by hbm2java
 */
@Entity
@Table(name = "T_DOCUMENTOS_CAB", schema = "WEB")
public class TDocumentosCab implements java.io.Serializable {

	private int codCab;
	private String descripcion;
	private Date fecha;
	private String tipArchivo;

	public TDocumentosCab() {
	}

	public TDocumentosCab(int codCab) {
		this.codCab = codCab;
	}

	public TDocumentosCab(int codCab, String descripcion, Date fecha,
			String tipArchivo) {
		this.codCab = codCab;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.tipArchivo = tipArchivo;
	}

	@Id
	@Column(name = "COD_CAB", nullable = false)
	public int getCodCab() {
		return this.codCab;
	}

	public void setCodCab(int codCab) {
		this.codCab = codCab;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "TIP_ARCHIVO", length = 500)
	public String getTipArchivo() {
		return this.tipArchivo;
	}

	public void setTipArchivo(String tipArchivo) {
		this.tipArchivo = tipArchivo;
	}

}
