package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDocumentosDet generated by hbm2java
 */
@Entity
@Table(name = "T_DOCUMENTOS_DET", schema = "WEB")
public class TDocumentosDet implements java.io.Serializable {

	private int codDet;
	private String descripcion;
	private String extencion;
	private String iconoNew;
	private Date fecha;
	private String nombArchivo;
	private Integer codCab;
	private String miniDescripcion;

	public TDocumentosDet() {
	}

	public TDocumentosDet(int codDet) {
		this.codDet = codDet;
	}

	public TDocumentosDet(int codDet, String descripcion, String extencion,
			String iconoNew, Date fecha, String nombArchivo, Integer codCab,
			String miniDescripcion) {
		this.codDet = codDet;
		this.descripcion = descripcion;
		this.extencion = extencion;
		this.iconoNew = iconoNew;
		this.fecha = fecha;
		this.nombArchivo = nombArchivo;
		this.codCab = codCab;
		this.miniDescripcion = miniDescripcion;
	}

	@Id
	@Column(name = "COD_DET", nullable = false)
	public int getCodDet() {
		return this.codDet;
	}

	public void setCodDet(int codDet) {
		this.codDet = codDet;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "EXTENCION", length = 500)
	public String getExtencion() {
		return this.extencion;
	}

	public void setExtencion(String extencion) {
		this.extencion = extencion;
	}

	@Column(name = "ICONO_NEW", length = 500)
	public String getIconoNew() {
		return this.iconoNew;
	}

	public void setIconoNew(String iconoNew) {
		this.iconoNew = iconoNew;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "NOMB_ARCHIVO", length = 500)
	public String getNombArchivo() {
		return this.nombArchivo;
	}

	public void setNombArchivo(String nombArchivo) {
		this.nombArchivo = nombArchivo;
	}

	@Column(name = "COD_CAB")
	public Integer getCodCab() {
		return this.codCab;
	}

	public void setCodCab(Integer codCab) {
		this.codCab = codCab;
	}

	@Column(name = "MINI_DESCRIPCION", length = 500)
	public String getMiniDescripcion() {
		return this.miniDescripcion;
	}

	public void setMiniDescripcion(String miniDescripcion) {
		this.miniDescripcion = miniDescripcion;
	}

}
