package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEncuesta generated by hbm2java
 */
@Entity
@Table(name = "T_ENCUESTA", schema = "WEB")
public class TEncuesta implements java.io.Serializable {

	private int idEncuesta;
	private String pregEncuesta;
	private String tipoEncuesta;
	private Date fecInicio;
	private Date fecTermino;
	private Integer estado;
	private Set<TLogVoto> TLogVotos = new HashSet<TLogVoto>(0);
	private Set<TEncuestaResp> TEncuestaResps = new HashSet<TEncuestaResp>(0);

	public TEncuesta() {
	}

	public TEncuesta(int idEncuesta) {
		this.idEncuesta = idEncuesta;
	}

	public TEncuesta(int idEncuesta, String pregEncuesta, String tipoEncuesta,
			Date fecInicio, Date fecTermino, Integer estado,
			Set<TLogVoto> TLogVotos, Set<TEncuestaResp> TEncuestaResps) {
		this.idEncuesta = idEncuesta;
		this.pregEncuesta = pregEncuesta;
		this.tipoEncuesta = tipoEncuesta;
		this.fecInicio = fecInicio;
		this.fecTermino = fecTermino;
		this.estado = estado;
		this.TLogVotos = TLogVotos;
		this.TEncuestaResps = TEncuestaResps;
	}

	@Id
	@Column(name = "id_encuesta", nullable = false)
	public int getIdEncuesta() {
		return this.idEncuesta;
	}

	public void setIdEncuesta(int idEncuesta) {
		this.idEncuesta = idEncuesta;
	}

	@Column(name = "preg_encuesta", length = 250)
	public String getPregEncuesta() {
		return this.pregEncuesta;
	}

	public void setPregEncuesta(String pregEncuesta) {
		this.pregEncuesta = pregEncuesta;
	}

	@Column(name = "tipo_encuesta", length = 50)
	public String getTipoEncuesta() {
		return this.tipoEncuesta;
	}

	public void setTipoEncuesta(String tipoEncuesta) {
		this.tipoEncuesta = tipoEncuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_inicio", length = 26)
	public Date getFecInicio() {
		return this.fecInicio;
	}

	public void setFecInicio(Date fecInicio) {
		this.fecInicio = fecInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_termino", length = 26)
	public Date getFecTermino() {
		return this.fecTermino;
	}

	public void setFecTermino(Date fecTermino) {
		this.fecTermino = fecTermino;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEncuesta")
	public Set<TLogVoto> getTLogVotos() {
		return this.TLogVotos;
	}

	public void setTLogVotos(Set<TLogVoto> TLogVotos) {
		this.TLogVotos = TLogVotos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEncuesta")
	public Set<TEncuestaResp> getTEncuestaResps() {
		return this.TEncuestaResps;
	}

	public void setTEncuestaResps(Set<TEncuestaResp> TEncuestaResps) {
		this.TEncuestaResps = TEncuestaResps;
	}

}
