package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TEncuestaResp generated by hbm2java
 */
@Entity
@Table(name = "T_ENCUESTA_RESP", schema = "WEB")
public class TEncuestaResp implements java.io.Serializable {

	private int idRespuesta;
	private TEncuesta TEncuesta;
	private String detRespuesta;
	private Integer votos;

	public TEncuestaResp() {
	}

	public TEncuestaResp(int idRespuesta) {
		this.idRespuesta = idRespuesta;
	}

	public TEncuestaResp(int idRespuesta, TEncuesta TEncuesta,
			String detRespuesta, Integer votos) {
		this.idRespuesta = idRespuesta;
		this.TEncuesta = TEncuesta;
		this.detRespuesta = detRespuesta;
		this.votos = votos;
	}

	@Id
	@Column(name = "id_respuesta", nullable = false)
	public int getIdRespuesta() {
		return this.idRespuesta;
	}

	public void setIdRespuesta(int idRespuesta) {
		this.idRespuesta = idRespuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_encuesta")
	public TEncuesta getTEncuesta() {
		return this.TEncuesta;
	}

	public void setTEncuesta(TEncuesta TEncuesta) {
		this.TEncuesta = TEncuesta;
	}

	@Column(name = "det_respuesta", length = 50)
	public String getDetRespuesta() {
		return this.detRespuesta;
	}

	public void setDetRespuesta(String detRespuesta) {
		this.detRespuesta = detRespuesta;
	}

	@Column(name = "votos")
	public Integer getVotos() {
		return this.votos;
	}

	public void setVotos(Integer votos) {
		this.votos = votos;
	}

}
