package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TEnlaces generated by hbm2java
 */
@Entity
@Table(name = "T_ENLACES", schema = "WEB")
public class TEnlaces implements java.io.Serializable {

	private int idLink;
	private TCatenalce TCatenalce;
	private String desLink;
	private String urlLink;
	private Integer estado;

	public TEnlaces() {
	}

	public TEnlaces(int idLink) {
		this.idLink = idLink;
	}

	public TEnlaces(int idLink, TCatenalce TCatenalce, String desLink,
			String urlLink, Integer estado) {
		this.idLink = idLink;
		this.TCatenalce = TCatenalce;
		this.desLink = desLink;
		this.urlLink = urlLink;
		this.estado = estado;
	}

	@Id
	@Column(name = "id_link", nullable = false)
	public int getIdLink() {
		return this.idLink;
	}

	public void setIdLink(int idLink) {
		this.idLink = idLink;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_link")
	public TCatenalce getTCatenalce() {
		return this.TCatenalce;
	}

	public void setTCatenalce(TCatenalce TCatenalce) {
		this.TCatenalce = TCatenalce;
	}

	@Column(name = "des_link", length = 200)
	public String getDesLink() {
		return this.desLink;
	}

	public void setDesLink(String desLink) {
		this.desLink = desLink;
	}

	@Column(name = "url_link", length = 250)
	public String getUrlLink() {
		return this.urlLink;
	}

	public void setUrlLink(String urlLink) {
		this.urlLink = urlLink;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

}
