package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TEstaSanciones generated by hbm2java
 */
@Entity
@Table(name = "T_ESTA_SANCIONES", schema = "WEB")
public class TEstaSanciones implements java.io.Serializable {

	private TEstaSancionesId id;

	public TEstaSanciones() {
	}

	public TEstaSanciones(TEstaSancionesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codSancion", column = @Column(name = "cod_sancion", nullable = false)),
			@AttributeOverride(name = "codConcepto", column = @Column(name = "cod_concepto")),
			@AttributeOverride(name = "totalMagistrados", column = @Column(name = "total_magistrados")),
			@AttributeOverride(name = "totalAux", column = @Column(name = "total_aux")),
			@AttributeOverride(name = "desMes", column = @Column(name = "des_mes", length = 50)),
			@AttributeOverride(name = "desAnio", column = @Column(name = "des_anio", length = 50)) })
	public TEstaSancionesId getId() {
		return this.id;
	}

	public void setId(TEstaSancionesId id) {
		this.id = id;
	}

}
