package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TEstaCategoria generated by hbm2java
 */
@Entity
@Table(name = "T_ESTA_CATEGORIA", schema = "WEB")
public class TEstaCategoria implements java.io.Serializable {

	private TEstaCategoriaId id;

	public TEstaCategoria() {
	}

	public TEstaCategoria(TEstaCategoriaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codCategoria", column = @Column(name = "cod_categoria", nullable = false)),
			@AttributeOverride(name = "desCategoria", column = @Column(name = "des_categoria", length = 50)) })
	public TEstaCategoriaId getId() {
		return this.id;
	}

	public void setId(TEstaCategoriaId id) {
		this.id = id;
	}

}
