package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TEstaMaster generated by hbm2java
 */
@Entity
@Table(name = "T_ESTA_MASTER", schema = "WEB")
public class TEstaMaster implements java.io.Serializable {

	private TEstaMasterId id;

	public TEstaMaster() {
	}

	public TEstaMaster(TEstaMasterId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codMaster", column = @Column(name = "cod_master", nullable = false)),
			@AttributeOverride(name = "codMes", column = @Column(name = "cod_mes")),
			@AttributeOverride(name = "desAnio", column = @Column(name = "des_anio")),
			@AttributeOverride(name = "codCategoria", column = @Column(name = "cod_categoria")),
			@AttributeOverride(name = "codConcepto", column = @Column(name = "cod_concepto")),
			@AttributeOverride(name = "cantidad", column = @Column(name = "cantidad")) })
	public TEstaMasterId getId() {
		return this.id;
	}

	public void setId(TEstaMasterId id) {
		this.id = id;
	}

}
