package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TEstaConceptosId generated by hbm2java
 */
@Embeddable
public class TEstaConceptosId implements java.io.Serializable {

	private int codConcepto;
	private String desConcepto;
	private Integer flagEstado;
	private Integer tipoConcepto;

	public TEstaConceptosId() {
	}

	public TEstaConceptosId(int codConcepto) {
		this.codConcepto = codConcepto;
	}

	public TEstaConceptosId(int codConcepto, String desConcepto,
			Integer flagEstado, Integer tipoConcepto) {
		this.codConcepto = codConcepto;
		this.desConcepto = desConcepto;
		this.flagEstado = flagEstado;
		this.tipoConcepto = tipoConcepto;
	}

	@Column(name = "cod_concepto", nullable = false)
	public int getCodConcepto() {
		return this.codConcepto;
	}

	public void setCodConcepto(int codConcepto) {
		this.codConcepto = codConcepto;
	}

	@Column(name = "des_concepto", length = 200)
	public String getDesConcepto() {
		return this.desConcepto;
	}

	public void setDesConcepto(String desConcepto) {
		this.desConcepto = desConcepto;
	}

	@Column(name = "flag_estado")
	public Integer getFlagEstado() {
		return this.flagEstado;
	}

	public void setFlagEstado(Integer flagEstado) {
		this.flagEstado = flagEstado;
	}

	@Column(name = "tipo_concepto")
	public Integer getTipoConcepto() {
		return this.tipoConcepto;
	}

	public void setTipoConcepto(Integer tipoConcepto) {
		this.tipoConcepto = tipoConcepto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEstaConceptosId))
			return false;
		TEstaConceptosId castOther = (TEstaConceptosId) other;

		return (this.getCodConcepto() == castOther.getCodConcepto())
				&& ((this.getDesConcepto() == castOther.getDesConcepto()) || (this
						.getDesConcepto() != null
						&& castOther.getDesConcepto() != null && this
						.getDesConcepto().equals(castOther.getDesConcepto())))
				&& ((this.getFlagEstado() == castOther.getFlagEstado()) || (this
						.getFlagEstado() != null
						&& castOther.getFlagEstado() != null && this
						.getFlagEstado().equals(castOther.getFlagEstado())))
				&& ((this.getTipoConcepto() == castOther.getTipoConcepto()) || (this
						.getTipoConcepto() != null
						&& castOther.getTipoConcepto() != null && this
						.getTipoConcepto().equals(castOther.getTipoConcepto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodConcepto();
		result = 37
				* result
				+ (getDesConcepto() == null ? 0 : this.getDesConcepto()
						.hashCode());
		result = 37
				* result
				+ (getFlagEstado() == null ? 0 : this.getFlagEstado()
						.hashCode());
		result = 37
				* result
				+ (getTipoConcepto() == null ? 0 : this.getTipoConcepto()
						.hashCode());
		return result;
	}

}
