package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TEstaMeses generated by hbm2java
 */
@Entity
@Table(name = "T_ESTA_MESES", schema = "WEB")
public class TEstaMeses implements java.io.Serializable {

	private TEstaMesesId id;

	public TEstaMeses() {
	}

	public TEstaMeses(TEstaMesesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codMes", column = @Column(name = "cod_mes", nullable = false)),
			@AttributeOverride(name = "desMes", column = @Column(name = "des_mes", length = 50)),
			@AttributeOverride(name = "abrMes", column = @Column(name = "abr_mes", length = 50)) })
	public TEstaMesesId getId() {
		return this.id;
	}

	public void setId(TEstaMesesId id) {
		this.id = id;
	}

}
