package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TEstaMasterId generated by hbm2java
 */
@Embeddable
public class TEstaMasterId implements java.io.Serializable {

	private int codMaster;
	private Integer codMes;
	private Integer desAnio;
	private Integer codCategoria;
	private Integer codConcepto;
	private Integer cantidad;

	public TEstaMasterId() {
	}

	public TEstaMasterId(int codMaster) {
		this.codMaster = codMaster;
	}

	public TEstaMasterId(int codMaster, Integer codMes, Integer desAnio,
			Integer codCategoria, Integer codConcepto, Integer cantidad) {
		this.codMaster = codMaster;
		this.codMes = codMes;
		this.desAnio = desAnio;
		this.codCategoria = codCategoria;
		this.codConcepto = codConcepto;
		this.cantidad = cantidad;
	}

	@Column(name = "cod_master", nullable = false)
	public int getCodMaster() {
		return this.codMaster;
	}

	public void setCodMaster(int codMaster) {
		this.codMaster = codMaster;
	}

	@Column(name = "cod_mes")
	public Integer getCodMes() {
		return this.codMes;
	}

	public void setCodMes(Integer codMes) {
		this.codMes = codMes;
	}

	@Column(name = "des_anio")
	public Integer getDesAnio() {
		return this.desAnio;
	}

	public void setDesAnio(Integer desAnio) {
		this.desAnio = desAnio;
	}

	@Column(name = "cod_categoria")
	public Integer getCodCategoria() {
		return this.codCategoria;
	}

	public void setCodCategoria(Integer codCategoria) {
		this.codCategoria = codCategoria;
	}

	@Column(name = "cod_concepto")
	public Integer getCodConcepto() {
		return this.codConcepto;
	}

	public void setCodConcepto(Integer codConcepto) {
		this.codConcepto = codConcepto;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEstaMasterId))
			return false;
		TEstaMasterId castOther = (TEstaMasterId) other;

		return (this.getCodMaster() == castOther.getCodMaster())
				&& ((this.getCodMes() == castOther.getCodMes()) || (this
						.getCodMes() != null && castOther.getCodMes() != null && this
						.getCodMes().equals(castOther.getCodMes())))
				&& ((this.getDesAnio() == castOther.getDesAnio()) || (this
						.getDesAnio() != null && castOther.getDesAnio() != null && this
						.getDesAnio().equals(castOther.getDesAnio())))
				&& ((this.getCodCategoria() == castOther.getCodCategoria()) || (this
						.getCodCategoria() != null
						&& castOther.getCodCategoria() != null && this
						.getCodCategoria().equals(castOther.getCodCategoria())))
				&& ((this.getCodConcepto() == castOther.getCodConcepto()) || (this
						.getCodConcepto() != null
						&& castOther.getCodConcepto() != null && this
						.getCodConcepto().equals(castOther.getCodConcepto())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this
						.getCantidad() != null
						&& castOther.getCantidad() != null && this
						.getCantidad().equals(castOther.getCantidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodMaster();
		result = 37 * result
				+ (getCodMes() == null ? 0 : this.getCodMes().hashCode());
		result = 37 * result
				+ (getDesAnio() == null ? 0 : this.getDesAnio().hashCode());
		result = 37
				* result
				+ (getCodCategoria() == null ? 0 : this.getCodCategoria()
						.hashCode());
		result = 37
				* result
				+ (getCodConcepto() == null ? 0 : this.getCodConcepto()
						.hashCode());
		result = 37 * result
				+ (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		return result;
	}

}
