package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TEstaConceptos generated by hbm2java
 */
@Entity
@Table(name = "T_ESTA_CONCEPTOS", schema = "WEB")
public class TEstaConceptos implements java.io.Serializable {

	private TEstaConceptosId id;

	public TEstaConceptos() {
	}

	public TEstaConceptos(TEstaConceptosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codConcepto", column = @Column(name = "cod_concepto", nullable = false)),
			@AttributeOverride(name = "desConcepto", column = @Column(name = "des_concepto", length = 200)),
			@AttributeOverride(name = "flagEstado", column = @Column(name = "flag_estado")),
			@AttributeOverride(name = "tipoConcepto", column = @Column(name = "tipo_concepto")) })
	public TEstaConceptosId getId() {
		return this.id;
	}

	public void setId(TEstaConceptosId id) {
		this.id = id;
	}

}
