package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLogVoto generated by hbm2java
 */
@Entity
@Table(name = "T_LOG_VOTO", schema = "WEB")
public class TLogVoto implements java.io.Serializable {

	private int idCorrelativo;
	private TEncuesta TEncuesta;
	private String desIp;
	private Date horaVoto;
	private int flaActivo;
	private int tipMovi;
	private String desIpProxy;
	private Integer idVoto;

	public TLogVoto() {
	}

	public TLogVoto(int idCorrelativo, String desIp, int flaActivo, int tipMovi) {
		this.idCorrelativo = idCorrelativo;
		this.desIp = desIp;
		this.flaActivo = flaActivo;
		this.tipMovi = tipMovi;
	}

	public TLogVoto(int idCorrelativo, TEncuesta TEncuesta, String desIp,
			Date horaVoto, int flaActivo, int tipMovi, String desIpProxy,
			Integer idVoto) {
		this.idCorrelativo = idCorrelativo;
		this.TEncuesta = TEncuesta;
		this.desIp = desIp;
		this.horaVoto = horaVoto;
		this.flaActivo = flaActivo;
		this.tipMovi = tipMovi;
		this.desIpProxy = desIpProxy;
		this.idVoto = idVoto;
	}

	@Id
	@Column(name = "id_correlativo", nullable = false)
	public int getIdCorrelativo() {
		return this.idCorrelativo;
	}

	public void setIdCorrelativo(int idCorrelativo) {
		this.idCorrelativo = idCorrelativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_encuesta")
	public TEncuesta getTEncuesta() {
		return this.TEncuesta;
	}

	public void setTEncuesta(TEncuesta TEncuesta) {
		this.TEncuesta = TEncuesta;
	}

	@Column(name = "des_ip", nullable = false, length = 50)
	public String getDesIp() {
		return this.desIp;
	}

	public void setDesIp(String desIp) {
		this.desIp = desIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_voto", length = 26)
	public Date getHoraVoto() {
		return this.horaVoto;
	}

	public void setHoraVoto(Date horaVoto) {
		this.horaVoto = horaVoto;
	}

	@Column(name = "fla_activo", nullable = false)
	public int getFlaActivo() {
		return this.flaActivo;
	}

	public void setFlaActivo(int flaActivo) {
		this.flaActivo = flaActivo;
	}

	@Column(name = "tip_movi", nullable = false)
	public int getTipMovi() {
		return this.tipMovi;
	}

	public void setTipMovi(int tipMovi) {
		this.tipMovi = tipMovi;
	}

	@Column(name = "des_ip_proxy", length = 50)
	public String getDesIpProxy() {
		return this.desIpProxy;
	}

	public void setDesIpProxy(String desIpProxy) {
		this.desIpProxy = desIpProxy;
	}

	@Column(name = "id_voto")
	public Integer getIdVoto() {
		return this.idVoto;
	}

	public void setIdVoto(Integer idVoto) {
		this.idVoto = idVoto;
	}

}
