package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TModulos generated by hbm2java
 */
@Entity
@Table(name = "T_MODULOS", schema = "WEB")
public class TModulos implements java.io.Serializable {

	private int idModulo;
	private String nombreModulo;
	private String descripModulo;
	private String abreModulo;
	private Integer estadoModulo;
	private Integer autorModulo;
	private Date fecmodModulo;

	public TModulos() {
	}

	public TModulos(int idModulo) {
		this.idModulo = idModulo;
	}

	public TModulos(int idModulo, String nombreModulo, String descripModulo,
			String abreModulo, Integer estadoModulo, Integer autorModulo,
			Date fecmodModulo) {
		this.idModulo = idModulo;
		this.nombreModulo = nombreModulo;
		this.descripModulo = descripModulo;
		this.abreModulo = abreModulo;
		this.estadoModulo = estadoModulo;
		this.autorModulo = autorModulo;
		this.fecmodModulo = fecmodModulo;
	}

	@Id
	@Column(name = "id_modulo", nullable = false)
	public int getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(int idModulo) {
		this.idModulo = idModulo;
	}

	@Column(name = "nombre_modulo", length = 50)
	public String getNombreModulo() {
		return this.nombreModulo;
	}

	public void setNombreModulo(String nombreModulo) {
		this.nombreModulo = nombreModulo;
	}

	@Column(name = "descrip_modulo", length = 200)
	public String getDescripModulo() {
		return this.descripModulo;
	}

	public void setDescripModulo(String descripModulo) {
		this.descripModulo = descripModulo;
	}

	@Column(name = "abre_modulo", length = 50)
	public String getAbreModulo() {
		return this.abreModulo;
	}

	public void setAbreModulo(String abreModulo) {
		this.abreModulo = abreModulo;
	}

	@Column(name = "estado_modulo")
	public Integer getEstadoModulo() {
		return this.estadoModulo;
	}

	public void setEstadoModulo(Integer estadoModulo) {
		this.estadoModulo = estadoModulo;
	}

	@Column(name = "autor_modulo")
	public Integer getAutorModulo() {
		return this.autorModulo;
	}

	public void setAutorModulo(Integer autorModulo) {
		this.autorModulo = autorModulo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecmod_modulo", length = 26)
	public Date getFecmodModulo() {
		return this.fecmodModulo;
	}

	public void setFecmodModulo(Date fecmodModulo) {
		this.fecmodModulo = fecmodModulo;
	}

}
