package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TNoticiaOrigen generated by hbm2java
 */
@Entity
@Table(name = "T_NOTICIA_ORIGEN", schema = "WEB")
public class TNoticiaOrigen implements java.io.Serializable {

	private int origenId;
	private String origenNombre;
	private String origenUrl;
	private String origenImagen;
	private Integer origenEstado;
	private Integer origenCategoria;

	public TNoticiaOrigen() {
	}

	public TNoticiaOrigen(int origenId) {
		this.origenId = origenId;
	}

	public TNoticiaOrigen(int origenId, String origenNombre, String origenUrl,
			String origenImagen, Integer origenEstado, Integer origenCategoria) {
		this.origenId = origenId;
		this.origenNombre = origenNombre;
		this.origenUrl = origenUrl;
		this.origenImagen = origenImagen;
		this.origenEstado = origenEstado;
		this.origenCategoria = origenCategoria;
	}

	@Id
	@Column(name = "origen_id", nullable = false)
	public int getOrigenId() {
		return this.origenId;
	}

	public void setOrigenId(int origenId) {
		this.origenId = origenId;
	}

	@Column(name = "origen_nombre", length = 200)
	public String getOrigenNombre() {
		return this.origenNombre;
	}

	public void setOrigenNombre(String origenNombre) {
		this.origenNombre = origenNombre;
	}

	@Column(name = "origen_url", length = 200)
	public String getOrigenUrl() {
		return this.origenUrl;
	}

	public void setOrigenUrl(String origenUrl) {
		this.origenUrl = origenUrl;
	}

	@Column(name = "origen_imagen", length = 200)
	public String getOrigenImagen() {
		return this.origenImagen;
	}

	public void setOrigenImagen(String origenImagen) {
		this.origenImagen = origenImagen;
	}

	@Column(name = "origen_estado")
	public Integer getOrigenEstado() {
		return this.origenEstado;
	}

	public void setOrigenEstado(Integer origenEstado) {
		this.origenEstado = origenEstado;
	}

	@Column(name = "origen_categoria")
	public Integer getOrigenCategoria() {
		return this.origenCategoria;
	}

	public void setOrigenCategoria(Integer origenCategoria) {
		this.origenCategoria = origenCategoria;
	}

}
