package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPrensaCategoria generated by hbm2java
 */
@Entity
@Table(name = "T_PRENSA_CATEGORIA", schema = "WEB")
public class TPrensaCategoria implements java.io.Serializable {

	private int idCategoria;
	private String desCategoria;
	private int flaCategoria;
	private Set<TPrensa> TPrensas = new HashSet<TPrensa>(0);
	private Set<TPrensaTipo> TPrensaTipos = new HashSet<TPrensaTipo>(0);

	public TPrensaCategoria() {
	}

	public TPrensaCategoria(int idCategoria, String desCategoria,
			int flaCategoria) {
		this.idCategoria = idCategoria;
		this.desCategoria = desCategoria;
		this.flaCategoria = flaCategoria;
	}

	public TPrensaCategoria(int idCategoria, String desCategoria,
			int flaCategoria, Set<TPrensa> TPrensas,
			Set<TPrensaTipo> TPrensaTipos) {
		this.idCategoria = idCategoria;
		this.desCategoria = desCategoria;
		this.flaCategoria = flaCategoria;
		this.TPrensas = TPrensas;
		this.TPrensaTipos = TPrensaTipos;
	}

	@Id
	@Column(name = "id_categoria", nullable = false)
	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "des_categoria", nullable = false, length = 250)
	public String getDesCategoria() {
		return this.desCategoria;
	}

	public void setDesCategoria(String desCategoria) {
		this.desCategoria = desCategoria;
	}

	@Column(name = "fla_categoria", nullable = false)
	public int getFlaCategoria() {
		return this.flaCategoria;
	}

	public void setFlaCategoria(int flaCategoria) {
		this.flaCategoria = flaCategoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPrensaCategoria")
	public Set<TPrensa> getTPrensas() {
		return this.TPrensas;
	}

	public void setTPrensas(Set<TPrensa> TPrensas) {
		this.TPrensas = TPrensas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPrensaCategoria")
	public Set<TPrensaTipo> getTPrensaTipos() {
		return this.TPrensaTipos;
	}

	public void setTPrensaTipos(Set<TPrensaTipo> TPrensaTipos) {
		this.TPrensaTipos = TPrensaTipos;
	}

}
