package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPrensa generated by hbm2java
 */
@Entity
@Table(name = "T_PRENSA", schema = "WEB")
public class TPrensa implements java.io.Serializable {

	private int idNoticia;
	private TPrensaCategoria TPrensaCategoria;
	private TDistritos TDistritos;
	private TPrensaTipo TPrensaTipo;
	private Integer origenNoticia;
	private String titularNoticia;
	private String contenidoNoticia;
	private String urlNoticia;
	private Date fechaNoticia;
	private Integer estadoNoticia;
	private int flaPrincipal;
	private String urlImagen;
	private String resumenNoticia;
	private String fecNoticia;
	private Date fecCreacion;

	public TPrensa() {
	}

	public TPrensa(int idNoticia, TPrensaCategoria TPrensaCategoria,
			TPrensaTipo TPrensaTipo, int flaPrincipal) {
		this.idNoticia = idNoticia;
		this.TPrensaCategoria = TPrensaCategoria;
		this.TPrensaTipo = TPrensaTipo;
		this.flaPrincipal = flaPrincipal;
	}

	public TPrensa(int idNoticia, TPrensaCategoria TPrensaCategoria,
			TDistritos TDistritos, TPrensaTipo TPrensaTipo,
			Integer origenNoticia, String titularNoticia,
			String contenidoNoticia, String urlNoticia, Date fechaNoticia,
			Integer estadoNoticia, int flaPrincipal, String urlImagen,
			String resumenNoticia, String fecNoticia, Date fecCreacion) {
		this.idNoticia = idNoticia;
		this.TPrensaCategoria = TPrensaCategoria;
		this.TDistritos = TDistritos;
		this.TPrensaTipo = TPrensaTipo;
		this.origenNoticia = origenNoticia;
		this.titularNoticia = titularNoticia;
		this.contenidoNoticia = contenidoNoticia;
		this.urlNoticia = urlNoticia;
		this.fechaNoticia = fechaNoticia;
		this.estadoNoticia = estadoNoticia;
		this.flaPrincipal = flaPrincipal;
		this.urlImagen = urlImagen;
		this.resumenNoticia = resumenNoticia;
		this.fecNoticia = fecNoticia;
		this.fecCreacion = fecCreacion;
	}

	@Id
	@Column(name = "id_noticia", nullable = false)
	public int getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(int idNoticia) {
		this.idNoticia = idNoticia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria", nullable = false)
	public TPrensaCategoria getTPrensaCategoria() {
		return this.TPrensaCategoria;
	}

	public void setTPrensaCategoria(TPrensaCategoria TPrensaCategoria) {
		this.TPrensaCategoria = TPrensaCategoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "distri_noticia")
	public TDistritos getTDistritos() {
		return this.TDistritos;
	}

	public void setTDistritos(TDistritos TDistritos) {
		this.TDistritos = TDistritos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo", nullable = false)
	public TPrensaTipo getTPrensaTipo() {
		return this.TPrensaTipo;
	}

	public void setTPrensaTipo(TPrensaTipo TPrensaTipo) {
		this.TPrensaTipo = TPrensaTipo;
	}

	@Column(name = "origen_noticia")
	public Integer getOrigenNoticia() {
		return this.origenNoticia;
	}

	public void setOrigenNoticia(Integer origenNoticia) {
		this.origenNoticia = origenNoticia;
	}

	@Column(name = "titular_noticia")
	public String getTitularNoticia() {
		return this.titularNoticia;
	}

	public void setTitularNoticia(String titularNoticia) {
		this.titularNoticia = titularNoticia;
	}

	@Column(name = "contenido_noticia")
	public String getContenidoNoticia() {
		return this.contenidoNoticia;
	}

	public void setContenidoNoticia(String contenidoNoticia) {
		this.contenidoNoticia = contenidoNoticia;
	}

	@Column(name = "url_noticia", length = 200)
	public String getUrlNoticia() {
		return this.urlNoticia;
	}

	public void setUrlNoticia(String urlNoticia) {
		this.urlNoticia = urlNoticia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_noticia", length = 26)
	public Date getFechaNoticia() {
		return this.fechaNoticia;
	}

	public void setFechaNoticia(Date fechaNoticia) {
		this.fechaNoticia = fechaNoticia;
	}

	@Column(name = "estado_noticia")
	public Integer getEstadoNoticia() {
		return this.estadoNoticia;
	}

	public void setEstadoNoticia(Integer estadoNoticia) {
		this.estadoNoticia = estadoNoticia;
	}

	@Column(name = "fla_principal", nullable = false)
	public int getFlaPrincipal() {
		return this.flaPrincipal;
	}

	public void setFlaPrincipal(int flaPrincipal) {
		this.flaPrincipal = flaPrincipal;
	}

	@Column(name = "url_imagen", length = 600)
	public String getUrlImagen() {
		return this.urlImagen;
	}

	public void setUrlImagen(String urlImagen) {
		this.urlImagen = urlImagen;
	}

	@Column(name = "resumen_noticia")
	public String getResumenNoticia() {
		return this.resumenNoticia;
	}

	public void setResumenNoticia(String resumenNoticia) {
		this.resumenNoticia = resumenNoticia;
	}

	@Column(name = "fec_noticia", length = 10)
	public String getFecNoticia() {
		return this.fecNoticia;
	}

	public void setFecNoticia(String fecNoticia) {
		this.fecNoticia = fecNoticia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_creacion", length = 26)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

}
