package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPrensaVisita generated by hbm2java
 */
@Entity
@Table(name = "T_PRENSA_VISITA", schema = "WEB")
public class TPrensaVisita implements java.io.Serializable {

	private int codPrensaVisita;
	private Date fecPrensaVisita;
	private String obsPrensaVisita;
	private Integer codDistritojudicial;
	private Integer idcategoria;
	private Integer origenId;

	public TPrensaVisita() {
	}

	public TPrensaVisita(int codPrensaVisita) {
		this.codPrensaVisita = codPrensaVisita;
	}

	public TPrensaVisita(int codPrensaVisita, Date fecPrensaVisita,
			String obsPrensaVisita, Integer codDistritojudicial,
			Integer idcategoria, Integer origenId) {
		this.codPrensaVisita = codPrensaVisita;
		this.fecPrensaVisita = fecPrensaVisita;
		this.obsPrensaVisita = obsPrensaVisita;
		this.codDistritojudicial = codDistritojudicial;
		this.idcategoria = idcategoria;
		this.origenId = origenId;
	}

	@Id
	@Column(name = "COD_PRENSA_VISITA", nullable = false)
	public int getCodPrensaVisita() {
		return this.codPrensaVisita;
	}

	public void setCodPrensaVisita(int codPrensaVisita) {
		this.codPrensaVisita = codPrensaVisita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_PRENSA_VISITA", length = 10)
	public Date getFecPrensaVisita() {
		return this.fecPrensaVisita;
	}

	public void setFecPrensaVisita(Date fecPrensaVisita) {
		this.fecPrensaVisita = fecPrensaVisita;
	}

	@Column(name = "OBS_PRENSA_VISITA", length = 250)
	public String getObsPrensaVisita() {
		return this.obsPrensaVisita;
	}

	public void setObsPrensaVisita(String obsPrensaVisita) {
		this.obsPrensaVisita = obsPrensaVisita;
	}

	@Column(name = "COD_DISTRITOJUDICIAL")
	public Integer getCodDistritojudicial() {
		return this.codDistritojudicial;
	}

	public void setCodDistritojudicial(Integer codDistritojudicial) {
		this.codDistritojudicial = codDistritojudicial;
	}

	@Column(name = "IDCATEGORIA")
	public Integer getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(Integer idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "ORIGEN_ID")
	public Integer getOrigenId() {
		return this.origenId;
	}

	public void setOrigenId(Integer origenId) {
		this.origenId = origenId;
	}

}
