package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPrensaTipo generated by hbm2java
 */
@Entity
@Table(name = "T_PRENSA_TIPO", schema = "WEB")
public class TPrensaTipo implements java.io.Serializable {

	private int idTipo;
	private TPrensaCategoria TPrensaCategoria;
	private String desTipo;
	private int flaTipo;
	private Set<TPrensa> TPrensas = new HashSet<TPrensa>(0);

	public TPrensaTipo() {
	}

	public TPrensaTipo(int idTipo, TPrensaCategoria TPrensaCategoria,
			String desTipo, int flaTipo) {
		this.idTipo = idTipo;
		this.TPrensaCategoria = TPrensaCategoria;
		this.desTipo = desTipo;
		this.flaTipo = flaTipo;
	}

	public TPrensaTipo(int idTipo, TPrensaCategoria TPrensaCategoria,
			String desTipo, int flaTipo, Set<TPrensa> TPrensas) {
		this.idTipo = idTipo;
		this.TPrensaCategoria = TPrensaCategoria;
		this.desTipo = desTipo;
		this.flaTipo = flaTipo;
		this.TPrensas = TPrensas;
	}

	@Id
	@Column(name = "id_tipo", nullable = false)
	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria", nullable = false)
	public TPrensaCategoria getTPrensaCategoria() {
		return this.TPrensaCategoria;
	}

	public void setTPrensaCategoria(TPrensaCategoria TPrensaCategoria) {
		this.TPrensaCategoria = TPrensaCategoria;
	}

	@Column(name = "des_tipo", nullable = false, length = 250)
	public String getDesTipo() {
		return this.desTipo;
	}

	public void setDesTipo(String desTipo) {
		this.desTipo = desTipo;
	}

	@Column(name = "fla_tipo", nullable = false)
	public int getFlaTipo() {
		return this.flaTipo;
	}

	public void setFlaTipo(int flaTipo) {
		this.flaTipo = flaTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPrensaTipo")
	public Set<TPrensa> getTPrensas() {
		return this.TPrensas;
	}

	public void setTPrensas(Set<TPrensa> TPrensas) {
		this.TPrensas = TPrensas;
	}

}
