package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TPrensa2 generated by hbm2java
 */
@Entity
@Table(name = "T_PRENSA_2", schema = "WEB")
public class TPrensa2 implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private int idNoticia;
	private Integer origenNoticia;
	private String titularNoticia;
	private String contenidoNoticia;
	private String urlNoticia;
	private Date fechaNoticia;
	private Integer estadoNoticia;
	private EstadoNoticia desEstado; 
	private int tipoNoticia;
	private TPrensaTipo desTipNot;
	private int cateNoticia;
	private Integer distriNoticia;
	private int flaPrincipal;
	private String urlImagen;
	private String resumenNoticia;
	private String fecNoticia;
	private Date fecCreacion;
	private Integer annioResolucion;
	private String urlPdf;
	private String urlVideo;
	private String urlConsejo;
	private Date fechaConsejo;
	private String sumilla;
	private String nroNotaPrensa;
	
	public TPrensa2() {
	}

	@Id
	@Column(name = "id_noticia", nullable = false)
	public int getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(int idNoticia) {
		this.idNoticia = idNoticia;
	}

	@Column(name = "origen_noticia")
	public Integer getOrigenNoticia() {
		return this.origenNoticia;
	}

	public void setOrigenNoticia(Integer origenNoticia) {
		this.origenNoticia = origenNoticia;
	}

	@Column(name = "titular_noticia")
	public String getTitularNoticia() {
		return this.titularNoticia;
	}

	public void setTitularNoticia(String titularNoticia) {
		this.titularNoticia = titularNoticia;
	}

	@Column(name = "contenido_noticia")
	public String getContenidoNoticia() {
		return this.contenidoNoticia;
	}

	public void setContenidoNoticia(String contenidoNoticia) {
		this.contenidoNoticia = contenidoNoticia;
	}

	@Column(name = "url_noticia", length = 200)
	public String getUrlNoticia() {
		return this.urlNoticia;
	}

	public void setUrlNoticia(String urlNoticia) {
		this.urlNoticia = urlNoticia;
	}

	@Column(name = "fecha_noticia", length = 10)
	public Date getFechaNoticia() {
		return this.fechaNoticia;
	}

	public void setFechaNoticia(Date fechaNoticia) {
		this.fechaNoticia = fechaNoticia;
	}

	@Column(name = "estado_noticia")
	public Integer getEstadoNoticia() {
		return this.estadoNoticia;
	}

	public void setEstadoNoticia(Integer estadoNoticia) {
		this.estadoNoticia = estadoNoticia;
	}

	@Column(name = "tipo_noticia", nullable = false)
	public int getTipoNoticia() {
		return this.tipoNoticia;
	}

	public void setTipoNoticia(int tipoNoticia) {
		this.tipoNoticia = tipoNoticia;
	}

	@Column(name = "cate_noticia", nullable = false)
	public int getCateNoticia() {
		return this.cateNoticia;
	}

	public void setCateNoticia(int cateNoticia) {
		this.cateNoticia = cateNoticia;
	}

	@Column(name = "distri_noticia")
	public Integer getDistriNoticia() {
		return this.distriNoticia;
	}

	public void setDistriNoticia(Integer distriNoticia) {
		this.distriNoticia = distriNoticia;
	}

	@Column(name = "fla_principal", nullable = false)
	public int getFlaPrincipal() {
		return this.flaPrincipal;
	}

	public void setFlaPrincipal(int flaPrincipal) {
		this.flaPrincipal = flaPrincipal;
	}

	@Column(name = "url_imagen", length = 600)
	public String getUrlImagen() {
		return this.urlImagen;
	}

	public void setUrlImagen(String urlImagen) {
		this.urlImagen = urlImagen;
	}

	@Column(name = "resumen_noticia")
	public String getResumenNoticia() {
		return this.resumenNoticia;
	}

	public void setResumenNoticia(String resumenNoticia) {
		this.resumenNoticia = resumenNoticia;
	}

	@Column(name = "fec_noticia", length = 10)
	public String getFecNoticia() {
		return this.fecNoticia;
	}

	public void setFecNoticia(String fecNoticia) {
		this.fecNoticia = fecNoticia;
	}

	@Column(name = "fec_creacion", length = 10)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Column(name = "annio_resolucion")
	public Integer getAnnioResolucion() {
		return this.annioResolucion;
	}

	public void setAnnioResolucion(Integer annioResolucion) {
		this.annioResolucion = annioResolucion;
	}

	@Column(name = "url_pdf", length = 200)
	public String getUrlPdf() {
		return this.urlPdf;
	}

	public void setUrlPdf(String urlPdf) {
		this.urlPdf = urlPdf;
	}

	@Column(name = "url_video", length = 200)
	public String getUrlVideo() {
		return this.urlVideo;
	}

	public void setUrlVideo(String urlVideo) {
		this.urlVideo = urlVideo;
	}

	@Column(name = "url_consejo", length = 300)
	public String getUrlConsejo() {
		return this.urlConsejo;
	}

	public void setUrlConsejo(String urlConsejo) {
		this.urlConsejo = urlConsejo;
	}

	@Column(name = "fecha_consejo", length = 10)
	public Date getFechaConsejo() {
		return this.fechaConsejo;
	}

	public void setFechaConsejo(Date fechaConsejo) {
		this.fechaConsejo = fechaConsejo;
	}

	@Column(name = "sumilla", length = 200)
	public String getSumilla() {
		return this.sumilla;
	}

	public void setSumilla(String sumilla) {
		this.sumilla = sumilla;
	}

	@Column(name = "nro_nota_prensa", length = 200)
	public String getNroNotaPrensa() {
		return this.nroNotaPrensa;
	}

	public void setNroNotaPrensa(String nroNotaPrensa) {
		this.nroNotaPrensa = nroNotaPrensa;
	}
	

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="estado_noticia", insertable=false, updatable=false)
	public EstadoNoticia getDesEstado() {
		return desEstado;
	}

	public void setDesEstado(EstadoNoticia desEstado) {
		this.desEstado = desEstado;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="tipo_noticia", insertable=false, updatable=false)
	public TPrensaTipo getDesTipNot() {
		return desTipNot;
	}

	public void setDesTipNot(TPrensaTipo desTipNot) {
		this.desTipNot = desTipNot;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idNoticia;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TPrensa2 other = (TPrensa2) obj;
		if (idNoticia != other.idNoticia)
			return false;
		return true;
	}
	
}
