package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TPrensaxdistritoId generated by hbm2java
 */
@Embeddable
public class TPrensaxdistritoId implements java.io.Serializable {

	private int codDistri;
	private int idNoticia;
	private Integer annioResolucion;

	public TPrensaxdistritoId() {
	}

	public TPrensaxdistritoId(int codDistri, int idNoticia) {
		this.codDistri = codDistri;
		this.idNoticia = idNoticia;
	}

	public TPrensaxdistritoId(int codDistri, int idNoticia,
			Integer annioResolucion) {
		this.codDistri = codDistri;
		this.idNoticia = idNoticia;
		this.annioResolucion = annioResolucion;
	}

	@Column(name = "cod_distri", nullable = false)
	public int getCodDistri() {
		return this.codDistri;
	}

	public void setCodDistri(int codDistri) {
		this.codDistri = codDistri;
	}

	@Column(name = "id_noticia", nullable = false)
	public int getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(int idNoticia) {
		this.idNoticia = idNoticia;
	}

	@Column(name = "annio_resolucion")
	public Integer getAnnioResolucion() {
		return this.annioResolucion;
	}

	public void setAnnioResolucion(Integer annioResolucion) {
		this.annioResolucion = annioResolucion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TPrensaxdistritoId))
			return false;
		TPrensaxdistritoId castOther = (TPrensaxdistritoId) other;

		return (this.getCodDistri() == castOther.getCodDistri())
				&& (this.getIdNoticia() == castOther.getIdNoticia())
				&& ((this.getAnnioResolucion() == castOther
						.getAnnioResolucion()) || (this.getAnnioResolucion() != null
						&& castOther.getAnnioResolucion() != null && this
						.getAnnioResolucion().equals(
								castOther.getAnnioResolucion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodDistri();
		result = 37 * result + this.getIdNoticia();
		result = 37
				* result
				+ (getAnnioResolucion() == null ? 0 : this.getAnnioResolucion()
						.hashCode());
		return result;
	}

}
