package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TPrensaxdistrito generated by hbm2java
 */
@Entity
@Table(name = "t_prensaxdistrito", schema = "WEB")
public class TPrensaxdistrito implements java.io.Serializable {

	private TPrensaxdistritoId id;

	public TPrensaxdistrito() {
	}

	public TPrensaxdistrito(TPrensaxdistritoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codDistri", column = @Column(name = "cod_distri", nullable = false)),
			@AttributeOverride(name = "idNoticia", column = @Column(name = "id_noticia", nullable = false)),
			@AttributeOverride(name = "annioResolucion", column = @Column(name = "annio_resolucion")) })
	public TPrensaxdistritoId getId() {
		return this.id;
	}

	public void setId(TPrensaxdistritoId id) {
		this.id = id;
	}

}
