package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TQuejasMotivos generated by hbm2java
 */
@Entity
@Table(name = "T_QUEJAS_MOTIVOS", schema = "WEB")
public class TQuejasMotivos implements java.io.Serializable {

	private int correlativo;
	private int codQueja;
	private int codMotivo;

	public TQuejasMotivos() {
	}

	public TQuejasMotivos(int correlativo, int codQueja, int codMotivo) {
		this.correlativo = correlativo;
		this.codQueja = codQueja;
		this.codMotivo = codMotivo;
	}

	@Id
	@Column(name = "correlativo", nullable = false)
	public int getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(int correlativo) {
		this.correlativo = correlativo;
	}

	@Column(name = "cod_queja", nullable = false)
	public int getCodQueja() {
		return this.codQueja;
	}

	public void setCodQueja(int codQueja) {
		this.codQueja = codQueja;
	}

	@Column(name = "cod_motivo", nullable = false)
	public int getCodMotivo() {
		return this.codMotivo;
	}

	public void setCodMotivo(int codMotivo) {
		this.codMotivo = codMotivo;
	}

}
