package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TQuejaMovi generated by hbm2java
 */
@Entity
@Table(name = "T_QUEJA_MOVI", schema = "WEB")
public class TQuejaMovi implements java.io.Serializable {

	private int codMovi;
	private Integer codQueja;
	private String desMovi;
	private Integer flaEstado;
	private String codUsuarioAten;
	private Date fecMovi;

	public TQuejaMovi() {
	}

	public TQuejaMovi(int codMovi) {
		this.codMovi = codMovi;
	}

	public TQuejaMovi(int codMovi, Integer codQueja, String desMovi,
			Integer flaEstado, String codUsuarioAten, Date fecMovi) {
		this.codMovi = codMovi;
		this.codQueja = codQueja;
		this.desMovi = desMovi;
		this.flaEstado = flaEstado;
		this.codUsuarioAten = codUsuarioAten;
		this.fecMovi = fecMovi;
	}

	@Id
	@Column(name = "cod_movi", nullable = false)
	public int getCodMovi() {
		return this.codMovi;
	}

	public void setCodMovi(int codMovi) {
		this.codMovi = codMovi;
	}

	@Column(name = "cod_queja")
	public Integer getCodQueja() {
		return this.codQueja;
	}

	public void setCodQueja(Integer codQueja) {
		this.codQueja = codQueja;
	}

	@Column(name = "des_movi")
	public String getDesMovi() {
		return this.desMovi;
	}

	public void setDesMovi(String desMovi) {
		this.desMovi = desMovi;
	}

	@Column(name = "fla_estado")
	public Integer getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Integer flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "cod_usuario_aten", length = 50)
	public String getCodUsuarioAten() {
		return this.codUsuarioAten;
	}

	public void setCodUsuarioAten(String codUsuarioAten) {
		this.codUsuarioAten = codUsuarioAten;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_movi", length = 26)
	public Date getFecMovi() {
		return this.fecMovi;
	}

	public void setFecMovi(Date fecMovi) {
		this.fecMovi = fecMovi;
	}

}
