package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TQuejasMaster generated by hbm2java
 */
@Entity
@Table(name = "T_QUEJAS_MASTER", schema = "WEB")
public class TQuejasMaster implements java.io.Serializable {

	private int codQueja;
	private TabEspecialidad tabEspecialidad;
	private TabProcesoJudicial tabProcesoJudicial;
	private TQuejasEstado TQuejasEstado;
	private String numExpe;
	private String matExpe;
	private String ubiExpe;
	private String partDemandantes;
	private String partDemandado;
	private String desQueja;
	private Date fecPresent;
	private Integer codQuejoso;
	private String apeQuejoso;
	private String nomQuejoso;
	private String mailQuejoso;
	private String dniQuejoso;
	private String telQuejoso;
	private String dirQuejoso;
	private int anioQueja;
	private String codSeguridad;
	private String dirIp;
	private String dirIpProxy;
	private String desQuejado;
	private Integer flaVista;
	private Integer nudoc;

	public TQuejasMaster() {
	}

	public TQuejasMaster(int codQueja, TQuejasEstado TQuejasEstado,
			String numExpe, String matExpe, String ubiExpe, String desQueja,
			Date fecPresent, String apeQuejoso, String nomQuejoso,
			String mailQuejoso, String dniQuejoso, int anioQueja) {
		this.codQueja = codQueja;
		this.TQuejasEstado = TQuejasEstado;
		this.numExpe = numExpe;
		this.matExpe = matExpe;
		this.ubiExpe = ubiExpe;
		this.desQueja = desQueja;
		this.fecPresent = fecPresent;
		this.apeQuejoso = apeQuejoso;
		this.nomQuejoso = nomQuejoso;
		this.mailQuejoso = mailQuejoso;
		this.dniQuejoso = dniQuejoso;
		this.anioQueja = anioQueja;
	}

	public TQuejasMaster(int codQueja, TabEspecialidad tabEspecialidad,
			TabProcesoJudicial tabProcesoJudicial, TQuejasEstado TQuejasEstado,
			String numExpe, String matExpe, String ubiExpe,
			String partDemandantes, String partDemandado, String desQueja,
			Date fecPresent, Integer codQuejoso, String apeQuejoso,
			String nomQuejoso, String mailQuejoso, String dniQuejoso,
			String telQuejoso, String dirQuejoso, int anioQueja,
			String codSeguridad, String dirIp, String dirIpProxy,
			String desQuejado, Integer flaVista, Integer nudoc) {
		this.codQueja = codQueja;
		this.tabEspecialidad = tabEspecialidad;
		this.tabProcesoJudicial = tabProcesoJudicial;
		this.TQuejasEstado = TQuejasEstado;
		this.numExpe = numExpe;
		this.matExpe = matExpe;
		this.ubiExpe = ubiExpe;
		this.partDemandantes = partDemandantes;
		this.partDemandado = partDemandado;
		this.desQueja = desQueja;
		this.fecPresent = fecPresent;
		this.codQuejoso = codQuejoso;
		this.apeQuejoso = apeQuejoso;
		this.nomQuejoso = nomQuejoso;
		this.mailQuejoso = mailQuejoso;
		this.dniQuejoso = dniQuejoso;
		this.telQuejoso = telQuejoso;
		this.dirQuejoso = dirQuejoso;
		this.anioQueja = anioQueja;
		this.codSeguridad = codSeguridad;
		this.dirIp = dirIp;
		this.dirIpProxy = dirIpProxy;
		this.desQuejado = desQuejado;
		this.flaVista = flaVista;
		this.nudoc = nudoc;
	}

	@Id
	@Column(name = "cod_queja", nullable = false)
	public int getCodQueja() {
		return this.codQueja;
	}

	public void setCodQueja(int codQueja) {
		this.codQueja = codQueja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_especialidad")
	public TabEspecialidad getTabEspecialidad() {
		return this.tabEspecialidad;
	}

	public void setTabEspecialidad(TabEspecialidad tabEspecialidad) {
		this.tabEspecialidad = tabEspecialidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proceso_judicial")
	public TabProcesoJudicial getTabProcesoJudicial() {
		return this.tabProcesoJudicial;
	}

	public void setTabProcesoJudicial(TabProcesoJudicial tabProcesoJudicial) {
		this.tabProcesoJudicial = tabProcesoJudicial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fla_estado", nullable = false)
	public TQuejasEstado getTQuejasEstado() {
		return this.TQuejasEstado;
	}

	public void setTQuejasEstado(TQuejasEstado TQuejasEstado) {
		this.TQuejasEstado = TQuejasEstado;
	}

	@Column(name = "num_expe", nullable = false, length = 200)
	public String getNumExpe() {
		return this.numExpe;
	}

	public void setNumExpe(String numExpe) {
		this.numExpe = numExpe;
	}

	@Column(name = "mat_expe", nullable = false, length = 200)
	public String getMatExpe() {
		return this.matExpe;
	}

	public void setMatExpe(String matExpe) {
		this.matExpe = matExpe;
	}

	@Column(name = "ubi_expe", nullable = false, length = 200)
	public String getUbiExpe() {
		return this.ubiExpe;
	}

	public void setUbiExpe(String ubiExpe) {
		this.ubiExpe = ubiExpe;
	}

	@Column(name = "part_demandantes")
	public String getPartDemandantes() {
		return this.partDemandantes;
	}

	public void setPartDemandantes(String partDemandantes) {
		this.partDemandantes = partDemandantes;
	}

	@Column(name = "part_demandado")
	public String getPartDemandado() {
		return this.partDemandado;
	}

	public void setPartDemandado(String partDemandado) {
		this.partDemandado = partDemandado;
	}

	@Column(name = "des_queja", nullable = false)
	public String getDesQueja() {
		return this.desQueja;
	}

	public void setDesQueja(String desQueja) {
		this.desQueja = desQueja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_present", nullable = false, length = 26)
	public Date getFecPresent() {
		return this.fecPresent;
	}

	public void setFecPresent(Date fecPresent) {
		this.fecPresent = fecPresent;
	}

	@Column(name = "cod_quejoso")
	public Integer getCodQuejoso() {
		return this.codQuejoso;
	}

	public void setCodQuejoso(Integer codQuejoso) {
		this.codQuejoso = codQuejoso;
	}

	@Column(name = "ape_quejoso", nullable = false, length = 200)
	public String getApeQuejoso() {
		return this.apeQuejoso;
	}

	public void setApeQuejoso(String apeQuejoso) {
		this.apeQuejoso = apeQuejoso;
	}

	@Column(name = "nom_quejoso", nullable = false, length = 200)
	public String getNomQuejoso() {
		return this.nomQuejoso;
	}

	public void setNomQuejoso(String nomQuejoso) {
		this.nomQuejoso = nomQuejoso;
	}

	@Column(name = "mail_quejoso", nullable = false, length = 100)
	public String getMailQuejoso() {
		return this.mailQuejoso;
	}

	public void setMailQuejoso(String mailQuejoso) {
		this.mailQuejoso = mailQuejoso;
	}

	@Column(name = "dni_quejoso", nullable = false, length = 10)
	public String getDniQuejoso() {
		return this.dniQuejoso;
	}

	public void setDniQuejoso(String dniQuejoso) {
		this.dniQuejoso = dniQuejoso;
	}

	@Column(name = "tel_quejoso", length = 200)
	public String getTelQuejoso() {
		return this.telQuejoso;
	}

	public void setTelQuejoso(String telQuejoso) {
		this.telQuejoso = telQuejoso;
	}

	@Column(name = "dir_quejoso", length = 250)
	public String getDirQuejoso() {
		return this.dirQuejoso;
	}

	public void setDirQuejoso(String dirQuejoso) {
		this.dirQuejoso = dirQuejoso;
	}

	@Column(name = "anio_queja", nullable = false)
	public int getAnioQueja() {
		return this.anioQueja;
	}

	public void setAnioQueja(int anioQueja) {
		this.anioQueja = anioQueja;
	}

	@Column(name = "cod_seguridad", length = 18)
	public String getCodSeguridad() {
		return this.codSeguridad;
	}

	public void setCodSeguridad(String codSeguridad) {
		this.codSeguridad = codSeguridad;
	}

	@Column(name = "dir_ip", length = 50)
	public String getDirIp() {
		return this.dirIp;
	}

	public void setDirIp(String dirIp) {
		this.dirIp = dirIp;
	}

	@Column(name = "dir_ip_proxy", length = 50)
	public String getDirIpProxy() {
		return this.dirIpProxy;
	}

	public void setDirIpProxy(String dirIpProxy) {
		this.dirIpProxy = dirIpProxy;
	}

	@Column(name = "des_quejado", length = 250)
	public String getDesQuejado() {
		return this.desQuejado;
	}

	public void setDesQuejado(String desQuejado) {
		this.desQuejado = desQuejado;
	}

	@Column(name = "fla_vista")
	public Integer getFlaVista() {
		return this.flaVista;
	}

	public void setFlaVista(Integer flaVista) {
		this.flaVista = flaVista;
	}

	@Column(name = "NUDOC")
	public Integer getNudoc() {
		return this.nudoc;
	}

	public void setNudoc(Integer nudoc) {
		this.nudoc = nudoc;
	}

}
