package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TQuejosos generated by hbm2java
 */
@Entity
@Table(name = "T_QUEJOSOS", schema = "WEB")
public class TQuejosos implements java.io.Serializable {

	private int codQuejoso;
	private String apeQuejoso;
	private String nomQuejoso;
	private String mailQuejoso;
	private String dniQuejoso;
	private String telQuejoso;
	private String dirQuejoso;

	public TQuejosos() {
	}

	public TQuejosos(int codQuejoso, String apeQuejoso, String nomQuejoso,
			String mailQuejoso, String dniQuejoso) {
		this.codQuejoso = codQuejoso;
		this.apeQuejoso = apeQuejoso;
		this.nomQuejoso = nomQuejoso;
		this.mailQuejoso = mailQuejoso;
		this.dniQuejoso = dniQuejoso;
	}

	public TQuejosos(int codQuejoso, String apeQuejoso, String nomQuejoso,
			String mailQuejoso, String dniQuejoso, String telQuejoso,
			String dirQuejoso) {
		this.codQuejoso = codQuejoso;
		this.apeQuejoso = apeQuejoso;
		this.nomQuejoso = nomQuejoso;
		this.mailQuejoso = mailQuejoso;
		this.dniQuejoso = dniQuejoso;
		this.telQuejoso = telQuejoso;
		this.dirQuejoso = dirQuejoso;
	}

	@Id
	@Column(name = "cod_quejoso", nullable = false)
	public int getCodQuejoso() {
		return this.codQuejoso;
	}

	public void setCodQuejoso(int codQuejoso) {
		this.codQuejoso = codQuejoso;
	}

	@Column(name = "ape_quejoso", nullable = false, length = 200)
	public String getApeQuejoso() {
		return this.apeQuejoso;
	}

	public void setApeQuejoso(String apeQuejoso) {
		this.apeQuejoso = apeQuejoso;
	}

	@Column(name = "nom_quejoso", nullable = false, length = 200)
	public String getNomQuejoso() {
		return this.nomQuejoso;
	}

	public void setNomQuejoso(String nomQuejoso) {
		this.nomQuejoso = nomQuejoso;
	}

	@Column(name = "mail_quejoso", nullable = false, length = 100)
	public String getMailQuejoso() {
		return this.mailQuejoso;
	}

	public void setMailQuejoso(String mailQuejoso) {
		this.mailQuejoso = mailQuejoso;
	}

	@Column(name = "dni_quejoso", nullable = false, length = 8)
	public String getDniQuejoso() {
		return this.dniQuejoso;
	}

	public void setDniQuejoso(String dniQuejoso) {
		this.dniQuejoso = dniQuejoso;
	}

	@Column(name = "tel_quejoso", length = 200)
	public String getTelQuejoso() {
		return this.telQuejoso;
	}

	public void setTelQuejoso(String telQuejoso) {
		this.telQuejoso = telQuejoso;
	}

	@Column(name = "dir_quejoso", length = 250)
	public String getDirQuejoso() {
		return this.dirQuejoso;
	}

	public void setDirQuejoso(String dirQuejoso) {
		this.dirQuejoso = dirQuejoso;
	}

}
