package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTalleres generated by hbm2java
 */
@Entity
@Table(name = "T_TALLERES", schema = "WEB")
public class TTalleres implements java.io.Serializable {

	private TTalleresId id;

	public TTalleres() {
	}

	public TTalleres(TTalleresId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codTaller", column = @Column(name = "COD_TALLER", nullable = false)),
			@AttributeOverride(name = "fechaTaller", column = @Column(name = "FECHA_TALLER", length = 10)),
			@AttributeOverride(name = "codDistritoJudicial", column = @Column(name = "COD_DISTRITO_JUDICIAL")),
			@AttributeOverride(name = "urlImagen", column = @Column(name = "URL_IMAGEN", length = 200)),
			@AttributeOverride(name = "TTipo", column = @Column(name = "T_TIPO", length = 1)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 250)) })
	public TTalleresId getId() {
		return this.id;
	}

	public void setId(TTalleresId id) {
		this.id = id;
	}

}
