package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTalleresId generated by hbm2java
 */
@Embeddable
public class TTalleresId implements java.io.Serializable {

	private int codTaller;
	private Date fechaTaller;
	private Integer codDistritoJudicial;
	private String urlImagen;
	private Character TTipo;
	private String descripcion;

	public TTalleresId() {
	}

	public TTalleresId(int codTaller) {
		this.codTaller = codTaller;
	}

	public TTalleresId(int codTaller, Date fechaTaller,
			Integer codDistritoJudicial, String urlImagen, Character TTipo,
			String descripcion) {
		this.codTaller = codTaller;
		this.fechaTaller = fechaTaller;
		this.codDistritoJudicial = codDistritoJudicial;
		this.urlImagen = urlImagen;
		this.TTipo = TTipo;
		this.descripcion = descripcion;
	}

	@Column(name = "COD_TALLER", nullable = false)
	public int getCodTaller() {
		return this.codTaller;
	}

	public void setCodTaller(int codTaller) {
		this.codTaller = codTaller;
	}

	@Column(name = "FECHA_TALLER", length = 10)
	public Date getFechaTaller() {
		return this.fechaTaller;
	}

	public void setFechaTaller(Date fechaTaller) {
		this.fechaTaller = fechaTaller;
	}

	@Column(name = "COD_DISTRITO_JUDICIAL")
	public Integer getCodDistritoJudicial() {
		return this.codDistritoJudicial;
	}

	public void setCodDistritoJudicial(Integer codDistritoJudicial) {
		this.codDistritoJudicial = codDistritoJudicial;
	}

	@Column(name = "URL_IMAGEN", length = 200)
	public String getUrlImagen() {
		return this.urlImagen;
	}

	public void setUrlImagen(String urlImagen) {
		this.urlImagen = urlImagen;
	}

	@Column(name = "T_TIPO", length = 1)
	public Character getTTipo() {
		return this.TTipo;
	}

	public void setTTipo(Character TTipo) {
		this.TTipo = TTipo;
	}

	@Column(name = "DESCRIPCION", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTalleresId))
			return false;
		TTalleresId castOther = (TTalleresId) other;

		return (this.getCodTaller() == castOther.getCodTaller())
				&& ((this.getFechaTaller() == castOther.getFechaTaller()) || (this
						.getFechaTaller() != null
						&& castOther.getFechaTaller() != null && this
						.getFechaTaller().equals(castOther.getFechaTaller())))
				&& ((this.getCodDistritoJudicial() == castOther
						.getCodDistritoJudicial()) || (this
						.getCodDistritoJudicial() != null
						&& castOther.getCodDistritoJudicial() != null && this
						.getCodDistritoJudicial().equals(
								castOther.getCodDistritoJudicial())))
				&& ((this.getUrlImagen() == castOther.getUrlImagen()) || (this
						.getUrlImagen() != null
						&& castOther.getUrlImagen() != null && this
						.getUrlImagen().equals(castOther.getUrlImagen())))
				&& ((this.getTTipo() == castOther.getTTipo()) || (this
						.getTTipo() != null && castOther.getTTipo() != null && this
						.getTTipo().equals(castOther.getTTipo())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTaller();
		result = 37
				* result
				+ (getFechaTaller() == null ? 0 : this.getFechaTaller()
						.hashCode());
		result = 37
				* result
				+ (getCodDistritoJudicial() == null ? 0 : this
						.getCodDistritoJudicial().hashCode());
		result = 37 * result
				+ (getUrlImagen() == null ? 0 : this.getUrlImagen().hashCode());
		result = 37 * result
				+ (getTTipo() == null ? 0 : this.getTTipo().hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		return result;
	}

}
