package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTipoArchivos generated by hbm2java
 */
@Entity
@Table(name = "T_TIPO_ARCHIVOS", schema = "WEB")
public class TTipoArchivos implements java.io.Serializable {

	private int codTipo;
	private String descripcion;

	public TTipoArchivos() {
	}

	public TTipoArchivos(int codTipo) {
		this.codTipo = codTipo;
	}

	public TTipoArchivos(int codTipo, String descripcion) {
		this.codTipo = codTipo;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "COD_TIPO", nullable = false)
	public int getCodTipo() {
		return this.codTipo;
	}

	public void setCodTipo(int codTipo) {
		this.codTipo = codTipo;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
