package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTipArchivosId generated by hbm2java
 */
@Embeddable
public class TTipArchivosId implements java.io.Serializable {

	private int cod;
	private String descripcion;
	private String extencion;
	private String ruta;

	public TTipArchivosId() {
	}

	public TTipArchivosId(int cod) {
		this.cod = cod;
	}

	public TTipArchivosId(int cod, String descripcion, String extencion,
			String ruta) {
		this.cod = cod;
		this.descripcion = descripcion;
		this.extencion = extencion;
		this.ruta = ruta;
	}

	@Column(name = "COD", nullable = false)
	public int getCod() {
		return this.cod;
	}

	public void setCod(int cod) {
		this.cod = cod;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "EXTENCION", length = 500)
	public String getExtencion() {
		return this.extencion;
	}

	public void setExtencion(String extencion) {
		this.extencion = extencion;
	}

	@Column(name = "RUTA", length = 500)
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTipArchivosId))
			return false;
		TTipArchivosId castOther = (TTipArchivosId) other;

		return (this.getCod() == castOther.getCod())
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getExtencion() == castOther.getExtencion()) || (this
						.getExtencion() != null
						&& castOther.getExtencion() != null && this
						.getExtencion().equals(castOther.getExtencion())))
				&& ((this.getRuta() == castOther.getRuta()) || (this.getRuta() != null
						&& castOther.getRuta() != null && this.getRuta()
						.equals(castOther.getRuta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCod();
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		result = 37 * result
				+ (getExtencion() == null ? 0 : this.getExtencion().hashCode());
		result = 37 * result
				+ (getRuta() == null ? 0 : this.getRuta().hashCode());
		return result;
	}

}
