package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTipArchivos generated by hbm2java
 */
@Entity
@Table(name = "T_TIP_ARCHIVOS", schema = "WEB")
public class TTipArchivos implements java.io.Serializable {

	private TTipArchivosId id;

	public TTipArchivos() {
	}

	public TTipArchivos(TTipArchivosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cod", column = @Column(name = "COD", nullable = false)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 500)),
			@AttributeOverride(name = "extencion", column = @Column(name = "EXTENCION", length = 500)),
			@AttributeOverride(name = "ruta", column = @Column(name = "RUTA", length = 500)) })
	public TTipArchivosId getId() {
		return this.id;
	}

	public void setId(TTipArchivosId id) {
		this.id = id;
	}

}
