package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TUserInformaMaster generated by hbm2java
 */
@Entity
@Table(name = "T_USER_INFORMA_MASTER", schema = "WEB")
public class TUserInformaMaster implements java.io.Serializable {

	private TUserInformaMasterId id;

	public TUserInformaMaster() {
	}

	public TUserInformaMaster(TUserInformaMasterId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTabla", column = @Column(name = "ID_TABLA")),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 200)),
			@AttributeOverride(name = "correo", column = @Column(name = "CORREO", length = 150)),
			@AttributeOverride(name = "fecha", column = @Column(name = "FECHA", length = 26)),
			@AttributeOverride(name = "contenido", column = @Column(name = "CONTENIDO")),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO")),
			@AttributeOverride(name = "calificacion", column = @Column(name = "CALIFICACION")),
			@AttributeOverride(name = "flaRegistro", column = @Column(name = "FLA_REGISTRO")) })
	public TUserInformaMasterId getId() {
		return this.id;
	}

	public void setId(TUserInformaMasterId id) {
		this.id = id;
	}

}
