package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TUserInformaMasterId generated by hbm2java
 */
@Embeddable
public class TUserInformaMasterId implements java.io.Serializable {

	private Integer idTabla;
	private String nombre;
	private String correo;
	private Date fecha;
	private String contenido;
	private Integer estado;
	private Integer calificacion;
	private Integer flaRegistro;

	public TUserInformaMasterId() {
	}

	public TUserInformaMasterId(Integer idTabla, String nombre, String correo,
			Date fecha, String contenido, Integer estado, Integer calificacion,
			Integer flaRegistro) {
		this.idTabla = idTabla;
		this.nombre = nombre;
		this.correo = correo;
		this.fecha = fecha;
		this.contenido = contenido;
		this.estado = estado;
		this.calificacion = calificacion;
		this.flaRegistro = flaRegistro;
	}

	@Column(name = "ID_TABLA")
	public Integer getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(Integer idTabla) {
		this.idTabla = idTabla;
	}

	@Column(name = "NOMBRE", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CORREO", length = 150)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "FECHA", length = 26)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "CONTENIDO")
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Column(name = "ESTADO")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "CALIFICACION")
	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "FLA_REGISTRO")
	public Integer getFlaRegistro() {
		return this.flaRegistro;
	}

	public void setFlaRegistro(Integer flaRegistro) {
		this.flaRegistro = flaRegistro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TUserInformaMasterId))
			return false;
		TUserInformaMasterId castOther = (TUserInformaMasterId) other;

		return ((this.getIdTabla() == castOther.getIdTabla()) || (this
				.getIdTabla() != null && castOther.getIdTabla() != null && this
				.getIdTabla().equals(castOther.getIdTabla())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getContenido() == castOther.getContenido()) || (this
						.getContenido() != null
						&& castOther.getContenido() != null && this
						.getContenido().equals(castOther.getContenido())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getCalificacion() == castOther.getCalificacion()) || (this
						.getCalificacion() != null
						&& castOther.getCalificacion() != null && this
						.getCalificacion().equals(castOther.getCalificacion())))
				&& ((this.getFlaRegistro() == castOther.getFlaRegistro()) || (this
						.getFlaRegistro() != null
						&& castOther.getFlaRegistro() != null && this
						.getFlaRegistro().equals(castOther.getFlaRegistro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdTabla() == null ? 0 : this.getIdTabla().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getContenido() == null ? 0 : this.getContenido().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37
				* result
				+ (getCalificacion() == null ? 0 : this.getCalificacion()
						.hashCode());
		result = 37
				* result
				+ (getFlaRegistro() == null ? 0 : this.getFlaRegistro()
						.hashCode());
		return result;
	}

}
