package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TVideosprensa generated by hbm2java
 */
@Entity
@Table(name = "T_VIDEOSPRENSA", schema = "WEB")
public class TVideosprensa implements java.io.Serializable {

	private int cod;
	private String titulo;
	private String desc;
	private Date fecha;
	private String nomvideo;
	private Date fechacreacion;
	private Integer flag;
	private String tipo;

	public TVideosprensa() {
	}

	public TVideosprensa(int cod) {
		this.cod = cod;
	}

	public TVideosprensa(int cod, String titulo, String desc, Date fecha,
			String nomvideo, Date fechacreacion, Integer flag, String tipo) {
		this.cod = cod;
		this.titulo = titulo;
		this.desc = desc;
		this.fecha = fecha;
		this.nomvideo = nomvideo;
		this.fechacreacion = fechacreacion;
		this.flag = flag;
		this.tipo = tipo;
	}

	@Id
	@Column(name = "cod", nullable = false)
	public int getCod() {
		return this.cod;
	}

	public void setCod(int cod) {
		this.cod = cod;
	}

	@Column(name = "titulo", length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "desc", length = 250)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "nomvideo", length = 200)
	public String getNomvideo() {
		return this.nomvideo;
	}

	public void setNomvideo(String nomvideo) {
		this.nomvideo = nomvideo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreacion", length = 26)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "flag")
	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	@Column(name = "tipo", length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
