package pe.gob.ocma.entities.web;

// Generated 27/11/2013 01:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebSugerencias generated by hbm2java
 */
@Entity
@Table(name = "WEB_SUGERENCIAS", schema = "WEB")
public class WebSugerencias implements java.io.Serializable {

	private int codSugerencia;
	private String nombre;
	private String dni;
	private String mail;
	private String asunto;
	private String comentarios;
	private String direccionIp;
	private String proxyIp;
	private Date fecha;
	private Integer flaVista;
	private Integer flaTipo;

	public WebSugerencias() {
	}

	public WebSugerencias(int codSugerencia) {
		this.codSugerencia = codSugerencia;
	}

	public WebSugerencias(int codSugerencia, String nombre, String dni,
			String mail, String asunto, String comentarios, String direccionIp,
			String proxyIp, Date fecha, Integer flaVista, Integer flaTipo) {
		this.codSugerencia = codSugerencia;
		this.nombre = nombre;
		this.dni = dni;
		this.mail = mail;
		this.asunto = asunto;
		this.comentarios = comentarios;
		this.direccionIp = direccionIp;
		this.proxyIp = proxyIp;
		this.fecha = fecha;
		this.flaVista = flaVista;
		this.flaTipo = flaTipo;
	}

	@Id
	@Column(name = "cod_sugerencia", nullable = false)
	public int getCodSugerencia() {
		return this.codSugerencia;
	}

	public void setCodSugerencia(int codSugerencia) {
		this.codSugerencia = codSugerencia;
	}

	@Column(name = "nombre", length = 250)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "dni", length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "mail", length = 250)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "asunto", length = 100)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	@Column(name = "comentarios", length = 800)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "direccion_ip", length = 12)
	public String getDireccionIp() {
		return this.direccionIp;
	}

	public void setDireccionIp(String direccionIp) {
		this.direccionIp = direccionIp;
	}

	@Column(name = "proxy_ip", length = 12)
	public String getProxyIp() {
		return this.proxyIp;
	}

	public void setProxyIp(String proxyIp) {
		this.proxyIp = proxyIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 26)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "fla_vista")
	public Integer getFlaVista() {
		return this.flaVista;
	}

	public void setFlaVista(Integer flaVista) {
		this.flaVista = flaVista;
	}

	@Column(name = "fla_tipo")
	public Integer getFlaTipo() {
		return this.flaTipo;
	}

	public void setFlaTipo(Integer flaTipo) {
		this.flaTipo = flaTipo;
	}

}
