package pe.gob.ocma.entities.generico;

// Generated 02/09/2013 10:25:33 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GetcorreldocId generated by hbm2java
 */
@Embeddable
public class GetcorreldocId implements java.io.Serializable {

	private short codTipDoc;
	private int anio;
	private int numDoc;

	public GetcorreldocId() {
	}

	public GetcorreldocId(short codTipDoc, int anio, int numDoc) {
		this.codTipDoc = codTipDoc;
		this.anio = anio;
		this.numDoc = numDoc;
	}

	@Column(name = "codTipDoc", nullable = false)
	public short getCodTipDoc() {
		return this.codTipDoc;
	}

	public void setCodTipDoc(short codTipDoc) {
		this.codTipDoc = codTipDoc;
	}

	@Column(name = "anio", nullable = false)
	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	@Column(name = "numDoc", nullable = false)
	public int getNumDoc() {
		return this.numDoc;
	}

	public void setNumDoc(int numDoc) {
		this.numDoc = numDoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GetcorreldocId))
			return false;
		GetcorreldocId castOther = (GetcorreldocId) other;

		return (this.getCodTipDoc() == castOther.getCodTipDoc())
				&& (this.getAnio() == castOther.getAnio())
				&& (this.getNumDoc() == castOther.getNumDoc());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTipDoc();
		result = 37 * result + this.getAnio();
		result = 37 * result + this.getNumDoc();
		return result;
	}

}
