package pe.gob.ocma.entities.generico;

// Generated 02/09/2013 10:25:33 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Getcorrelmae generated by hbm2java
 */
@Entity
@Table(name = "GETCORRELMAE", schema = "GENERICO", uniqueConstraints = @UniqueConstraint(columnNames = "nomTabla"))
public class Getcorrelmae implements java.io.Serializable {

	private short codCorrel;
	private String nomTabla;
	private long correlativo;

	public Getcorrelmae() {
	}

	public Getcorrelmae(short codCorrel, String nomTabla, long correlativo) {
		this.codCorrel = codCorrel;
		this.nomTabla = nomTabla;
		this.correlativo = correlativo;
	}

	@Id
	@Column(name = "codCorrel", nullable = false)
	public short getCodCorrel() {
		return this.codCorrel;
	}

	public void setCodCorrel(short codCorrel) {
		this.codCorrel = codCorrel;
	}

	@Column(name = "nomTabla", unique = true, nullable = false, length = 20)
	public String getNomTabla() {
		return this.nomTabla;
	}

	public void setNomTabla(String nomTabla) {
		this.nomTabla = nomTabla;
	}

	@Column(name = "correlativo", nullable = false)
	public long getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(long correlativo) {
		this.correlativo = correlativo;
	}

}
