package pe.gob.ocma.entities.generico;

// Generated 02/09/2013 10:25:33 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gettabmae generated by hbm2java
 */
@Entity
@Table(name = "GETTABMAE", schema = "GENERICO")
public class Gettabmae implements java.io.Serializable {

	private short codTabMae;
	private String nomTabla;
	private String desTabla;
	private String codColumna;
	private String desCorta;
	private String desLarga;
	private String desOtra;
	private short orden;
	private boolean porDefecto;
	private boolean habilitado;

	public Gettabmae() {
	}

	public Gettabmae(short codTabMae, String nomTabla, String desTabla,
			String codColumna, String desCorta, String desLarga, short orden,
			boolean porDefecto, boolean habilitado) {
		this.codTabMae = codTabMae;
		this.nomTabla = nomTabla;
		this.desTabla = desTabla;
		this.codColumna = codColumna;
		this.desCorta = desCorta;
		this.desLarga = desLarga;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.habilitado = habilitado;
	}

	public Gettabmae(short codTabMae, String nomTabla, String desTabla,
			String codColumna, String desCorta, String desLarga,
			String desOtra, short orden, boolean porDefecto, boolean habilitado) {
		this.codTabMae = codTabMae;
		this.nomTabla = nomTabla;
		this.desTabla = desTabla;
		this.codColumna = codColumna;
		this.desCorta = desCorta;
		this.desLarga = desLarga;
		this.desOtra = desOtra;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.habilitado = habilitado;
	}

	@Id
	@Column(name = "codTabMae", nullable = false)
	public short getCodTabMae() {
		return this.codTabMae;
	}

	public void setCodTabMae(short codTabMae) {
		this.codTabMae = codTabMae;
	}

	@Column(name = "nomTabla", nullable = false, length = 50)
	public String getNomTabla() {
		return this.nomTabla;
	}

	public void setNomTabla(String nomTabla) {
		this.nomTabla = nomTabla;
	}

	@Column(name = "desTabla", nullable = false, length = 100)
	public String getDesTabla() {
		return this.desTabla;
	}

	public void setDesTabla(String desTabla) {
		this.desTabla = desTabla;
	}

	@Column(name = "codColumna", nullable = false, length = 10)
	public String getCodColumna() {
		return this.codColumna;
	}

	public void setCodColumna(String codColumna) {
		this.codColumna = codColumna;
	}

	@Column(name = "desCorta", nullable = false, length = 50)
	public String getDesCorta() {
		return this.desCorta;
	}

	public void setDesCorta(String desCorta) {
		this.desCorta = desCorta;
	}

	@Column(name = "desLarga", nullable = false, length = 100)
	public String getDesLarga() {
		return this.desLarga;
	}

	public void setDesLarga(String desLarga) {
		this.desLarga = desLarga;
	}

	@Column(name = "desOtra")
	public String getDesOtra() {
		return this.desOtra;
	}

	public void setDesOtra(String desOtra) {
		this.desOtra = desOtra;
	}

	@Column(name = "orden", nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "porDefecto", nullable = false)
	public boolean isPorDefecto() {
		return this.porDefecto;
	}

	public void setPorDefecto(boolean porDefecto) {
		this.porDefecto = porDefecto;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
