package pe.gob.ocma.entities.generico;

// Generated 02/09/2013 10:25:33 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Gettipdoc generated by hbm2java
 */
@Entity
@Table(name = "GETTIPDOC", schema = "GENERICO", uniqueConstraints = {
		@UniqueConstraint(columnNames = "desAbrev"),
		@UniqueConstraint(columnNames = "descripcion") })
public class Gettipdoc implements java.io.Serializable {

	private short codTipDoc;
	private String descripcion;
	private String desAbrev;
	private boolean habilitado;

	public Gettipdoc() {
	}

	public Gettipdoc(short codTipDoc, String descripcion, String desAbrev,
			boolean habilitado) {
		this.codTipDoc = codTipDoc;
		this.descripcion = descripcion;
		this.desAbrev = desAbrev;
		this.habilitado = habilitado;
	}

	@Id
	@Column(name = "codTipDoc", nullable = false)
	public short getCodTipDoc() {
		return this.codTipDoc;
	}

	public void setCodTipDoc(short codTipDoc) {
		this.codTipDoc = codTipDoc;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "desAbrev", unique = true, nullable = false, length = 2)
	public String getDesAbrev() {
		return this.desAbrev;
	}

	public void setDesAbrev(String desAbrev) {
		this.desAbrev = desAbrev;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
