package pe.gob.ocma.entities.seguridad;

// Generated 02/09/2013 12:50:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Setaplica generated by hbm2java
 */
@Entity
@Table(name = "SETAPLICA", schema = "SEGURIDAD", uniqueConstraints = {
		@UniqueConstraint(columnNames = "orden"),
		@UniqueConstraint(columnNames = "descripcion") })
public class Setaplica implements java.io.Serializable {

	private short codAplica;
	private String descripcion;
	private short orden;
	private Set<Setgrupo> setgrupos = new HashSet<Setgrupo>(0);
	private Set<Setopcion> setopcions = new HashSet<Setopcion>(0);

	public Setaplica() {
	}

	public Setaplica(short codAplica, String descripcion, short orden) {
		this.codAplica = codAplica;
		this.descripcion = descripcion;
		this.orden = orden;
	}

	public Setaplica(short codAplica, String descripcion, short orden,
			Set<Setgrupo> setgrupos, Set<Setopcion> setopcions) {
		this.codAplica = codAplica;
		this.descripcion = descripcion;
		this.orden = orden;
		this.setgrupos = setgrupos;
		this.setopcions = setopcions;
	}

	@Id
	@Column(name = "codAplica", nullable = false)
	public short getCodAplica() {
		return this.codAplica;
	}

	public void setCodAplica(short codAplica) {
		this.codAplica = codAplica;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", unique = true, nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setaplica")
	public Set<Setgrupo> getSetgrupos() {
		return this.setgrupos;
	}

	public void setSetgrupos(Set<Setgrupo> setgrupos) {
		this.setgrupos = setgrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setaplica")
	public Set<Setopcion> getSetopcions() {
		return this.setopcions;
	}

	public void setSetopcions(Set<Setopcion> setopcions) {
		this.setopcions = setopcions;
	}

}
