package pe.gob.ocma.entities.seguridad;

// Generated 02/09/2013 12:50:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Setgrupo generated by hbm2java
 */
@Entity
@Table(name = "SETGRUPO", schema = "SEGURIDAD")
public class Setgrupo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codGrupo;
	private String codAutoriza;
	private Setusuario setusuario;
	private short codAplica;
	private Setaplica setaplica;
	private String desCorta;
	private String descripcion;
	private boolean habilitado;
	private Set<Setusugrupo> setusugrupos = new HashSet<Setusugrupo>(0);
	private Set<Setopcion> setopcions = new HashSet<Setopcion>(0);

	public Setgrupo() {
	}

	@Id
	@Column(name = "codGrupo", nullable = false)
	public int getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(int codGrupo) {
		this.codGrupo = codGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codAutoriza", nullable = false, insertable = false, updatable = false)
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codAplica", nullable = false, insertable = false, updatable = false)
	public Setaplica getSetaplica() {
		return this.setaplica;
	}

	public void setSetaplica(Setaplica setaplica) {
		this.setaplica = setaplica;
	}

	@Column(name = "codAplica", nullable = false)
	public short getCodAplica() {
		return codAplica;
	}

	public void setCodAplica(short codAplica) {
		this.codAplica = codAplica;
	}

	@Column(name = "desCorta", nullable = false, length = 100)
	public String getDesCorta() {
		return this.desCorta;
	}

	public void setDesCorta(String desCorta) {
		this.desCorta = desCorta;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "codAutoriza", nullable = false, length = 20)
	public String getCodAutoriza() {
		return codAutoriza;
	}

	public void setCodAutoriza(String codAutoriza) {
		this.codAutoriza = codAutoriza;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setgrupo")
	public Set<Setusugrupo> getSetusugrupos() {
		return this.setusugrupos;
	}

	public void setSetusugrupos(Set<Setusugrupo> setusugrupos) {
		this.setusugrupos = setusugrupos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "setgrupos")
	public Set<Setopcion> getSetopcions() {
		return this.setopcions;
	}

	public void setSetopcions(Set<Setopcion> setopcions) {
		this.setopcions = setopcions;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + codGrupo;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Setgrupo other = (Setgrupo) obj;
		if (codGrupo != other.codGrupo)
			return false;
		return true;
	}
}