package pe.gob.ocma.entities.seguridad;

// Generated 02/09/2013 12:50:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Setnivseguri generated by hbm2java
 */
@Entity
@Table(name = "SETNIVSEGURI", schema = "SEGURIDAD", uniqueConstraints = @UniqueConstraint(columnNames = "descripcion"))
public class Setnivseguri implements java.io.Serializable {

	private short codNivSeguri;
	private String descripcion;
	private Integer expClave;
	private short minCaracter;
	private short minMayus;
	private short minMinus;
	private short minDigitos;
	private short minNoAlfanum;
	private String ejemplo;
	private Set<Setusuario> setusuarios = new HashSet<Setusuario>(0);

	public Setnivseguri() {
	}

	public Setnivseguri(short codNivSeguri, String descripcion,
			short minCaracter, short minMayus, short minMinus,
			short minDigitos, short minNoAlfanum, String ejemplo) {
		this.codNivSeguri = codNivSeguri;
		this.descripcion = descripcion;
		this.minCaracter = minCaracter;
		this.minMayus = minMayus;
		this.minMinus = minMinus;
		this.minDigitos = minDigitos;
		this.minNoAlfanum = minNoAlfanum;
		this.ejemplo = ejemplo;
	}

	public Setnivseguri(short codNivSeguri, String descripcion,
			Integer expClave, short minCaracter, short minMayus,
			short minMinus, short minDigitos, short minNoAlfanum,
			String ejemplo, Set<Setusuario> setusuarios) {
		this.codNivSeguri = codNivSeguri;
		this.descripcion = descripcion;
		this.expClave = expClave;
		this.minCaracter = minCaracter;
		this.minMayus = minMayus;
		this.minMinus = minMinus;
		this.minDigitos = minDigitos;
		this.minNoAlfanum = minNoAlfanum;
		this.ejemplo = ejemplo;
		this.setusuarios = setusuarios;
	}

	@Id
	@Column(name = "codNivSeguri", nullable = false)
	public short getCodNivSeguri() {
		return this.codNivSeguri;
	}

	public void setCodNivSeguri(short codNivSeguri) {
		this.codNivSeguri = codNivSeguri;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "expClave")
	public Integer getExpClave() {
		return this.expClave;
	}

	public void setExpClave(Integer expClave) {
		this.expClave = expClave;
	}

	@Column(name = "minCaracter", nullable = false)
	public short getMinCaracter() {
		return this.minCaracter;
	}

	public void setMinCaracter(short minCaracter) {
		this.minCaracter = minCaracter;
	}

	@Column(name = "minMayus", nullable = false)
	public short getMinMayus() {
		return this.minMayus;
	}

	public void setMinMayus(short minMayus) {
		this.minMayus = minMayus;
	}

	@Column(name = "minMinus", nullable = false)
	public short getMinMinus() {
		return this.minMinus;
	}

	public void setMinMinus(short minMinus) {
		this.minMinus = minMinus;
	}

	@Column(name = "minDigitos", nullable = false)
	public short getMinDigitos() {
		return this.minDigitos;
	}

	public void setMinDigitos(short minDigitos) {
		this.minDigitos = minDigitos;
	}

	@Column(name = "minNoAlfanum", nullable = false)
	public short getMinNoAlfanum() {
		return this.minNoAlfanum;
	}

	public void setMinNoAlfanum(short minNoAlfanum) {
		this.minNoAlfanum = minNoAlfanum;
	}

	@Column(name = "ejemplo", nullable = false, length = 20)
	public String getEjemplo() {
		return this.ejemplo;
	}

	public void setEjemplo(String ejemplo) {
		this.ejemplo = ejemplo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setnivseguri")
	public Set<Setusuario> getSetusuarios() {
		return this.setusuarios;
	}

	public void setSetusuarios(Set<Setusuario> setusuarios) {
		this.setusuarios = setusuarios;
	}

}
