package pe.gob.ocma.entities.seguridad;

// Generated 02/09/2013 12:50:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Setopcion generated by hbm2java
 */
@Entity
@Table(name = "SETOPCION", schema = "SEGURIDAD")
public class Setopcion implements java.io.Serializable {

	private int codOpcion;
	private Setaplica setaplica;
	private int opcPadre;
	private String descripcion;
	private char tipo;
	private String url;
	private int orden;
	private Set<Setgrupo> setgrupos = new HashSet<Setgrupo>(0);

	public Setopcion() {
	}

	public Setopcion(int codOpcion, Setaplica setaplica, int opcPadre,
			String descripcion, char tipo, String url, int orden) {
		this.codOpcion = codOpcion;
		this.setaplica = setaplica;
		this.opcPadre = opcPadre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.url = url;
		this.orden = orden;
	}

	public Setopcion(int codOpcion, Setaplica setaplica, int opcPadre,
			String descripcion, char tipo, String url, int orden,
			Set<Setgrupo> setgrupos) {
		this.codOpcion = codOpcion;
		this.setaplica = setaplica;
		this.opcPadre = opcPadre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.url = url;
		this.orden = orden;
		this.setgrupos = setgrupos;
	}

	@Id
	@Column(name = "codOpcion", nullable = false)
	public int getCodOpcion() {
		return this.codOpcion;
	}

	public void setCodOpcion(int codOpcion) {
		this.codOpcion = codOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codAplica", nullable = false)
	public Setaplica getSetaplica() {
		return this.setaplica;
	}

	public void setSetaplica(Setaplica setaplica) {
		this.setaplica = setaplica;
	}

	@Column(name = "opcPadre", nullable = false)
	public int getOpcPadre() {
		return this.opcPadre;
	}

	public void setOpcPadre(int opcPadre) {
		this.opcPadre = opcPadre;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	public char getTipo() {
		return this.tipo;
	}

	public void setTipo(char tipo) {
		this.tipo = tipo;
	}

	@Column(name = "url", nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SETOPCGRUPO", schema = "SEGURIDAD", joinColumns = { @JoinColumn(name = "codOpcion", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codGrupo", nullable = false, updatable = false) })
	public Set<Setgrupo> getSetgrupos() {
		return this.setgrupos;
	}

	public void setSetgrupos(Set<Setgrupo> setgrupos) {
		this.setgrupos = setgrupos;
	}

}
