package pe.gob.ocma.entities.seguridad;

// Generated 02/09/2013 12:50:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Settema generated by hbm2java
 */
@Entity
@Table(name = "SETTEMA", schema = "SEGURIDAD", uniqueConstraints = @UniqueConstraint(columnNames = "descripcion"))
public class Settema implements java.io.Serializable {

	private String codTema;
	private String descripcion;
	private Set<Setusuario> setusuarios = new HashSet<Setusuario>(0);

	public Settema() {
	}

	public Settema(String codTema, String descripcion) {
		this.codTema = codTema;
		this.descripcion = descripcion;
	}

	public Settema(String codTema, String descripcion,
			Set<Setusuario> setusuarios) {
		this.codTema = codTema;
		this.descripcion = descripcion;
		this.setusuarios = setusuarios;
	}

	@Id
	@Column(name = "codTema", nullable = false, length = 32)
	public String getCodTema() {
		return this.codTema;
	}

	public void setCodTema(String codTema) {
		this.codTema = codTema;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "settema")
	public Set<Setusuario> getSetusuarios() {
		return this.setusuarios;
	}

	public void setSetusuarios(Set<Setusuario> setusuarios) {
		this.setusuarios = setusuarios;
	}

}
