package pe.gob.ocma.entities.seguridad;

// Generated 02/09/2013 12:50:05 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Setusugrupo generated by hbm2java
 */
@Entity
@Table(name = "SETUSUGRUPO", schema = "SEGURIDAD")
public class Setusugrupo implements java.io.Serializable {

	private SetusugrupoId id;
	private Setusuario setusuario;
	private Setgrupo setgrupo;
	private boolean habilitado;

	public Setusugrupo() {
	}

	public Setusugrupo(SetusugrupoId id, Setusuario setusuario,
			Setgrupo setgrupo, boolean habilitado) {
		this.id = id;
		this.setusuario = setusuario;
		this.setgrupo = setgrupo;
		this.habilitado = habilitado;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codGrupo", column = @Column(name = "codGrupo", nullable = false)),
			@AttributeOverride(name = "codUsuario", column = @Column(name = "codUsuario", nullable = false)) })
	public SetusugrupoId getId() {
		return this.id;
	}

	public void setId(SetusugrupoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codUsuario", nullable = false, insertable = false, updatable = false)
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codGrupo", nullable = false, insertable = false, updatable = false)
	public Setgrupo getSetgrupo() {
		return this.setgrupo;
	}

	public void setSetgrupo(Setgrupo setgrupo) {
		this.setgrupo = setgrupo;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
