package pe.gob.ocma.entities.seguridad;

// Generated 02/09/2013 12:50:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.gob.ocma.entities.oc_ocma.Socmovimiento;
import pe.gob.ocma.entities.persona.Petpernatu;
import pe.gob.ocma.entities.ubigeojud.Ujtdisjud;

/**
 * Setusuario generated by hbm2java
 */
@Entity
@Table(name = "SETUSUARIO", schema = "SEGURIDAD")
public class Setusuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String codUsuario;
	private Petpernatu petpernatu;
	private Ujtdisjud ujtdisjud;
	private Settema settema;
	private Setnivseguri setnivseguri;
	private String contrasenia;
	private String tipo;
	private Date ultLogin;
	private Date ultResClave;
	private boolean envCorreo;
	private boolean envFax;
	private long codPerNatu;
	private short codDisJud;
	private boolean habilitado;
	private Set<Setusugrupo> setusugrupos = new HashSet<Setusugrupo>(0);
	private Set<Socmovimiento> socusu = new HashSet<Socmovimiento>(0);
	
	public Setusuario() {
	}

	@Id
	@Column(name = "codUsuario", nullable = false)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codPerNatu", unique = true, nullable = false, insertable = false, updatable = false)
	public Petpernatu getPetpernatu() {
		return petpernatu;
	}

	public void setPetpernatu(Petpernatu petpernatu) {
		this.petpernatu = petpernatu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codDisJud", nullable = false, insertable = false, updatable = false)
	public Ujtdisjud getUjtdisjud() {
		return ujtdisjud;
	}

	public void setUjtdisjud(Ujtdisjud ujtdisjud) {
		this.ujtdisjud = ujtdisjud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codTema", nullable = false)
	public Settema getSettema() {
		return this.settema;
	}

	public void setSettema(Settema settema) {
		this.settema = settema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codNivSeguri", nullable = false)
	public Setnivseguri getSetnivseguri() {
		return this.setnivseguri;
	}

	public void setSetnivseguri(Setnivseguri setnivseguri) {
		this.setnivseguri = setnivseguri;
	}

	@Column(name = "contrasenia", nullable = false, length = 50)
	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	@Column(name = "tipo", nullable = false, length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultLogin", length = 26)
	public Date getUltLogin() {
		return this.ultLogin;
	}

	public void setUltLogin(Date ultLogin) {
		this.ultLogin = ultLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultResClave", length = 26)
	public Date getUltResClave() {
		return this.ultResClave;
	}

	public void setUltResClave(Date ultResClave) {
		this.ultResClave = ultResClave;
	}

	@Column(name = "envCorreo", nullable = false)
	public boolean isEnvCorreo() {
		return this.envCorreo;
	}

	public void setEnvCorreo(boolean envCorreo) {
		this.envCorreo = envCorreo;
	}

	@Column(name = "envFax", nullable = false)
	public boolean isEnvFax() {
		return this.envFax;
	}

	public void setEnvFax(boolean envFax) {
		this.envFax = envFax;
	}

	@Column(name = "codPerNatu", nullable = false)
	public long getCodPerNatu() {
		return this.codPerNatu;
	}

	public void setCodPerNatu(long codPerNatu) {
		this.codPerNatu = codPerNatu;
	}

	@Column(name = "codDisJud", nullable = false)
	public short getCodDisJud() {
		return this.codDisJud;
	}

	public void setCodDisJud(short codDisJud) {
		this.codDisJud = codDisJud;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario")
	public Set<Setusugrupo> getSetusugrupos() {
		return this.setusugrupos;
	}

	public void setSetusugrupos(Set<Setusugrupo> setusugrupos) {
		this.setusugrupos = setusugrupos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socmovimiento")
	public Set<Socmovimiento> getSocusu() {
		return socusu;
	}

	public void setSocusu(Set<Socmovimiento> socusu) {
		this.socusu = socusu;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codUsuario == null) ? 0 : codUsuario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Setusuario other = (Setusuario) obj;
		if (codUsuario == null) {
			if (other.codUsuario != null)
				return false;
		} else if (!codUsuario.equals(other.codUsuario))
			return false;
		return true;
	}
}
