package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DistriJud generated by hbm2java
 */
@Entity
@Table(name = "DISTRI_JUD", schema = "OC_OCMA")
public class DistriJud implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codDistri;
	private String desDistri;
	private Integer flaEstado;
	private String desDireccion;
	private Set<SeguEnca> seguEncas = new HashSet<SeguEnca>(0);
	private Set<ExpeMast> expeMastsForCodDistri = new HashSet<ExpeMast>(0);
	private Set<ExpeMast> expeMastsForCodDistritoOrigen = new HashSet<ExpeMast>(0);
	private Set<Socmast> socmastdistorigen = new HashSet<Socmast>(0);
	private Set<Socmast> socmastdist = new HashSet<Socmast>(0);

	public DistriJud() {
	}
	
	@Id
	@Column(name = "COD_DISTRI", nullable = false)
	public int getCodDistri() {
		return this.codDistri;
	}

	public void setCodDistri(int codDistri) {
		this.codDistri = codDistri;
	}

	@Column(name = "DES_DISTRI", length = 25)
	public String getDesDistri() {
		return this.desDistri;
	}

	public void setDesDistri(String desDistri) {
		this.desDistri = desDistri;
	}

	@Column(name = "FLA_ESTADO")
	public Integer getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Integer flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "DES_DIRECCION", length = 100)
	public String getDesDireccion() {
		return this.desDireccion;
	}

	public void setDesDireccion(String desDireccion) {
		this.desDireccion = desDireccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distriJud")
	public Set<SeguEnca> getSeguEncas() {
		return this.seguEncas;
	}

	public void setSeguEncas(Set<SeguEnca> seguEncas) {
		this.seguEncas = seguEncas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distriJudByCodDistri")
	public Set<ExpeMast> getExpeMastsForCodDistri() {
		return this.expeMastsForCodDistri;
	}

	public void setExpeMastsForCodDistri(Set<ExpeMast> expeMastsForCodDistri) {
		this.expeMastsForCodDistri = expeMastsForCodDistri;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distriJudByCodDistritoOrigen")
	public Set<ExpeMast> getExpeMastsForCodDistritoOrigen() {
		return this.expeMastsForCodDistritoOrigen;
	}

	public void setExpeMastsForCodDistritoOrigen(
			Set<ExpeMast> expeMastsForCodDistritoOrigen) {
		this.expeMastsForCodDistritoOrigen = expeMastsForCodDistritoOrigen;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socmastdistorigen")
	public Set<Socmast> getSocmastdistorigen() {
		return this.socmastdistorigen;
	}

	public void setSocmastdistorigen(Set<Socmast> socmastdistorigen) {
		this.socmastdistorigen = socmastdistorigen;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socmastdist")
	public Set<Socmast> getSocmastdist() {
		return this.socmastdist;
	}

	public void setSocmastdist(Set<Socmast> socmastdist) {
		this.socmastdist = socmastdist;
	}
	

}
