package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjAuditoria generated by hbm2java
 */
@Entity
@Table(name = "DJ_AUDITORIA", schema = "OC_OCMA")
public class DjAuditoria implements java.io.Serializable {

	private int codCorrelativo;
	private String codAccion;
	private Integer codDj;
	private Date fecModificacion;
	private String codUsuario;

	public DjAuditoria() {
	}

	public DjAuditoria(int codCorrelativo, String codAccion,
			Date fecModificacion, String codUsuario) {
		this.codCorrelativo = codCorrelativo;
		this.codAccion = codAccion;
		this.fecModificacion = fecModificacion;
		this.codUsuario = codUsuario;
	}

	public DjAuditoria(int codCorrelativo, String codAccion, Integer codDj,
			Date fecModificacion, String codUsuario) {
		this.codCorrelativo = codCorrelativo;
		this.codAccion = codAccion;
		this.codDj = codDj;
		this.fecModificacion = fecModificacion;
		this.codUsuario = codUsuario;
	}

	@Id
	@Column(name = "COD_CORRELATIVO", nullable = false)
	public int getCodCorrelativo() {
		return this.codCorrelativo;
	}

	public void setCodCorrelativo(int codCorrelativo) {
		this.codCorrelativo = codCorrelativo;
	}

	@Column(name = "COD_ACCION", nullable = false, length = 450)
	public String getCodAccion() {
		return this.codAccion;
	}

	public void setCodAccion(String codAccion) {
		this.codAccion = codAccion;
	}

	@Column(name = "COD_DJ")
	public Integer getCodDj() {
		return this.codDj;
	}

	public void setCodDj(Integer codDj) {
		this.codDj = codDj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICACION", nullable = false, length = 26)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "COD_USUARIO", nullable = false, length = 15)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

}
