package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DjBloqueAhorro generated by hbm2java
 */
@Entity
@Table(name = "DJ_BLOQUE_AHORRO", schema = "OC_OCMA")
public class DjBloqueAhorro implements java.io.Serializable {

	private DjBloqueAhorroId id;
	private DjInstrumento djInstrumento;
	private String desEntidad;
	private BigDecimal numValor;
	private Integer codTipoMoneda;

	public DjBloqueAhorro() {
	}

	public DjBloqueAhorro(DjBloqueAhorroId id, DjInstrumento djInstrumento,
			String desEntidad, BigDecimal numValor) {
		this.id = id;
		this.djInstrumento = djInstrumento;
		this.desEntidad = desEntidad;
		this.numValor = numValor;
	}

	public DjBloqueAhorro(DjBloqueAhorroId id, DjInstrumento djInstrumento,
			String desEntidad, BigDecimal numValor, Integer codTipoMoneda) {
		this.id = id;
		this.djInstrumento = djInstrumento;
		this.desEntidad = desEntidad;
		this.numValor = numValor;
		this.codTipoMoneda = codTipoMoneda;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codAhorro", column = @Column(name = "COD_AHORRO", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjBloqueAhorroId getId() {
		return this.id;
	}

	public void setId(DjBloqueAhorroId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_INSTRUMENTO", nullable = false)
	public DjInstrumento getDjInstrumento() {
		return this.djInstrumento;
	}

	public void setDjInstrumento(DjInstrumento djInstrumento) {
		this.djInstrumento = djInstrumento;
	}

	@Column(name = "DES_ENTIDAD", nullable = false, length = 1000)
	public String getDesEntidad() {
		return this.desEntidad;
	}

	public void setDesEntidad(String desEntidad) {
		this.desEntidad = desEntidad;
	}

	@Column(name = "NUM_VALOR", nullable = false, precision = 10)
	public BigDecimal getNumValor() {
		return this.numValor;
	}

	public void setNumValor(BigDecimal numValor) {
		this.numValor = numValor;
	}

	@Column(name = "COD_TIPO_MONEDA")
	public Integer getCodTipoMoneda() {
		return this.codTipoMoneda;
	}

	public void setCodTipoMoneda(Integer codTipoMoneda) {
		this.codTipoMoneda = codTipoMoneda;
	}

}
