package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjBloqueMuebleId generated by hbm2java
 */
@Embeddable
public class DjBloqueMuebleId implements java.io.Serializable {

	private int codMueble;
	private int codBloque;
	private int codDj;

	public DjBloqueMuebleId() {
	}

	public DjBloqueMuebleId(int codMueble, int codBloque, int codDj) {
		this.codMueble = codMueble;
		this.codBloque = codBloque;
		this.codDj = codDj;
	}

	@Column(name = "COD_MUEBLE", nullable = false)
	public int getCodMueble() {
		return this.codMueble;
	}

	public void setCodMueble(int codMueble) {
		this.codMueble = codMueble;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjBloqueMuebleId))
			return false;
		DjBloqueMuebleId castOther = (DjBloqueMuebleId) other;

		return (this.getCodMueble() == castOther.getCodMueble())
				&& (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodDj() == castOther.getCodDj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodMueble();
		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodDj();
		return result;
	}

}
