package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjBloqueAhorroId generated by hbm2java
 */
@Embeddable
public class DjBloqueAhorroId implements java.io.Serializable {

	private int codAhorro;
	private int codBloque;
	private int codDj;

	public DjBloqueAhorroId() {
	}

	public DjBloqueAhorroId(int codAhorro, int codBloque, int codDj) {
		this.codAhorro = codAhorro;
		this.codBloque = codBloque;
		this.codDj = codDj;
	}

	@Column(name = "COD_AHORRO", nullable = false)
	public int getCodAhorro() {
		return this.codAhorro;
	}

	public void setCodAhorro(int codAhorro) {
		this.codAhorro = codAhorro;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjBloqueAhorroId))
			return false;
		DjBloqueAhorroId castOther = (DjBloqueAhorroId) other;

		return (this.getCodAhorro() == castOther.getCodAhorro())
				&& (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodDj() == castOther.getCodDj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodAhorro();
		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodDj();
		return result;
	}

}
