package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DjBloqueViaje generated by hbm2java
 */
@Entity
@Table(name = "DJ_BLOQUE_VIAJE", schema = "OC_OCMA")
public class DjBloqueViaje implements java.io.Serializable {

	private DjBloqueViajeId id;
	private String destinoViaje;
	private String motivoViaje;
	private String fechaViaje;
	private String diasViaje;
	private BigDecimal numMonto;
	private Integer codTipoMoneda;

	public DjBloqueViaje() {
	}

	public DjBloqueViaje(DjBloqueViajeId id, String destinoViaje,
			BigDecimal numMonto) {
		this.id = id;
		this.destinoViaje = destinoViaje;
		this.numMonto = numMonto;
	}

	public DjBloqueViaje(DjBloqueViajeId id, String destinoViaje,
			String motivoViaje, String fechaViaje, String diasViaje,
			BigDecimal numMonto, Integer codTipoMoneda) {
		this.id = id;
		this.destinoViaje = destinoViaje;
		this.motivoViaje = motivoViaje;
		this.fechaViaje = fechaViaje;
		this.diasViaje = diasViaje;
		this.numMonto = numMonto;
		this.codTipoMoneda = codTipoMoneda;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codViaje", column = @Column(name = "COD_VIAJE", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjBloqueViajeId getId() {
		return this.id;
	}

	public void setId(DjBloqueViajeId id) {
		this.id = id;
	}

	@Column(name = "DESTINO_VIAJE", nullable = false, length = 250)
	public String getDestinoViaje() {
		return this.destinoViaje;
	}

	public void setDestinoViaje(String destinoViaje) {
		this.destinoViaje = destinoViaje;
	}

	@Column(name = "MOTIVO_VIAJE", length = 250)
	public String getMotivoViaje() {
		return this.motivoViaje;
	}

	public void setMotivoViaje(String motivoViaje) {
		this.motivoViaje = motivoViaje;
	}

	@Column(name = "FECHA_VIAJE", length = 10)
	public String getFechaViaje() {
		return this.fechaViaje;
	}

	public void setFechaViaje(String fechaViaje) {
		this.fechaViaje = fechaViaje;
	}

	@Column(name = "DIAS_VIAJE", length = 5)
	public String getDiasViaje() {
		return this.diasViaje;
	}

	public void setDiasViaje(String diasViaje) {
		this.diasViaje = diasViaje;
	}

	@Column(name = "NUM_MONTO", nullable = false, precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

	@Column(name = "COD_TIPO_MONEDA")
	public Integer getCodTipoMoneda() {
		return this.codTipoMoneda;
	}

	public void setCodTipoMoneda(Integer codTipoMoneda) {
		this.codTipoMoneda = codTipoMoneda;
	}

}
