package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjBloqueIngreso generated by hbm2java
 */
@Entity
@Table(name = "DJ_BLOQUE_INGRESO", schema = "OC_OCMA")
public class DjBloqueIngreso implements java.io.Serializable {

	private DjBloqueIngresoId id;
	private BigDecimal numMonto;
	private Set<DjIngresoItem> djIngresoItems = new HashSet<DjIngresoItem>(0);

	public DjBloqueIngreso() {
	}

	public DjBloqueIngreso(DjBloqueIngresoId id) {
		this.id = id;
	}

	public DjBloqueIngreso(DjBloqueIngresoId id, BigDecimal numMonto,
			Set<DjIngresoItem> djIngresoItems) {
		this.id = id;
		this.numMonto = numMonto;
		this.djIngresoItems = djIngresoItems;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codIngreso", column = @Column(name = "COD_INGRESO", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjBloqueIngresoId getId() {
		return this.id;
	}

	public void setId(DjBloqueIngresoId id) {
		this.id = id;
	}

	@Column(name = "NUM_MONTO", precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djBloqueIngreso")
	public Set<DjIngresoItem> getDjIngresoItems() {
		return this.djIngresoItems;
	}

	public void setDjIngresoItems(Set<DjIngresoItem> djIngresoItems) {
		this.djIngresoItems = djIngresoItems;
	}

}
