package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjBloqueIngresoId generated by hbm2java
 */
@Embeddable
public class DjBloqueIngresoId implements java.io.Serializable {

	private int codIngreso;
	private int codBloque;
	private int codDj;

	public DjBloqueIngresoId() {
	}

	public DjBloqueIngresoId(int codIngreso, int codBloque, int codDj) {
		this.codIngreso = codIngreso;
		this.codBloque = codBloque;
		this.codDj = codDj;
	}

	@Column(name = "COD_INGRESO", nullable = false)
	public int getCodIngreso() {
		return this.codIngreso;
	}

	public void setCodIngreso(int codIngreso) {
		this.codIngreso = codIngreso;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjBloqueIngresoId))
			return false;
		DjBloqueIngresoId castOther = (DjBloqueIngresoId) other;

		return (this.getCodIngreso() == castOther.getCodIngreso())
				&& (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodDj() == castOther.getCodDj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodIngreso();
		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodDj();
		return result;
	}

}
