package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DjBloqueAcreencia generated by hbm2java
 */
@Entity
@Table(name = "DJ_BLOQUE_ACREENCIA", schema = "OC_OCMA")
public class DjBloqueAcreencia implements java.io.Serializable {

	private DjBloqueAcreenciaId id;
	private DjTipoObligacion djTipoObligacion;
	private String desDetalle;
	private BigDecimal numMonto;
	private Integer codTipoAcreencia;
	private Integer codTipoMoneda;

	public DjBloqueAcreencia() {
	}

	public DjBloqueAcreencia(DjBloqueAcreenciaId id) {
		this.id = id;
	}

	public DjBloqueAcreencia(DjBloqueAcreenciaId id,
			DjTipoObligacion djTipoObligacion, String desDetalle,
			BigDecimal numMonto, Integer codTipoAcreencia, Integer codTipoMoneda) {
		this.id = id;
		this.djTipoObligacion = djTipoObligacion;
		this.desDetalle = desDetalle;
		this.numMonto = numMonto;
		this.codTipoAcreencia = codTipoAcreencia;
		this.codTipoMoneda = codTipoMoneda;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codAcreen", column = @Column(name = "COD_ACREEN", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjBloqueAcreenciaId getId() {
		return this.id;
	}

	public void setId(DjBloqueAcreenciaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_TIPO_OBLIGACION")
	public DjTipoObligacion getDjTipoObligacion() {
		return this.djTipoObligacion;
	}

	public void setDjTipoObligacion(DjTipoObligacion djTipoObligacion) {
		this.djTipoObligacion = djTipoObligacion;
	}

	@Column(name = "DES_DETALLE", length = 1000)
	public String getDesDetalle() {
		return this.desDetalle;
	}

	public void setDesDetalle(String desDetalle) {
		this.desDetalle = desDetalle;
	}

	@Column(name = "NUM_MONTO", precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

	@Column(name = "COD_TIPO_ACREENCIA")
	public Integer getCodTipoAcreencia() {
		return this.codTipoAcreencia;
	}

	public void setCodTipoAcreencia(Integer codTipoAcreencia) {
		this.codTipoAcreencia = codTipoAcreencia;
	}

	@Column(name = "COD_TIPO_MONEDA")
	public Integer getCodTipoMoneda() {
		return this.codTipoMoneda;
	}

	public void setCodTipoMoneda(Integer codTipoMoneda) {
		this.codTipoMoneda = codTipoMoneda;
	}

}
