package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DjBloqueMueble generated by hbm2java
 */
@Entity
@Table(name = "DJ_BLOQUE_MUEBLE", schema = "OC_OCMA")
public class DjBloqueMueble implements java.io.Serializable {

	private DjBloqueMuebleId id;
	private String desCaract;
	private String desFicha;
	private BigDecimal numMonto;
	private String desDirecc;
	private String desDetalle;
	private Integer codVivienda;
	private Integer codTipMueble;
	private Integer codTipoMoneda;

	public DjBloqueMueble() {
	}

	public DjBloqueMueble(DjBloqueMuebleId id) {
		this.id = id;
	}

	public DjBloqueMueble(DjBloqueMuebleId id, String desCaract,
			String desFicha, BigDecimal numMonto, String desDirecc,
			String desDetalle, Integer codVivienda, Integer codTipMueble,
			Integer codTipoMoneda) {
		this.id = id;
		this.desCaract = desCaract;
		this.desFicha = desFicha;
		this.numMonto = numMonto;
		this.desDirecc = desDirecc;
		this.desDetalle = desDetalle;
		this.codVivienda = codVivienda;
		this.codTipMueble = codTipMueble;
		this.codTipoMoneda = codTipoMoneda;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codMueble", column = @Column(name = "COD_MUEBLE", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjBloqueMuebleId getId() {
		return this.id;
	}

	public void setId(DjBloqueMuebleId id) {
		this.id = id;
	}

	@Column(name = "DES_CARACT", length = 1000)
	public String getDesCaract() {
		return this.desCaract;
	}

	public void setDesCaract(String desCaract) {
		this.desCaract = desCaract;
	}

	@Column(name = "DES_FICHA", length = 1000)
	public String getDesFicha() {
		return this.desFicha;
	}

	public void setDesFicha(String desFicha) {
		this.desFicha = desFicha;
	}

	@Column(name = "NUM_MONTO", precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

	@Column(name = "DES_DIRECC", length = 1000)
	public String getDesDirecc() {
		return this.desDirecc;
	}

	public void setDesDirecc(String desDirecc) {
		this.desDirecc = desDirecc;
	}

	@Column(name = "DES_DETALLE", length = 1000)
	public String getDesDetalle() {
		return this.desDetalle;
	}

	public void setDesDetalle(String desDetalle) {
		this.desDetalle = desDetalle;
	}

	@Column(name = "COD_VIVIENDA")
	public Integer getCodVivienda() {
		return this.codVivienda;
	}

	public void setCodVivienda(Integer codVivienda) {
		this.codVivienda = codVivienda;
	}

	@Column(name = "COD_TIP_MUEBLE")
	public Integer getCodTipMueble() {
		return this.codTipMueble;
	}

	public void setCodTipMueble(Integer codTipMueble) {
		this.codTipMueble = codTipMueble;
	}

	@Column(name = "COD_TIPO_MONEDA")
	public Integer getCodTipoMoneda() {
		return this.codTipoMoneda;
	}

	public void setCodTipoMoneda(Integer codTipoMoneda) {
		this.codTipoMoneda = codTipoMoneda;
	}

}
