package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjBloqueAcreenciaId generated by hbm2java
 */
@Embeddable
public class DjBloqueAcreenciaId implements java.io.Serializable {

	private int codAcreen;
	private int codBloque;
	private int codDj;

	public DjBloqueAcreenciaId() {
	}

	public DjBloqueAcreenciaId(int codAcreen, int codBloque, int codDj) {
		this.codAcreen = codAcreen;
		this.codBloque = codBloque;
		this.codDj = codDj;
	}

	@Column(name = "COD_ACREEN", nullable = false)
	public int getCodAcreen() {
		return this.codAcreen;
	}

	public void setCodAcreen(int codAcreen) {
		this.codAcreen = codAcreen;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjBloqueAcreenciaId))
			return false;
		DjBloqueAcreenciaId castOther = (DjBloqueAcreenciaId) other;

		return (this.getCodAcreen() == castOther.getCodAcreen())
				&& (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodDj() == castOther.getCodDj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodAcreen();
		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodDj();
		return result;
	}

}
