package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DjBloqueOtroBien generated by hbm2java
 */
@Entity
@Table(name = "DJ_BLOQUE_OTRO_BIEN", schema = "OC_OCMA")
public class DjBloqueOtroBien implements java.io.Serializable {

	private DjBloqueOtroBienId id;
	private String desBien;
	private int codTipo;
	private BigDecimal numMonto;
	private Integer codTipoMoneda;

	public DjBloqueOtroBien() {
	}

	public DjBloqueOtroBien(DjBloqueOtroBienId id, String desBien, int codTipo,
			BigDecimal numMonto) {
		this.id = id;
		this.desBien = desBien;
		this.codTipo = codTipo;
		this.numMonto = numMonto;
	}

	public DjBloqueOtroBien(DjBloqueOtroBienId id, String desBien, int codTipo,
			BigDecimal numMonto, Integer codTipoMoneda) {
		this.id = id;
		this.desBien = desBien;
		this.codTipo = codTipo;
		this.numMonto = numMonto;
		this.codTipoMoneda = codTipoMoneda;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codBien", column = @Column(name = "COD_BIEN", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjBloqueOtroBienId getId() {
		return this.id;
	}

	public void setId(DjBloqueOtroBienId id) {
		this.id = id;
	}

	@Column(name = "DES_BIEN", nullable = false, length = 1000)
	public String getDesBien() {
		return this.desBien;
	}

	public void setDesBien(String desBien) {
		this.desBien = desBien;
	}

	@Column(name = "COD_TIPO", nullable = false)
	public int getCodTipo() {
		return this.codTipo;
	}

	public void setCodTipo(int codTipo) {
		this.codTipo = codTipo;
	}

	@Column(name = "NUM_MONTO", nullable = false, precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

	@Column(name = "COD_TIPO_MONEDA")
	public Integer getCodTipoMoneda() {
		return this.codTipoMoneda;
	}

	public void setCodTipoMoneda(Integer codTipoMoneda) {
		this.codTipoMoneda = codTipoMoneda;
	}

}
