package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjBloqueViajeId generated by hbm2java
 */
@Embeddable
public class DjBloqueViajeId implements java.io.Serializable {

	private int codViaje;
	private int codBloque;
	private int codDj;

	public DjBloqueViajeId() {
	}

	public DjBloqueViajeId(int codViaje, int codBloque, int codDj) {
		this.codViaje = codViaje;
		this.codBloque = codBloque;
		this.codDj = codDj;
	}

	@Column(name = "COD_VIAJE", nullable = false)
	public int getCodViaje() {
		return this.codViaje;
	}

	public void setCodViaje(int codViaje) {
		this.codViaje = codViaje;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjBloqueViajeId))
			return false;
		DjBloqueViajeId castOther = (DjBloqueViajeId) other;

		return (this.getCodViaje() == castOther.getCodViaje())
				&& (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodDj() == castOther.getCodDj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodViaje();
		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodDj();
		return result;
	}

}
