package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjBloqueOtroBienId generated by hbm2java
 */
@Embeddable
public class DjBloqueOtroBienId implements java.io.Serializable {

	private int codBien;
	private int codBloque;
	private int codDj;

	public DjBloqueOtroBienId() {
	}

	public DjBloqueOtroBienId(int codBien, int codBloque, int codDj) {
		this.codBien = codBien;
		this.codBloque = codBloque;
		this.codDj = codDj;
	}

	@Column(name = "COD_BIEN", nullable = false)
	public int getCodBien() {
		return this.codBien;
	}

	public void setCodBien(int codBien) {
		this.codBien = codBien;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjBloqueOtroBienId))
			return false;
		DjBloqueOtroBienId castOther = (DjBloqueOtroBienId) other;

		return (this.getCodBien() == castOther.getCodBien())
				&& (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodDj() == castOther.getCodDj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodBien();
		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodDj();
		return result;
	}

}
