package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjCargoxejercicioId generated by hbm2java
 */
@Embeddable
public class DjCargoxejercicioId implements java.io.Serializable {

	private int codCargo;
	private int desEjercicio;
	private int codEstado;

	public DjCargoxejercicioId() {
	}

	public DjCargoxejercicioId(int codCargo, int desEjercicio, int codEstado) {
		this.codCargo = codCargo;
		this.desEjercicio = desEjercicio;
		this.codEstado = codEstado;
	}

	@Column(name = "COD_CARGO", nullable = false)
	public int getCodCargo() {
		return this.codCargo;
	}

	public void setCodCargo(int codCargo) {
		this.codCargo = codCargo;
	}

	@Column(name = "DES_EJERCICIO", nullable = false)
	public int getDesEjercicio() {
		return this.desEjercicio;
	}

	public void setDesEjercicio(int desEjercicio) {
		this.desEjercicio = desEjercicio;
	}

	@Column(name = "COD_ESTADO", nullable = false)
	public int getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(int codEstado) {
		this.codEstado = codEstado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjCargoxejercicioId))
			return false;
		DjCargoxejercicioId castOther = (DjCargoxejercicioId) other;

		return (this.getCodCargo() == castOther.getCodCargo())
				&& (this.getDesEjercicio() == castOther.getDesEjercicio())
				&& (this.getCodEstado() == castOther.getCodEstado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodCargo();
		result = 37 * result + this.getDesEjercicio();
		result = 37 * result + this.getCodEstado();
		return result;
	}

}
