package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjCargos generated by hbm2java
 */
@Entity
@Table(name = "DJ_CARGOS", schema = "OC_OCMA")
public class DjCargos implements java.io.Serializable {

	private int codCargo;
	private String desCargo;
	private Integer flaCargo;
	private Integer codCargoEquivalentePersonal;
	private Integer codCorrelativo;
	private Set<DjCargoxejercicio> djCargoxejercicios = new HashSet<DjCargoxejercicio>(
			0);

	public DjCargos() {
	}

	public DjCargos(int codCargo, String desCargo) {
		this.codCargo = codCargo;
		this.desCargo = desCargo;
	}

	public DjCargos(int codCargo, String desCargo, Integer flaCargo,
			Integer codCargoEquivalentePersonal, Integer codCorrelativo,
			Set<DjCargoxejercicio> djCargoxejercicios) {
		this.codCargo = codCargo;
		this.desCargo = desCargo;
		this.flaCargo = flaCargo;
		this.codCargoEquivalentePersonal = codCargoEquivalentePersonal;
		this.codCorrelativo = codCorrelativo;
		this.djCargoxejercicios = djCargoxejercicios;
	}

	@Id
	@Column(name = "COD_CARGO", nullable = false)
	public int getCodCargo() {
		return this.codCargo;
	}

	public void setCodCargo(int codCargo) {
		this.codCargo = codCargo;
	}

	@Column(name = "DES_CARGO", nullable = false, length = 200)
	public String getDesCargo() {
		return this.desCargo;
	}

	public void setDesCargo(String desCargo) {
		this.desCargo = desCargo;
	}

	@Column(name = "FLA_CARGO")
	public Integer getFlaCargo() {
		return this.flaCargo;
	}

	public void setFlaCargo(Integer flaCargo) {
		this.flaCargo = flaCargo;
	}

	@Column(name = "COD_CARGO_EQUIVALENTE_PERSONAL")
	public Integer getCodCargoEquivalentePersonal() {
		return this.codCargoEquivalentePersonal;
	}

	public void setCodCargoEquivalentePersonal(
			Integer codCargoEquivalentePersonal) {
		this.codCargoEquivalentePersonal = codCargoEquivalentePersonal;
	}

	@Column(name = "COD_CORRELATIVO")
	public Integer getCodCorrelativo() {
		return this.codCorrelativo;
	}

	public void setCodCorrelativo(Integer codCorrelativo) {
		this.codCorrelativo = codCorrelativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djCargos")
	public Set<DjCargoxejercicio> getDjCargoxejercicios() {
		return this.djCargoxejercicios;
	}

	public void setDjCargoxejercicios(Set<DjCargoxejercicio> djCargoxejercicios) {
		this.djCargoxejercicios = djCargoxejercicios;
	}

}
