package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DjCargoxejercicio generated by hbm2java
 */
@Entity
@Table(name = "DJ_CARGOXEJERCICIO", schema = "OC_OCMA")
public class DjCargoxejercicio implements java.io.Serializable {

	private DjCargoxejercicioId id;
	private DjCargos djCargos;
	private BigDecimal remBrutaMensual;
	private BigDecimal gastoOperativo;

	public DjCargoxejercicio() {
	}

	public DjCargoxejercicio(DjCargoxejercicioId id, DjCargos djCargos,
			BigDecimal remBrutaMensual, BigDecimal gastoOperativo) {
		this.id = id;
		this.djCargos = djCargos;
		this.remBrutaMensual = remBrutaMensual;
		this.gastoOperativo = gastoOperativo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codCargo", column = @Column(name = "COD_CARGO", nullable = false)),
			@AttributeOverride(name = "desEjercicio", column = @Column(name = "DES_EJERCICIO", nullable = false)),
			@AttributeOverride(name = "codEstado", column = @Column(name = "COD_ESTADO", nullable = false)) })
	public DjCargoxejercicioId getId() {
		return this.id;
	}

	public void setId(DjCargoxejercicioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_CARGO", nullable = false, insertable = false, updatable = false)
	public DjCargos getDjCargos() {
		return this.djCargos;
	}

	public void setDjCargos(DjCargos djCargos) {
		this.djCargos = djCargos;
	}

	@Column(name = "REM_BRUTA_MENSUAL", nullable = false, precision = 10)
	public BigDecimal getRemBrutaMensual() {
		return this.remBrutaMensual;
	}

	public void setRemBrutaMensual(BigDecimal remBrutaMensual) {
		this.remBrutaMensual = remBrutaMensual;
	}

	@Column(name = "GASTO_OPERATIVO", nullable = false, precision = 10)
	public BigDecimal getGastoOperativo() {
		return this.gastoOperativo;
	}

	public void setGastoOperativo(BigDecimal gastoOperativo) {
		this.gastoOperativo = gastoOperativo;
	}

}
