package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DjConyugue generated by hbm2java
 */
@Entity
@Table(name = "DJ_CONYUGUE", schema = "OC_OCMA")
public class DjConyugue implements java.io.Serializable {

	private int codDj;
	private DjMaster djMaster;
	private String desApepaterno;
	private String desApematerno;
	private String desNombres;
	private Integer codDocide;
	private String numDocide;
	private String numRuc;
	private BigDecimal numMonto;
	private String desCentroLab;

	public DjConyugue() {
	}

	public DjConyugue(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	public DjConyugue(DjMaster djMaster, String desApepaterno,
			String desApematerno, String desNombres, Integer codDocide,
			String numDocide, String numRuc, BigDecimal numMonto,
			String desCentroLab) {
		this.djMaster = djMaster;
		this.desApepaterno = desApepaterno;
		this.desApematerno = desApematerno;
		this.desNombres = desNombres;
		this.codDocide = codDocide;
		this.numDocide = numDocide;
		this.numRuc = numRuc;
		this.numMonto = numMonto;
		this.desCentroLab = desCentroLab;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "djMaster"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public DjMaster getDjMaster() {
		return this.djMaster;
	}

	public void setDjMaster(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	@Column(name = "DES_APEPATERNO", length = 200)
	public String getDesApepaterno() {
		return this.desApepaterno;
	}

	public void setDesApepaterno(String desApepaterno) {
		this.desApepaterno = desApepaterno;
	}

	@Column(name = "DES_APEMATERNO", length = 200)
	public String getDesApematerno() {
		return this.desApematerno;
	}

	public void setDesApematerno(String desApematerno) {
		this.desApematerno = desApematerno;
	}

	@Column(name = "DES_NOMBRES", length = 200)
	public String getDesNombres() {
		return this.desNombres;
	}

	public void setDesNombres(String desNombres) {
		this.desNombres = desNombres;
	}

	@Column(name = "COD_DOCIDE")
	public Integer getCodDocide() {
		return this.codDocide;
	}

	public void setCodDocide(Integer codDocide) {
		this.codDocide = codDocide;
	}

	@Column(name = "NUM_DOCIDE", length = 50)
	public String getNumDocide() {
		return this.numDocide;
	}

	public void setNumDocide(String numDocide) {
		this.numDocide = numDocide;
	}

	@Column(name = "NUM_RUC", length = 11)
	public String getNumRuc() {
		return this.numRuc;
	}

	public void setNumRuc(String numRuc) {
		this.numRuc = numRuc;
	}

	@Column(name = "NUM_MONTO", precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

	@Column(name = "DES_CENTRO_LAB", length = 250)
	public String getDesCentroLab() {
		return this.desCentroLab;
	}

	public void setDesCentroLab(String desCentroLab) {
		this.desCentroLab = desCentroLab;
	}

}
