package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DjContraloria generated by hbm2java
 */
@Entity
@Table(name = "DJ_CONTRALORIA", schema = "OC_OCMA")
public class DjContraloria implements java.io.Serializable {

	private int codDj;
	private DjMaster djMaster;
	private String desNumeroOficio;
	private String desObservacion;
	private String codUsucre;
	private String codUsumod;
	private Date fecCreacion;
	private Date fecMod;

	public DjContraloria() {
	}

	public DjContraloria(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	public DjContraloria(DjMaster djMaster, String desNumeroOficio,
			String desObservacion, String codUsucre, String codUsumod,
			Date fecCreacion, Date fecMod) {
		this.djMaster = djMaster;
		this.desNumeroOficio = desNumeroOficio;
		this.desObservacion = desObservacion;
		this.codUsucre = codUsucre;
		this.codUsumod = codUsumod;
		this.fecCreacion = fecCreacion;
		this.fecMod = fecMod;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "djMaster"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public DjMaster getDjMaster() {
		return this.djMaster;
	}

	public void setDjMaster(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	@Column(name = "DES_NUMERO_OFICIO", length = 50)
	public String getDesNumeroOficio() {
		return this.desNumeroOficio;
	}

	public void setDesNumeroOficio(String desNumeroOficio) {
		this.desNumeroOficio = desNumeroOficio;
	}

	@Column(name = "DES_OBSERVACION", length = 250)
	public String getDesObservacion() {
		return this.desObservacion;
	}

	public void setDesObservacion(String desObservacion) {
		this.desObservacion = desObservacion;
	}

	@Column(name = "COD_USUCRE", length = 15)
	public String getCodUsucre() {
		return this.codUsucre;
	}

	public void setCodUsucre(String codUsucre) {
		this.codUsucre = codUsucre;
	}

	@Column(name = "COD_USUMOD", length = 15)
	public String getCodUsumod() {
		return this.codUsumod;
	}

	public void setCodUsumod(String codUsumod) {
		this.codUsumod = codUsumod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_CREACION", length = 10)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_MOD", length = 10)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

}
