package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DjDeclarante generated by hbm2java
 */
@Entity
@Table(name = "DJ_DECLARANTE", schema = "OC_OCMA")
public class DjDeclarante implements java.io.Serializable {

	private int codDj;
	private DjMaster djMaster;
	private String desApepaterno;
	private String desApematerno;
	private String desNombre;
	private String desDireccion;
	private String numDni;
	private String numRuc;
	private Integer codCargo;
	private Integer codEstado;
	private Integer codEstciv;
	private String fechaAsume;
	private String fechaCese;
	private Integer anioTs;
	private Integer mesTs;
	private Integer diasTs;
	private Integer numDependientes;

	public DjDeclarante() {
	}

	public DjDeclarante(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	public DjDeclarante(DjMaster djMaster, String desApepaterno,
			String desApematerno, String desNombre, String desDireccion,
			String numDni, String numRuc, Integer codCargo, Integer codEstado,
			Integer codEstciv, String fechaAsume, String fechaCese,
			Integer anioTs, Integer mesTs, Integer diasTs,
			Integer numDependientes) {
		this.djMaster = djMaster;
		this.desApepaterno = desApepaterno;
		this.desApematerno = desApematerno;
		this.desNombre = desNombre;
		this.desDireccion = desDireccion;
		this.numDni = numDni;
		this.numRuc = numRuc;
		this.codCargo = codCargo;
		this.codEstado = codEstado;
		this.codEstciv = codEstciv;
		this.fechaAsume = fechaAsume;
		this.fechaCese = fechaCese;
		this.anioTs = anioTs;
		this.mesTs = mesTs;
		this.diasTs = diasTs;
		this.numDependientes = numDependientes;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "djMaster"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public DjMaster getDjMaster() {
		return this.djMaster;
	}

	public void setDjMaster(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	@Column(name = "DES_APEPATERNO", length = 150)
	public String getDesApepaterno() {
		return this.desApepaterno;
	}

	public void setDesApepaterno(String desApepaterno) {
		this.desApepaterno = desApepaterno;
	}

	@Column(name = "DES_APEMATERNO", length = 150)
	public String getDesApematerno() {
		return this.desApematerno;
	}

	public void setDesApematerno(String desApematerno) {
		this.desApematerno = desApematerno;
	}

	@Column(name = "DES_NOMBRE", length = 150)
	public String getDesNombre() {
		return this.desNombre;
	}

	public void setDesNombre(String desNombre) {
		this.desNombre = desNombre;
	}

	@Column(name = "DES_DIRECCION", length = 600)
	public String getDesDireccion() {
		return this.desDireccion;
	}

	public void setDesDireccion(String desDireccion) {
		this.desDireccion = desDireccion;
	}

	@Column(name = "NUM_DNI", length = 8)
	public String getNumDni() {
		return this.numDni;
	}

	public void setNumDni(String numDni) {
		this.numDni = numDni;
	}

	@Column(name = "NUM_RUC", length = 11)
	public String getNumRuc() {
		return this.numRuc;
	}

	public void setNumRuc(String numRuc) {
		this.numRuc = numRuc;
	}

	@Column(name = "COD_CARGO")
	public Integer getCodCargo() {
		return this.codCargo;
	}

	public void setCodCargo(Integer codCargo) {
		this.codCargo = codCargo;
	}

	@Column(name = "COD_ESTADO")
	public Integer getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(Integer codEstado) {
		this.codEstado = codEstado;
	}

	@Column(name = "COD_ESTCIV")
	public Integer getCodEstciv() {
		return this.codEstciv;
	}

	public void setCodEstciv(Integer codEstciv) {
		this.codEstciv = codEstciv;
	}

	@Column(name = "FECHA_ASUME", length = 10)
	public String getFechaAsume() {
		return this.fechaAsume;
	}

	public void setFechaAsume(String fechaAsume) {
		this.fechaAsume = fechaAsume;
	}

	@Column(name = "FECHA_CESE", length = 10)
	public String getFechaCese() {
		return this.fechaCese;
	}

	public void setFechaCese(String fechaCese) {
		this.fechaCese = fechaCese;
	}

	@Column(name = "ANIO_TS")
	public Integer getAnioTs() {
		return this.anioTs;
	}

	public void setAnioTs(Integer anioTs) {
		this.anioTs = anioTs;
	}

	@Column(name = "MES_TS")
	public Integer getMesTs() {
		return this.mesTs;
	}

	public void setMesTs(Integer mesTs) {
		this.mesTs = mesTs;
	}

	@Column(name = "DIAS_TS")
	public Integer getDiasTs() {
		return this.diasTs;
	}

	public void setDiasTs(Integer diasTs) {
		this.diasTs = diasTs;
	}

	@Column(name = "NUM_DEPENDIENTES")
	public Integer getNumDependientes() {
		return this.numDependientes;
	}

	public void setNumDependientes(Integer numDependientes) {
		this.numDependientes = numDependientes;
	}

}
