package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DjIngresoSector generated by hbm2java
 */
@Entity
@Table(name = "DJ_INGRESO_SECTOR", schema = "OC_OCMA")
public class DjIngresoSector implements java.io.Serializable {

	private DjIngresoSectorId id;
	private BigDecimal numMonto;

	public DjIngresoSector() {
	}

	public DjIngresoSector(DjIngresoSectorId id) {
		this.id = id;
	}

	public DjIngresoSector(DjIngresoSectorId id, BigDecimal numMonto) {
		this.id = id;
		this.numMonto = numMonto;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codIngreso", column = @Column(name = "COD_INGRESO", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)),
			@AttributeOverride(name = "codItem", column = @Column(name = "COD_ITEM", nullable = false)),
			@AttributeOverride(name = "codCategoria", column = @Column(name = "COD_CATEGORIA", nullable = false)),
			@AttributeOverride(name = "codSector", column = @Column(name = "COD_SECTOR", nullable = false)) })
	public DjIngresoSectorId getId() {
		return this.id;
	}

	public void setId(DjIngresoSectorId id) {
		this.id = id;
	}

	@Column(name = "NUM_MONTO", precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

}
