package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjIngresoItemId generated by hbm2java
 */
@Embeddable
public class DjIngresoItemId implements java.io.Serializable {

	private int codIngreso;
	private int codBloque;
	private int codDj;
	private int codItem;
	private int codCategoria;

	public DjIngresoItemId() {
	}

	public DjIngresoItemId(int codIngreso, int codBloque, int codDj,
			int codItem, int codCategoria) {
		this.codIngreso = codIngreso;
		this.codBloque = codBloque;
		this.codDj = codDj;
		this.codItem = codItem;
		this.codCategoria = codCategoria;
	}

	@Column(name = "COD_INGRESO", nullable = false)
	public int getCodIngreso() {
		return this.codIngreso;
	}

	public void setCodIngreso(int codIngreso) {
		this.codIngreso = codIngreso;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	@Column(name = "COD_ITEM", nullable = false)
	public int getCodItem() {
		return this.codItem;
	}

	public void setCodItem(int codItem) {
		this.codItem = codItem;
	}

	@Column(name = "COD_CATEGORIA", nullable = false)
	public int getCodCategoria() {
		return this.codCategoria;
	}

	public void setCodCategoria(int codCategoria) {
		this.codCategoria = codCategoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjIngresoItemId))
			return false;
		DjIngresoItemId castOther = (DjIngresoItemId) other;

		return (this.getCodIngreso() == castOther.getCodIngreso())
				&& (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodDj() == castOther.getCodDj())
				&& (this.getCodItem() == castOther.getCodItem())
				&& (this.getCodCategoria() == castOther.getCodCategoria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodIngreso();
		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodDj();
		result = 37 * result + this.getCodItem();
		result = 37 * result + this.getCodCategoria();
		return result;
	}

}
