package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DjIngresoItem generated by hbm2java
 */
@Entity
@Table(name = "DJ_INGRESO_ITEM", schema = "OC_OCMA")
public class DjIngresoItem implements java.io.Serializable {

	private DjIngresoItemId id;
	private DjBloqueIngreso djBloqueIngreso;
	private DjIngItem djIngItem;
	private BigDecimal numMonto;
	private BigDecimal numMontoAnual;

	public DjIngresoItem() {
	}

	public DjIngresoItem(DjIngresoItemId id, DjBloqueIngreso djBloqueIngreso,
			DjIngItem djIngItem) {
		this.id = id;
		this.djBloqueIngreso = djBloqueIngreso;
		this.djIngItem = djIngItem;
	}

	public DjIngresoItem(DjIngresoItemId id, DjBloqueIngreso djBloqueIngreso,
			DjIngItem djIngItem, BigDecimal numMonto, BigDecimal numMontoAnual) {
		this.id = id;
		this.djBloqueIngreso = djBloqueIngreso;
		this.djIngItem = djIngItem;
		this.numMonto = numMonto;
		this.numMontoAnual = numMontoAnual;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codIngreso", column = @Column(name = "COD_INGRESO", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)),
			@AttributeOverride(name = "codItem", column = @Column(name = "COD_ITEM", nullable = false)),
			@AttributeOverride(name = "codCategoria", column = @Column(name = "COD_CATEGORIA", nullable = false)) })
	public DjIngresoItemId getId() {
		return this.id;
	}

	public void setId(DjIngresoItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_INGRESO", referencedColumnName = "COD_INGRESO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "COD_BLOQUE", referencedColumnName = "COD_BLOQUE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "COD_DJ", referencedColumnName = "COD_DJ", nullable = false, insertable = false, updatable = false) })
	public DjBloqueIngreso getDjBloqueIngreso() {
		return this.djBloqueIngreso;
	}

	public void setDjBloqueIngreso(DjBloqueIngreso djBloqueIngreso) {
		this.djBloqueIngreso = djBloqueIngreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ITEM", nullable = false, insertable = false, updatable = false)
	public DjIngItem getDjIngItem() {
		return this.djIngItem;
	}

	public void setDjIngItem(DjIngItem djIngItem) {
		this.djIngItem = djIngItem;
	}

	@Column(name = "NUM_MONTO", precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

	@Column(name = "NUM_MONTO_ANUAL", precision = 10)
	public BigDecimal getNumMontoAnual() {
		return this.numMontoAnual;
	}

	public void setNumMontoAnual(BigDecimal numMontoAnual) {
		this.numMontoAnual = numMontoAnual;
	}

}
