package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjInstrumento generated by hbm2java
 */
@Entity
@Table(name = "DJ_INSTRUMENTO", schema = "OC_OCMA")
public class DjInstrumento implements java.io.Serializable {

	private int codInstrumento;
	private String desInstrumento;
	private int flaInstrumento;
	private Set<DjBloqueAhorro> djBloqueAhorros = new HashSet<DjBloqueAhorro>(0);

	public DjInstrumento() {
	}

	public DjInstrumento(int codInstrumento, String desInstrumento,
			int flaInstrumento) {
		this.codInstrumento = codInstrumento;
		this.desInstrumento = desInstrumento;
		this.flaInstrumento = flaInstrumento;
	}

	public DjInstrumento(int codInstrumento, String desInstrumento,
			int flaInstrumento, Set<DjBloqueAhorro> djBloqueAhorros) {
		this.codInstrumento = codInstrumento;
		this.desInstrumento = desInstrumento;
		this.flaInstrumento = flaInstrumento;
		this.djBloqueAhorros = djBloqueAhorros;
	}

	@Id
	@Column(name = "COD_INSTRUMENTO", nullable = false)
	public int getCodInstrumento() {
		return this.codInstrumento;
	}

	public void setCodInstrumento(int codInstrumento) {
		this.codInstrumento = codInstrumento;
	}

	@Column(name = "DES_INSTRUMENTO", nullable = false, length = 250)
	public String getDesInstrumento() {
		return this.desInstrumento;
	}

	public void setDesInstrumento(String desInstrumento) {
		this.desInstrumento = desInstrumento;
	}

	@Column(name = "FLA_INSTRUMENTO", nullable = false)
	public int getFlaInstrumento() {
		return this.flaInstrumento;
	}

	public void setFlaInstrumento(int flaInstrumento) {
		this.flaInstrumento = flaInstrumento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djInstrumento")
	public Set<DjBloqueAhorro> getDjBloqueAhorros() {
		return this.djBloqueAhorros;
	}

	public void setDjBloqueAhorros(Set<DjBloqueAhorro> djBloqueAhorros) {
		this.djBloqueAhorros = djBloqueAhorros;
	}

}
