package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjIngresoCategoria generated by hbm2java
 */
@Entity
@Table(name = "DJ_INGRESO_CATEGORIA", schema = "OC_OCMA")
public class DjIngresoCategoria implements java.io.Serializable {

	private int codCategoria;
	private String desCategoria;
	private Integer flaCategoria;
	private Set<DjIngItem> djIngItems = new HashSet<DjIngItem>(0);

	public DjIngresoCategoria() {
	}

	public DjIngresoCategoria(int codCategoria) {
		this.codCategoria = codCategoria;
	}

	public DjIngresoCategoria(int codCategoria, String desCategoria,
			Integer flaCategoria, Set<DjIngItem> djIngItems) {
		this.codCategoria = codCategoria;
		this.desCategoria = desCategoria;
		this.flaCategoria = flaCategoria;
		this.djIngItems = djIngItems;
	}

	@Id
	@Column(name = "COD_CATEGORIA", nullable = false)
	public int getCodCategoria() {
		return this.codCategoria;
	}

	public void setCodCategoria(int codCategoria) {
		this.codCategoria = codCategoria;
	}

	@Column(name = "DES_CATEGORIA", length = 250)
	public String getDesCategoria() {
		return this.desCategoria;
	}

	public void setDesCategoria(String desCategoria) {
		this.desCategoria = desCategoria;
	}

	@Column(name = "FLA_CATEGORIA")
	public Integer getFlaCategoria() {
		return this.flaCategoria;
	}

	public void setFlaCategoria(Integer flaCategoria) {
		this.flaCategoria = flaCategoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djIngresoCategoria")
	public Set<DjIngItem> getDjIngItems() {
		return this.djIngItems;
	}

	public void setDjIngItems(Set<DjIngItem> djIngItems) {
		this.djIngItems = djIngItems;
	}

}
