package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjIngItem generated by hbm2java
 */
@Entity
@Table(name = "DJ_ING_ITEM", schema = "OC_OCMA")
public class DjIngItem implements java.io.Serializable {

	private int codItem;
	private DjIngresoCategoria djIngresoCategoria;
	private String desItem;
	private Integer flaItem;
	private Set<DjIngresoItem> djIngresoItems = new HashSet<DjIngresoItem>(0);

	public DjIngItem() {
	}

	public DjIngItem(int codItem) {
		this.codItem = codItem;
	}

	public DjIngItem(int codItem, DjIngresoCategoria djIngresoCategoria,
			String desItem, Integer flaItem, Set<DjIngresoItem> djIngresoItems) {
		this.codItem = codItem;
		this.djIngresoCategoria = djIngresoCategoria;
		this.desItem = desItem;
		this.flaItem = flaItem;
		this.djIngresoItems = djIngresoItems;
	}

	@Id
	@Column(name = "COD_ITEM", nullable = false)
	public int getCodItem() {
		return this.codItem;
	}

	public void setCodItem(int codItem) {
		this.codItem = codItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_CATEGORIA")
	public DjIngresoCategoria getDjIngresoCategoria() {
		return this.djIngresoCategoria;
	}

	public void setDjIngresoCategoria(DjIngresoCategoria djIngresoCategoria) {
		this.djIngresoCategoria = djIngresoCategoria;
	}

	@Column(name = "DES_ITEM", length = 250)
	public String getDesItem() {
		return this.desItem;
	}

	public void setDesItem(String desItem) {
		this.desItem = desItem;
	}

	@Column(name = "FLA_ITEM")
	public Integer getFlaItem() {
		return this.flaItem;
	}

	public void setFlaItem(Integer flaItem) {
		this.flaItem = flaItem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djIngItem")
	public Set<DjIngresoItem> getDjIngresoItems() {
		return this.djIngresoItems;
	}

	public void setDjIngresoItems(Set<DjIngresoItem> djIngresoItems) {
		this.djIngresoItems = djIngresoItems;
	}

}
