package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.gob.ocma.entities.web_ocma.DistritoJudicial;

/**
 * DjMaster generated by hbm2java
 */
@Entity
@Table(name = "DJ_MASTER", schema = "OC_OCMA")
public class DjMaster implements java.io.Serializable {
	
	private int codDj;
	private DjOpPresentacion djOpPresentacion;
	private String fecElab;
	private String desEntidad;
	private Integer desEjercicio;
	private String fecPresent;
	private String dirEntidad;
	private String numDocumento;
	private Integer codDistrito;
	private DistritoJudicial djmasterDist; //relacion distrito
	private String desObservacion;
	private Date fecCreacion;
	private String codUsucre;
	private Integer flaEstado;
	private TablaDjEstado masterEstados; //relacion Estados DJ
	private String codUsumod;
	private String fecMod;
	private Integer codPersonal;
	private Integer numFojas;
	private Integer desVez;
	private String desPdf;
	private Character flaTipoOrigen;
	private String desGaveta;
	private String desLista;
	private String desControlint;
	private Integer flagContraloria;
	private Set<DjObservacionBloque> djObservacionBloques = new HashSet<DjObservacionBloque>(0);
	private Set<DjOtraInformacion> djOtraInformacions = new HashSet<DjOtraInformacion>(0);
	private Set<DjListaxdj> djListaxdjs = new HashSet<DjListaxdj>(0);
	private DjDeclarante djDeclarante;
	private DjConyugue djConyugue;
	private DjContraloria djContraloria;

	public DjMaster() {
	}

	public DjMaster(int codDj) {
		this.codDj = codDj;
	}
/*
	public DjMaster(int codDj, DjOpPresentacion djOpPresentacion,
			String fecElab, String desEntidad, Integer desEjercicio,
			String fecPresent, String dirEntidad, String numDocumento,
			Integer codDistrito, String desObservacion, Date fecCreacion,
			String codUsucre, Integer flaEstado, String codUsumod,
			String fecMod, Integer codPersonal, Integer numFojas,
			Integer desVez, String desPdf, Character flaTipoOrigen,
			String desGaveta, String desLista, String desControlint,
			Integer flagContraloria,
			Set<DjObservacionBloque> djObservacionBloques,
			Set<DjOtraInformacion> djOtraInformacions,
			Set<DjListaxdj> djListaxdjs, DjDeclarante djDeclarante,
			DjConyugue djConyugue, DjContraloria djContraloria) {
		this.codDj = codDj;
		this.djOpPresentacion = djOpPresentacion;
		this.fecElab = fecElab;
		this.desEntidad = desEntidad;
		this.desEjercicio = desEjercicio;
		this.fecPresent = fecPresent;
		this.dirEntidad = dirEntidad;
		this.numDocumento = numDocumento;
		this.codDistrito = codDistrito;
		this.desObservacion = desObservacion;
		this.fecCreacion = fecCreacion;
		this.codUsucre = codUsucre;
		this.flaEstado = flaEstado;
		this.codUsumod = codUsumod;
		this.fecMod = fecMod;
		this.codPersonal = codPersonal;
		this.numFojas = numFojas;
		this.desVez = desVez;
		this.desPdf = desPdf;
		this.flaTipoOrigen = flaTipoOrigen;
		this.desGaveta = desGaveta;
		this.desLista = desLista;
		this.desControlint = desControlint;
		this.flagContraloria = flagContraloria;
		this.djObservacionBloques = djObservacionBloques;
		this.djOtraInformacions = djOtraInformacions;
		this.djListaxdjs = djListaxdjs;
		this.djDeclarante = djDeclarante;
		this.djConyugue = djConyugue;
		this.djContraloria = djContraloria;
	}*/

	@Id
	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_PRESENT")
	public DjOpPresentacion getDjOpPresentacion() {
		return this.djOpPresentacion;
	}

	public void setDjOpPresentacion(DjOpPresentacion djOpPresentacion) {
		this.djOpPresentacion = djOpPresentacion;
	}

	@Column(name = "FEC_ELAB", length = 10)
	public String getFecElab() {
		return this.fecElab;
	}

	public void setFecElab(String fecElab) {
		this.fecElab = fecElab;
	}

	@Column(name = "DES_ENTIDAD", length = 250)
	public String getDesEntidad() {
		return this.desEntidad;
	}

	public void setDesEntidad(String desEntidad) {
		this.desEntidad = desEntidad;
	}

	@Column(name = "DES_EJERCICIO")
	public Integer getDesEjercicio() {
		return this.desEjercicio;
	}

	public void setDesEjercicio(Integer desEjercicio) {
		this.desEjercicio = desEjercicio;
	}

	@Column(name = "FEC_PRESENT", length = 10)
	public String getFecPresent() {
		return this.fecPresent;
	}

	public void setFecPresent(String fecPresent) {
		this.fecPresent = fecPresent;
	}

	@Column(name = "DIR_ENTIDAD", length = 500)
	public String getDirEntidad() {
		return this.dirEntidad;
	}

	public void setDirEntidad(String dirEntidad) {
		this.dirEntidad = dirEntidad;
	}

	@Column(name = "NUM_DOCUMENTO", length = 100)
	public String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	@Column(name = "COD_DISTRITO")
	public Integer getCodDistrito() {
		return this.codDistrito;
	}

	public void setCodDistrito(Integer codDistrito) {
		this.codDistrito = codDistrito;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DISTRITO", nullable = false, insertable = false, updatable = false)
	public DistritoJudicial getDjmasterDist() {
		return djmasterDist;
	}
	
	public void setDjmasterDist(DistritoJudicial djmasterDist) {
		this.djmasterDist = djmasterDist;
	}

	@Column(name = "DES_OBSERVACION", length = 1000)
	public String getDesObservacion() {
		return this.desObservacion;
	}

	public void setDesObservacion(String desObservacion) {
		this.desObservacion = desObservacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_CREACION", length = 26)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Column(name = "COD_USUCRE", length = 15)
	public String getCodUsucre() {
		return this.codUsucre;
	}

	public void setCodUsucre(String codUsucre) {
		this.codUsucre = codUsucre;
	}	

	@Column(name = "FLA_ESTADO")
	public Integer getFlaEstado() {
		return this.flaEstado;
	}
	
	public void setFlaEstado(Integer flaEstado) {
		this.flaEstado = flaEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FLA_ESTADO", nullable = false, insertable = false, updatable = false)
	public TablaDjEstado getMasterEstados() {
		return masterEstados;
	}
	
	public void setMasterEstados(TablaDjEstado masterEstados) {
		this.masterEstados = masterEstados;
	}
	

	@Column(name = "COD_USUMOD", length = 15)
	public String getCodUsumod() {
		return this.codUsumod;
	}

	public void setCodUsumod(String codUsumod) {
		this.codUsumod = codUsumod;
	}

	@Column(name = "FEC_MOD", length = 250)
	public String getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(String fecMod) {
		this.fecMod = fecMod;
	}

	@Column(name = "COD_PERSONAL")
	public Integer getCodPersonal() {
		return this.codPersonal;
	}

	public void setCodPersonal(Integer codPersonal) {
		this.codPersonal = codPersonal;
	}

	@Column(name = "NUM_FOJAS")
	public Integer getNumFojas() {
		return this.numFojas;
	}

	public void setNumFojas(Integer numFojas) {
		this.numFojas = numFojas;
	}

	@Column(name = "DES_VEZ")
	public Integer getDesVez() {
		return this.desVez;
	}

	public void setDesVez(Integer desVez) {
		this.desVez = desVez;
	}

	@Column(name = "DES_PDF", length = 50)
	public String getDesPdf() {
		return this.desPdf;
	}

	public void setDesPdf(String desPdf) {
		this.desPdf = desPdf;
	}

	@Column(name = "FLA_TIPO_ORIGEN", length = 1)
	public Character getFlaTipoOrigen() {
		return this.flaTipoOrigen;
	}

	public void setFlaTipoOrigen(Character flaTipoOrigen) {
		this.flaTipoOrigen = flaTipoOrigen;
	}

	@Column(name = "DES_GAVETA", length = 10)
	public String getDesGaveta() {
		return this.desGaveta;
	}

	public void setDesGaveta(String desGaveta) {
		this.desGaveta = desGaveta;
	}

	@Column(name = "DES_LISTA", length = 1500)
	public String getDesLista() {
		return this.desLista;
	}

	public void setDesLista(String desLista) {
		this.desLista = desLista;
	}

	@Column(name = "DES_CONTROLINT", length = 1500)
	public String getDesControlint() {
		return this.desControlint;
	}

	public void setDesControlint(String desControlint) {
		this.desControlint = desControlint;
	}

	@Column(name = "FLAG_CONTRALORIA")
	public Integer getFlagContraloria() {
		return this.flagContraloria;
	}

	public void setFlagContraloria(Integer flagContraloria) {
		this.flagContraloria = flagContraloria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djMaster")
	public Set<DjObservacionBloque> getDjObservacionBloques() {
		return this.djObservacionBloques;
	}

	public void setDjObservacionBloques(
			Set<DjObservacionBloque> djObservacionBloques) {
		this.djObservacionBloques = djObservacionBloques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djMaster")
	public Set<DjOtraInformacion> getDjOtraInformacions() {
		return this.djOtraInformacions;
	}

	public void setDjOtraInformacions(Set<DjOtraInformacion> djOtraInformacions) {
		this.djOtraInformacions = djOtraInformacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djMaster")
	public Set<DjListaxdj> getDjListaxdjs() {
		return this.djListaxdjs;
	}

	public void setDjListaxdjs(Set<DjListaxdj> djListaxdjs) {
		this.djListaxdjs = djListaxdjs;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "djMaster")
	public DjDeclarante getDjDeclarante() {
		return this.djDeclarante;
	}

	public void setDjDeclarante(DjDeclarante djDeclarante) {
		this.djDeclarante = djDeclarante;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "djMaster")
	public DjConyugue getDjConyugue() {
		return this.djConyugue;
	}

	public void setDjConyugue(DjConyugue djConyugue) {
		this.djConyugue = djConyugue;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "djMaster")
	public DjContraloria getDjContraloria() {
		return this.djContraloria;
	}

	public void setDjContraloria(DjContraloria djContraloria) {
		this.djContraloria = djContraloria;
	}

}
