package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjObservacionBloque generated by hbm2java
 */
@Entity
@Table(name = "DJ_OBSERVACION_BLOQUE", schema = "OC_OCMA")
public class DjObservacionBloque implements java.io.Serializable {

	private DjObservacionBloqueId id;
	private DjMaster djMaster;
	private String desObservacionBloque;
	private Date fecObservacion;
	private Date fecCreacion;
	private Date fecModificacion;
	private int codTipoObs;
	private String codUsucre;
	private String codUsumod;
	private Integer flagVisible;

	public DjObservacionBloque() {
	}

	public DjObservacionBloque(DjObservacionBloqueId id, DjMaster djMaster,
			String desObservacionBloque, Date fecObservacion, Date fecCreacion,
			int codTipoObs) {
		this.id = id;
		this.djMaster = djMaster;
		this.desObservacionBloque = desObservacionBloque;
		this.fecObservacion = fecObservacion;
		this.fecCreacion = fecCreacion;
		this.codTipoObs = codTipoObs;
	}

	public DjObservacionBloque(DjObservacionBloqueId id, DjMaster djMaster,
			String desObservacionBloque, Date fecObservacion, Date fecCreacion,
			Date fecModificacion, int codTipoObs, String codUsucre,
			String codUsumod, Integer flagVisible) {
		this.id = id;
		this.djMaster = djMaster;
		this.desObservacionBloque = desObservacionBloque;
		this.fecObservacion = fecObservacion;
		this.fecCreacion = fecCreacion;
		this.fecModificacion = fecModificacion;
		this.codTipoObs = codTipoObs;
		this.codUsucre = codUsucre;
		this.codUsumod = codUsumod;
		this.flagVisible = flagVisible;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codObservacion", column = @Column(name = "COD_OBSERVACION", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjObservacionBloqueId getId() {
		return this.id;
	}

	public void setId(DjObservacionBloqueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DJ", nullable = false, insertable = false, updatable = false)
	public DjMaster getDjMaster() {
		return this.djMaster;
	}

	public void setDjMaster(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	@Column(name = "DES_OBSERVACION_BLOQUE", nullable = false)
	public String getDesObservacionBloque() {
		return this.desObservacionBloque;
	}

	public void setDesObservacionBloque(String desObservacionBloque) {
		this.desObservacionBloque = desObservacionBloque;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_OBSERVACION", nullable = false, length = 10)
	public Date getFecObservacion() {
		return this.fecObservacion;
	}

	public void setFecObservacion(Date fecObservacion) {
		this.fecObservacion = fecObservacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_CREACION", nullable = false, length = 10)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_MODIFICACION", length = 10)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "COD_TIPO_OBS", nullable = false)
	public int getCodTipoObs() {
		return this.codTipoObs;
	}

	public void setCodTipoObs(int codTipoObs) {
		this.codTipoObs = codTipoObs;
	}

	@Column(name = "COD_USUCRE", length = 15)
	public String getCodUsucre() {
		return this.codUsucre;
	}

	public void setCodUsucre(String codUsucre) {
		this.codUsucre = codUsucre;
	}

	@Column(name = "COD_USUMOD", length = 15)
	public String getCodUsumod() {
		return this.codUsumod;
	}

	public void setCodUsumod(String codUsumod) {
		this.codUsumod = codUsumod;
	}

	@Column(name = "flag_visible")
	public Integer getFlagVisible() {
		return this.flagVisible;
	}

	public void setFlagVisible(Integer flagVisible) {
		this.flagVisible = flagVisible;
	}

}
