package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjOtraInformacionId generated by hbm2java
 */
@Embeddable
public class DjOtraInformacionId implements java.io.Serializable {

	private int codDj;
	private int codOtra;

	public DjOtraInformacionId() {
	}

	public DjOtraInformacionId(int codDj, int codOtra) {
		this.codDj = codDj;
		this.codOtra = codOtra;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	@Column(name = "COD_OTRA", nullable = false)
	public int getCodOtra() {
		return this.codOtra;
	}

	public void setCodOtra(int codOtra) {
		this.codOtra = codOtra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjOtraInformacionId))
			return false;
		DjOtraInformacionId castOther = (DjOtraInformacionId) other;

		return (this.getCodDj() == castOther.getCodDj())
				&& (this.getCodOtra() == castOther.getCodOtra());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodDj();
		result = 37 * result + this.getCodOtra();
		return result;
	}

}
