package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DjOtroBienSector generated by hbm2java
 */
@Entity
@Table(name = "DJ_OTRO_BIEN_SECTOR", schema = "OC_OCMA")
public class DjOtroBienSector implements java.io.Serializable {

	private DjOtroBienSectorId id;
	private BigDecimal numMonto;

	public DjOtroBienSector() {
	}

	public DjOtroBienSector(DjOtroBienSectorId id, BigDecimal numMonto) {
		this.id = id;
		this.numMonto = numMonto;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codSector", column = @Column(name = "COD_SECTOR", nullable = false)),
			@AttributeOverride(name = "codBien", column = @Column(name = "COD_BIEN", nullable = false)),
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public DjOtroBienSectorId getId() {
		return this.id;
	}

	public void setId(DjOtroBienSectorId id) {
		this.id = id;
	}

	@Column(name = "NUM_MONTO", nullable = false, precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

}
