package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DjOtraInformacion generated by hbm2java
 */
@Entity
@Table(name = "DJ_OTRA_INFORMACION", schema = "OC_OCMA")
public class DjOtraInformacion implements java.io.Serializable {

	private DjOtraInformacionId id;
	private DjTipoMoneda djTipoMoneda;
	private DjMaster djMaster;
	private String desOtro;
	private BigDecimal numMonto;

	public DjOtraInformacion() {
	}

	public DjOtraInformacion(DjOtraInformacionId id, DjTipoMoneda djTipoMoneda,
			DjMaster djMaster, String desOtro, BigDecimal numMonto) {
		this.id = id;
		this.djTipoMoneda = djTipoMoneda;
		this.djMaster = djMaster;
		this.desOtro = desOtro;
		this.numMonto = numMonto;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)),
			@AttributeOverride(name = "codOtra", column = @Column(name = "COD_OTRA", nullable = false)) })
	public DjOtraInformacionId getId() {
		return this.id;
	}

	public void setId(DjOtraInformacionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_TIPO_MONEDA", nullable = false)
	public DjTipoMoneda getDjTipoMoneda() {
		return this.djTipoMoneda;
	}

	public void setDjTipoMoneda(DjTipoMoneda djTipoMoneda) {
		this.djTipoMoneda = djTipoMoneda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DJ", nullable = false, insertable = false, updatable = false)
	public DjMaster getDjMaster() {
		return this.djMaster;
	}

	public void setDjMaster(DjMaster djMaster) {
		this.djMaster = djMaster;
	}

	@Column(name = "DES_OTRO", nullable = false)
	public String getDesOtro() {
		return this.desOtro;
	}

	public void setDesOtro(String desOtro) {
		this.desOtro = desOtro;
	}

	@Column(name = "NUM_MONTO", nullable = false, precision = 10)
	public BigDecimal getNumMonto() {
		return this.numMonto;
	}

	public void setNumMonto(BigDecimal numMonto) {
		this.numMonto = numMonto;
	}

}
