package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjPersonalId generated by hbm2java
 */
@Embeddable
public class DjPersonalId implements java.io.Serializable {

	private String apepaterno;
	private String apematerno;
	private String nombres;
	private String dni;
	private Integer codIntper;

	public DjPersonalId() {
	}

	public DjPersonalId(String apepaterno, String apematerno, String nombres,
			String dni, Integer codIntper) {
		this.apepaterno = apepaterno;
		this.apematerno = apematerno;
		this.nombres = nombres;
		this.dni = dni;
		this.codIntper = codIntper;
	}

	@Column(name = "APEPATERNO")
	public String getApepaterno() {
		return this.apepaterno;
	}

	public void setApepaterno(String apepaterno) {
		this.apepaterno = apepaterno;
	}

	@Column(name = "APEMATERNO")
	public String getApematerno() {
		return this.apematerno;
	}

	public void setApematerno(String apematerno) {
		this.apematerno = apematerno;
	}

	@Column(name = "NOMBRES")
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "DNI")
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "COD_INTPER")
	public Integer getCodIntper() {
		return this.codIntper;
	}

	public void setCodIntper(Integer codIntper) {
		this.codIntper = codIntper;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjPersonalId))
			return false;
		DjPersonalId castOther = (DjPersonalId) other;

		return ((this.getApepaterno() == castOther.getApepaterno()) || (this
				.getApepaterno() != null && castOther.getApepaterno() != null && this
				.getApepaterno().equals(castOther.getApepaterno())))
				&& ((this.getApematerno() == castOther.getApematerno()) || (this
						.getApematerno() != null
						&& castOther.getApematerno() != null && this
						.getApematerno().equals(castOther.getApematerno())))
				&& ((this.getNombres() == castOther.getNombres()) || (this
						.getNombres() != null && castOther.getNombres() != null && this
						.getNombres().equals(castOther.getNombres())))
				&& ((this.getDni() == castOther.getDni()) || (this.getDni() != null
						&& castOther.getDni() != null && this.getDni().equals(
						castOther.getDni())))
				&& ((this.getCodIntper() == castOther.getCodIntper()) || (this
						.getCodIntper() != null
						&& castOther.getCodIntper() != null && this
						.getCodIntper().equals(castOther.getCodIntper())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getApepaterno() == null ? 0 : this.getApepaterno()
						.hashCode());
		result = 37
				* result
				+ (getApematerno() == null ? 0 : this.getApematerno()
						.hashCode());
		result = 37 * result
				+ (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37 * result
				+ (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result
				+ (getCodIntper() == null ? 0 : this.getCodIntper().hashCode());
		return result;
	}

}
