package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DjPersonal generated by hbm2java
 */
@Entity
@Table(name = "DJ_PERSONAL", schema = "OC_OCMA")
public class DjPersonal implements java.io.Serializable {

	private DjPersonalId id;

	public DjPersonal() {
	}

	public DjPersonal(DjPersonalId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "apepaterno", column = @Column(name = "APEPATERNO")),
			@AttributeOverride(name = "apematerno", column = @Column(name = "APEMATERNO")),
			@AttributeOverride(name = "nombres", column = @Column(name = "NOMBRES")),
			@AttributeOverride(name = "dni", column = @Column(name = "DNI")),
			@AttributeOverride(name = "codIntper", column = @Column(name = "COD_INTPER")) })
	public DjPersonalId getId() {
		return this.id;
	}

	public void setId(DjPersonalId id) {
		this.id = id;
	}

}
