package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DjTipoMueble generated by hbm2java
 */
@Entity
@Table(name = "DJ_TIPO_MUEBLE", schema = "OC_OCMA")
public class DjTipoMueble implements java.io.Serializable {

	private DjTipoMuebleId id;

	public DjTipoMueble() {
	}

	public DjTipoMueble(DjTipoMuebleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codTipoMueble", column = @Column(name = "COD_TIPO_MUEBLE", nullable = false)),
			@AttributeOverride(name = "desTipoMueble", column = @Column(name = "DES_TIPO_MUEBLE", nullable = false, length = 250)),
			@AttributeOverride(name = "flaTipoMueble", column = @Column(name = "FLA_TIPO_MUEBLE", nullable = false)),
			@AttributeOverride(name = "flaVehiculo", column = @Column(name = "FLA_VEHICULO")) })
	public DjTipoMuebleId getId() {
		return this.id;
	}

	public void setId(DjTipoMuebleId id) {
		this.id = id;
	}

}
