package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DjTipoSector generated by hbm2java
 */
@Entity
@Table(name = "DJ_TIPO_SECTOR", schema = "OC_OCMA")
public class DjTipoSector implements java.io.Serializable {

	private int codSector;
	private String desSector;
	private int flaSector;

	public DjTipoSector() {
	}

	public DjTipoSector(int codSector, String desSector, int flaSector) {
		this.codSector = codSector;
		this.desSector = desSector;
		this.flaSector = flaSector;
	}

	@Id
	@Column(name = "COD_SECTOR", nullable = false)
	public int getCodSector() {
		return this.codSector;
	}

	public void setCodSector(int codSector) {
		this.codSector = codSector;
	}

	@Column(name = "DES_SECTOR", nullable = false, length = 250)
	public String getDesSector() {
		return this.desSector;
	}

	public void setDesSector(String desSector) {
		this.desSector = desSector;
	}

	@Column(name = "FLA_SECTOR", nullable = false)
	public int getFlaSector() {
		return this.flaSector;
	}

	public void setFlaSector(int flaSector) {
		this.flaSector = flaSector;
	}

}
