package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjTipoObligacion generated by hbm2java
 */
@Entity
@Table(name = "DJ_TIPO_OBLIGACION", schema = "OC_OCMA")
public class DjTipoObligacion implements java.io.Serializable {

	private char codTipoObligacion;
	private String desTipoObligacion;
	private Set<DjBloqueAcreencia> djBloqueAcreencias = new HashSet<DjBloqueAcreencia>(
			0);

	public DjTipoObligacion() {
	}

	public DjTipoObligacion(char codTipoObligacion, String desTipoObligacion) {
		this.codTipoObligacion = codTipoObligacion;
		this.desTipoObligacion = desTipoObligacion;
	}

	public DjTipoObligacion(char codTipoObligacion, String desTipoObligacion,
			Set<DjBloqueAcreencia> djBloqueAcreencias) {
		this.codTipoObligacion = codTipoObligacion;
		this.desTipoObligacion = desTipoObligacion;
		this.djBloqueAcreencias = djBloqueAcreencias;
	}

	@Id
	@Column(name = "COD_TIPO_OBLIGACION", nullable = false, length = 1)
	public char getCodTipoObligacion() {
		return this.codTipoObligacion;
	}

	public void setCodTipoObligacion(char codTipoObligacion) {
		this.codTipoObligacion = codTipoObligacion;
	}

	@Column(name = "DES_TIPO_OBLIGACION", nullable = false, length = 100)
	public String getDesTipoObligacion() {
		return this.desTipoObligacion;
	}

	public void setDesTipoObligacion(String desTipoObligacion) {
		this.desTipoObligacion = desTipoObligacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djTipoObligacion")
	public Set<DjBloqueAcreencia> getDjBloqueAcreencias() {
		return this.djBloqueAcreencias;
	}

	public void setDjBloqueAcreencias(Set<DjBloqueAcreencia> djBloqueAcreencias) {
		this.djBloqueAcreencias = djBloqueAcreencias;
	}

}
