package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DjTipoMuebleId generated by hbm2java
 */
@Embeddable
public class DjTipoMuebleId implements java.io.Serializable {

	private int codTipoMueble;
	private String desTipoMueble;
	private int flaTipoMueble;
	private Integer flaVehiculo;

	public DjTipoMuebleId() {
	}

	public DjTipoMuebleId(int codTipoMueble, String desTipoMueble,
			int flaTipoMueble) {
		this.codTipoMueble = codTipoMueble;
		this.desTipoMueble = desTipoMueble;
		this.flaTipoMueble = flaTipoMueble;
	}

	public DjTipoMuebleId(int codTipoMueble, String desTipoMueble,
			int flaTipoMueble, Integer flaVehiculo) {
		this.codTipoMueble = codTipoMueble;
		this.desTipoMueble = desTipoMueble;
		this.flaTipoMueble = flaTipoMueble;
		this.flaVehiculo = flaVehiculo;
	}

	@Column(name = "COD_TIPO_MUEBLE", nullable = false)
	public int getCodTipoMueble() {
		return this.codTipoMueble;
	}

	public void setCodTipoMueble(int codTipoMueble) {
		this.codTipoMueble = codTipoMueble;
	}

	@Column(name = "DES_TIPO_MUEBLE", nullable = false, length = 250)
	public String getDesTipoMueble() {
		return this.desTipoMueble;
	}

	public void setDesTipoMueble(String desTipoMueble) {
		this.desTipoMueble = desTipoMueble;
	}

	@Column(name = "FLA_TIPO_MUEBLE", nullable = false)
	public int getFlaTipoMueble() {
		return this.flaTipoMueble;
	}

	public void setFlaTipoMueble(int flaTipoMueble) {
		this.flaTipoMueble = flaTipoMueble;
	}

	@Column(name = "FLA_VEHICULO")
	public Integer getFlaVehiculo() {
		return this.flaVehiculo;
	}

	public void setFlaVehiculo(Integer flaVehiculo) {
		this.flaVehiculo = flaVehiculo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DjTipoMuebleId))
			return false;
		DjTipoMuebleId castOther = (DjTipoMuebleId) other;

		return (this.getCodTipoMueble() == castOther.getCodTipoMueble())
				&& ((this.getDesTipoMueble() == castOther.getDesTipoMueble()) || (this
						.getDesTipoMueble() != null
						&& castOther.getDesTipoMueble() != null && this
						.getDesTipoMueble()
						.equals(castOther.getDesTipoMueble())))
				&& (this.getFlaTipoMueble() == castOther.getFlaTipoMueble())
				&& ((this.getFlaVehiculo() == castOther.getFlaVehiculo()) || (this
						.getFlaVehiculo() != null
						&& castOther.getFlaVehiculo() != null && this
						.getFlaVehiculo().equals(castOther.getFlaVehiculo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTipoMueble();
		result = 37
				* result
				+ (getDesTipoMueble() == null ? 0 : this.getDesTipoMueble()
						.hashCode());
		result = 37 * result + this.getFlaTipoMueble();
		result = 37
				* result
				+ (getFlaVehiculo() == null ? 0 : this.getFlaVehiculo()
						.hashCode());
		return result;
	}

}
