package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DjTipoMov generated by hbm2java
 */
@Entity
@Table(name = "DJ_TIPO_MOV", schema = "OC_OCMA")
public class DjTipoMov implements java.io.Serializable {

	private char codTipoMov;
	private String desTipoMovDj;

	public DjTipoMov() {
	}

	public DjTipoMov(char codTipoMov, String desTipoMovDj) {
		this.codTipoMov = codTipoMov;
		this.desTipoMovDj = desTipoMovDj;
	}

	@Id
	@Column(name = "COD_TIPO_MOV", nullable = false, length = 1)
	public char getCodTipoMov() {
		return this.codTipoMov;
	}

	public void setCodTipoMov(char codTipoMov) {
		this.codTipoMov = codTipoMov;
	}

	@Column(name = "DES_TIPO_MOV_DJ", nullable = false, length = 100)
	public String getDesTipoMovDj() {
		return this.desTipoMovDj;
	}

	public void setDesTipoMovDj(String desTipoMovDj) {
		this.desTipoMovDj = desTipoMovDj;
	}

}
