package pe.gob.ocma.entities.oc_ocma;
// Generated 16/05/2014 08:49:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjTipoMoneda generated by hbm2java
 */
@Entity
@Table(name = "DJ_TIPO_MONEDA", schema = "OC_OCMA")
public class DjTipoMoneda implements java.io.Serializable {

	private int codTipoMoneda;
	private String desTipoMoneda;
	private int flaTipoMoneda;
	private Set<DjOtraInformacion> djOtraInformacions = new HashSet<DjOtraInformacion>(
			0);

	public DjTipoMoneda() {
	}

	public DjTipoMoneda(int codTipoMoneda, String desTipoMoneda,
			int flaTipoMoneda) {
		this.codTipoMoneda = codTipoMoneda;
		this.desTipoMoneda = desTipoMoneda;
		this.flaTipoMoneda = flaTipoMoneda;
	}

	public DjTipoMoneda(int codTipoMoneda, String desTipoMoneda,
			int flaTipoMoneda, Set<DjOtraInformacion> djOtraInformacions) {
		this.codTipoMoneda = codTipoMoneda;
		this.desTipoMoneda = desTipoMoneda;
		this.flaTipoMoneda = flaTipoMoneda;
		this.djOtraInformacions = djOtraInformacions;
	}

	@Id
	@Column(name = "COD_TIPO_MONEDA", nullable = false)
	public int getCodTipoMoneda() {
		return this.codTipoMoneda;
	}

	public void setCodTipoMoneda(int codTipoMoneda) {
		this.codTipoMoneda = codTipoMoneda;
	}

	@Column(name = "DES_TIPO_MONEDA", nullable = false, length = 200)
	public String getDesTipoMoneda() {
		return this.desTipoMoneda;
	}

	public void setDesTipoMoneda(String desTipoMoneda) {
		this.desTipoMoneda = desTipoMoneda;
	}

	@Column(name = "FLA_TIPO_MONEDA", nullable = false)
	public int getFlaTipoMoneda() {
		return this.flaTipoMoneda;
	}

	public void setFlaTipoMoneda(int flaTipoMoneda) {
		this.flaTipoMoneda = flaTipoMoneda;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djTipoMoneda")
	public Set<DjOtraInformacion> getDjOtraInformacions() {
		return this.djOtraInformacions;
	}

	public void setDjOtraInformacions(Set<DjOtraInformacion> djOtraInformacions) {
		this.djOtraInformacions = djOtraInformacions;
	}

}
