package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExpePers generated by hbm2java
 */
@Entity
@Table(name = "EXPE_PERS", schema = "OC_OCMA")
public class ExpePers implements java.io.Serializable {

	private ExpePersId id;
	private ExpeMast expeMast;
	private Personal personal;
	private ExpeEsta expeEsta;
	private int codDistri;
	private int codCiudad;
	private Despachos persDespacho;
	private int codDespac;
	private Dependen persDependecia;
	private int codDepend;
	private Cargos persCargo;
	private int codCargo;
	private int codFuncio;
	private Funciones persFunciones;
	private Integer codEstper;
	private Set<SeguReso> seguResos = new HashSet<SeguReso>(0);

	public ExpePers() {
	}

	public ExpePers(ExpePersId id, ExpeMast expeMast, Personal personal,
			int codDistri, int codCiudad, int codDespac, int codDepend,
			int codCargo, int codFuncio) {
		this.id = id;
		this.expeMast = expeMast;
		this.personal = personal;
		this.codDistri = codDistri;
		this.codCiudad = codCiudad;
		this.codDespac = codDespac;
		this.codDepend = codDepend;
		this.codCargo = codCargo;
		this.codFuncio = codFuncio;
	}

	public ExpePers(ExpePersId id, ExpeMast expeMast, Personal personal,
			ExpeEsta expeEsta, int codDistri, int codCiudad, int codDespac,
			int codDepend, int codCargo, int codFuncio, Integer codEstper,
			Set<SeguReso> seguResos) {
		this.id = id;
		this.expeMast = expeMast;
		this.personal = personal;
		this.expeEsta = expeEsta;
		this.codDistri = codDistri;
		this.codCiudad = codCiudad;
		this.codDespac = codDespac;
		this.codDepend = codDepend;
		this.codCargo = codCargo;
		this.codFuncio = codFuncio;
		this.codEstper = codEstper;
		this.seguResos = seguResos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codDistritoOrigen", column = @Column(name = "COD_DISTRITO_ORIGEN", nullable = false)),
			@AttributeOverride(name = "codIntexp", column = @Column(name = "COD_INTEXP", nullable = false)),
			@AttributeOverride(name = "codIntper", column = @Column(name = "COD_INTPER", nullable = false)) })
	public ExpePersId getId() {
		return this.id;
	}

	public void setId(ExpePersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_DISTRITO_ORIGEN", referencedColumnName = "COD_DISTRITO_ORIGEN", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "COD_INTEXP", referencedColumnName = "COD_INTEXP", nullable = false, insertable = false, updatable = false) })
	public ExpeMast getExpeMast() {
		return this.expeMast;
	}

	public void setExpeMast(ExpeMast expeMast) {
		this.expeMast = expeMast;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_INTPER", nullable = false, insertable = false, updatable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ESTADO")
	public ExpeEsta getExpeEsta() {
		return this.expeEsta;
	}

	public void setExpeEsta(ExpeEsta expeEsta) {
		this.expeEsta = expeEsta;
	}

	@Column(name = "COD_DISTRI", nullable = false)
	public int getCodDistri() {
		return this.codDistri;
	}

	public void setCodDistri(int codDistri) {
		this.codDistri = codDistri;
	}

	@Column(name = "COD_CIUDAD", nullable = false)
	public int getCodCiudad() {
		return this.codCiudad;
	}

	public void setCodCiudad(int codCiudad) {
		this.codCiudad = codCiudad;
	}

	@Column(name = "COD_DESPAC", nullable = false)
	public int getCodDespac() {
		return this.codDespac;
	}

	public void setCodDespac(int codDespac) {
		this.codDespac = codDespac;
	}

	@Column(name = "COD_DEPEND", nullable = false)
	public int getCodDepend() {
		return this.codDepend;
	}

	public void setCodDepend(int codDepend) {
		this.codDepend = codDepend;
	}

	@Column(name = "COD_CARGO", nullable = false)
	public int getCodCargo() {
		return this.codCargo;
	}

	public void setCodCargo(int codCargo) {
		this.codCargo = codCargo;
	}

	@Column(name = "COD_FUNCIO", nullable = false)
	public int getCodFuncio() {
		return this.codFuncio;
	}

	public void setCodFuncio(int codFuncio) {
		this.codFuncio = codFuncio;
	}

	@Column(name = "COD_ESTPER")
	public Integer getCodEstper() {
		return this.codEstper;
	}

	public void setCodEstper(Integer codEstper) {
		this.codEstper = codEstper;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expePers")
	public Set<SeguReso> getSeguResos() {
		return this.seguResos;
	}

	public void setSeguResos(Set<SeguReso> seguResos) {
		this.seguResos = seguResos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_CARGO", nullable = false, insertable = false, updatable = false)
	public Cargos getPersCargo() {
		return persCargo;
	}

	public void setPersCargo(Cargos persCargo) {
		this.persCargo = persCargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_FUNCIO", nullable = false, insertable = false, updatable = false)
	public Funciones getPersFunciones() {
		return persFunciones;
	}

	public void setPersFunciones(Funciones persFunciones) {
		this.persFunciones = persFunciones;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DESPAC", nullable = false, insertable = false, updatable = false)
	public Despachos getPersDespacho() {
		return persDespacho;
	}

	public void setPersDespacho(Despachos persDespacho) {
		this.persDespacho = persDespacho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DEPEND", nullable = false, insertable = false, updatable = false)
	public Dependen getPersDependecia() {
		return persDependecia;
	}

	public void setPersDependecia(Dependen persDependecia) {
		this.persDependecia = persDependecia;
	}
	
	

}
