package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExpeQuejId generated by hbm2java
 */
@Embeddable
public class ExpeQuejId implements java.io.Serializable {

	private int codDistritoOrigen;
	private int codIntexp;
	private int numQuejos;

	public ExpeQuejId() {
	}

	public ExpeQuejId(int codDistritoOrigen, int codIntexp, int numQuejos) {
		this.codDistritoOrigen = codDistritoOrigen;
		this.codIntexp = codIntexp;
		this.numQuejos = numQuejos;
	}

	@Column(name = "COD_DISTRITO_ORIGEN", nullable = false)
	public int getCodDistritoOrigen() {
		return this.codDistritoOrigen;
	}

	public void setCodDistritoOrigen(int codDistritoOrigen) {
		this.codDistritoOrigen = codDistritoOrigen;
	}

	@Column(name = "COD_INTEXP", nullable = false)
	public int getCodIntexp() {
		return this.codIntexp;
	}

	public void setCodIntexp(int codIntexp) {
		this.codIntexp = codIntexp;
	}

	@Column(name = "NUM_QUEJOS", nullable = false)
	public int getNumQuejos() {
		return this.numQuejos;
	}

	public void setNumQuejos(int numQuejos) {
		this.numQuejos = numQuejos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExpeQuejId))
			return false;
		ExpeQuejId castOther = (ExpeQuejId) other;

		return (this.getCodDistritoOrigen() == castOther.getCodDistritoOrigen())
				&& (this.getCodIntexp() == castOther.getCodIntexp())
				&& (this.getNumQuejos() == castOther.getNumQuejos());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodDistritoOrigen();
		result = 37 * result + this.getCodIntexp();
		result = 37 * result + this.getNumQuejos();
		return result;
	}

}
