package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExpeQuej generated by hbm2java
 */
@Entity
@Table(name = "EXPE_QUEJ", schema = "OC_OCMA")
public class ExpeQuej implements java.io.Serializable {

	private ExpeQuejId id;
	private ExpeMast expeMast;
	private ExpeDque expeDque;

	public ExpeQuej() {
	}

	public ExpeQuej(ExpeQuejId id, ExpeMast expeMast, ExpeDque expeDque) {
		this.id = id;
		this.expeMast = expeMast;
		this.expeDque = expeDque;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codDistritoOrigen", column = @Column(name = "COD_DISTRITO_ORIGEN", nullable = false)),
			@AttributeOverride(name = "codIntexp", column = @Column(name = "COD_INTEXP", nullable = false)),
			@AttributeOverride(name = "numQuejos", column = @Column(name = "NUM_QUEJOS", nullable = false)) })
	public ExpeQuejId getId() {
		return this.id;
	}

	public void setId(ExpeQuejId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_DISTRITO_ORIGEN", referencedColumnName = "COD_DISTRITO_ORIGEN", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "COD_INTEXP", referencedColumnName = "COD_INTEXP", nullable = false, insertable = false, updatable = false) })
	public ExpeMast getExpeMast() {
		return this.expeMast;
	}

	public void setExpeMast(ExpeMast expeMast) {
		this.expeMast = expeMast;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_QUEJOS", nullable = false)
	public ExpeDque getExpeDque() {
		return this.expeDque;
	}

	public void setExpeDque(ExpeDque expeDque) {
		this.expeDque = expeDque;
	}

}
