package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExpeTipo generated by hbm2java
 */
@Entity
@Table(name = "EXPE_TIPO", schema = "OC_OCMA")
public class ExpeTipo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codTipexp;
	private String desTipexp;
	private String desAbrevi;
	private Integer flaEstado;
	private Character flaVisita;
	private Character flaClasifi;
	private Set<ExpeMast> expeMasts = new HashSet<ExpeMast>(0);
	private Set<Socmast> socmastexpetipo = new HashSet<Socmast>(0);

	public ExpeTipo() {
	}

	public ExpeTipo(int codTipexp) {
		this.codTipexp = codTipexp;
	}

	public ExpeTipo(int codTipexp, String desTipexp, String desAbrevi,
			Integer flaEstado, Character flaVisita, Character flaClasifi,
			Set<ExpeMast> expeMasts) {
		this.codTipexp = codTipexp;
		this.desTipexp = desTipexp;
		this.desAbrevi = desAbrevi;
		this.flaEstado = flaEstado;
		this.flaVisita = flaVisita;
		this.flaClasifi = flaClasifi;
		this.expeMasts = expeMasts;
	}

	@Id
	@Column(name = "COD_TIPEXP", nullable = false)
	public int getCodTipexp() {
		return this.codTipexp;
	}

	public void setCodTipexp(int codTipexp) {
		this.codTipexp = codTipexp;
	}

	@Column(name = "DES_TIPEXP", length = 25)
	public String getDesTipexp() {
		return this.desTipexp;
	}

	public void setDesTipexp(String desTipexp) {
		this.desTipexp = desTipexp;
	}

	@Column(name = "DES_ABREVI", length = 2)
	public String getDesAbrevi() {
		return this.desAbrevi;
	}

	public void setDesAbrevi(String desAbrevi) {
		this.desAbrevi = desAbrevi;
	}

	@Column(name = "FLA_ESTADO")
	public Integer getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Integer flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "FLA_VISITA", length = 1)
	public Character getFlaVisita() {
		return this.flaVisita;
	}

	public void setFlaVisita(Character flaVisita) {
		this.flaVisita = flaVisita;
	}

	@Column(name = "FLA_CLASIFI", length = 1)
	public Character getFlaClasifi() {
		return this.flaClasifi;
	}

	public void setFlaClasifi(Character flaClasifi) {
		this.flaClasifi = flaClasifi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expeTipo")
	public Set<ExpeMast> getExpeMasts() {
		return this.expeMasts;
	}

	public void setExpeMasts(Set<ExpeMast> expeMasts) {
		this.expeMasts = expeMasts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socmastexpetipo")
	public Set<Socmast> getSocmastexpetipo() {
		return this.socmastexpetipo;
	}

	public void setSocmastexpetipo(Set<Socmast> socmastexpetipo) {
		this.socmastexpetipo = socmastexpetipo;
	}


}
