package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExpePersId generated by hbm2java
 */
@Embeddable
public class ExpePersId implements java.io.Serializable {

	private int codDistritoOrigen;
	private int codIntexp;
	private int codIntper;

	public ExpePersId() {
	}

	public ExpePersId(int codDistritoOrigen, int codIntexp, int codIntper) {
		this.codDistritoOrigen = codDistritoOrigen;
		this.codIntexp = codIntexp;
		this.codIntper = codIntper;
	}

	@Column(name = "COD_DISTRITO_ORIGEN", nullable = false)
	public int getCodDistritoOrigen() {
		return this.codDistritoOrigen;
	}

	public void setCodDistritoOrigen(int codDistritoOrigen) {
		this.codDistritoOrigen = codDistritoOrigen;
	}

	@Column(name = "COD_INTEXP", nullable = false)
	public int getCodIntexp() {
		return this.codIntexp;
	}

	public void setCodIntexp(int codIntexp) {
		this.codIntexp = codIntexp;
	}

	@Column(name = "COD_INTPER", nullable = false)
	public int getCodIntper() {
		return this.codIntper;
	}

	public void setCodIntper(int codIntper) {
		this.codIntper = codIntper;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExpePersId))
			return false;
		ExpePersId castOther = (ExpePersId) other;

		return (this.getCodDistritoOrigen() == castOther.getCodDistritoOrigen())
				&& (this.getCodIntexp() == castOther.getCodIntexp())
				&& (this.getCodIntper() == castOther.getCodIntper());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodDistritoOrigen();
		result = 37 * result + this.getCodIntexp();
		result = 37 * result + this.getCodIntper();
		return result;
	}

}
