package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ExpeMast generated by hbm2java
 */
@Entity
@Table(name = "EXPE_MAST", schema = "OC_OCMA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"COD_DISTRITO_ORIGEN", "COD_TIPEXP", "NUM_EXPEDI", "NUM_ANIOS" }))
public class ExpeMast implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ExpeMastId id;
	private DistriJud distriJudByCodDistri;
	private ExpeTipo expeTipo;
	private SeguEnca seguEnca;
	private DistriJud distriJudByCodDistritoOrigen;
	private String numExpedi;
	private String numAnios;
	private Integer numFojas;
	private Date fecRecepc;
	private String desObserv;
	private Date fecInicio;
	private Date fecEncargatura;
	private Date fecCreacion;
	private Date fecModificacion;
	private char indEstado;
	private Integer codEstado;
	private String codUsuario;
	private Integer codTipcaso;
	private Integer codPerAsig;
	private Integer codEtapapd;
	private Integer codEtapasubpd;
	private Date fecPrescrip;
	private Date fecRecPer;
	private Integer flagPresc;
	private Date fechaRsl;
	private Set<ExpeQuej> expeQuejs = new HashSet<ExpeQuej>(0);
	private Set<ExpePers> expePerses = new HashSet<ExpePers>(0);
	private Set<SeguMovi> seguMovimi = new HashSet<SeguMovi>(0);
	

	public ExpeMast() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codDistritoOrigen", column = @Column(name = "COD_DISTRITO_ORIGEN", nullable = false)),
			@AttributeOverride(name = "codIntexp", column = @Column(name = "COD_INTEXP", nullable = false)) })
	public ExpeMastId getId() {
		return this.id;
	}

	public void setId(ExpeMastId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DISTRI", nullable = false)
	public DistriJud getDistriJudByCodDistri() {
		return this.distriJudByCodDistri;
	}

	public void setDistriJudByCodDistri(DistriJud distriJudByCodDistri) {
		this.distriJudByCodDistri = distriJudByCodDistri;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_TIPEXP", nullable = false)
	public ExpeTipo getExpeTipo() {
		return this.expeTipo;
	}

	public void setExpeTipo(ExpeTipo expeTipo) {
		this.expeTipo = expeTipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ENCARG")
	public SeguEnca getSeguEnca() {
		return this.seguEnca;
	}

	public void setSeguEnca(SeguEnca seguEnca) {
		this.seguEnca = seguEnca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DISTRITO_ORIGEN", nullable = false, insertable = false, updatable = false)
	public DistriJud getDistriJudByCodDistritoOrigen() {
		return this.distriJudByCodDistritoOrigen;
	}

	public void setDistriJudByCodDistritoOrigen(
			DistriJud distriJudByCodDistritoOrigen) {
		this.distriJudByCodDistritoOrigen = distriJudByCodDistritoOrigen;
	}

	@Column(name = "NUM_EXPEDI", length = 5)
	public String getNumExpedi() {
		return this.numExpedi;
	}

	public void setNumExpedi(String numExpedi) {
		this.numExpedi = numExpedi;
	}

	@Column(name = "NUM_ANIOS", length = 4)
	public String getNumAnios() {
		return this.numAnios;
	}

	public void setNumAnios(String numAnios) {
		this.numAnios = numAnios;
	}

	@Column(name = "NUM_FOJAS", precision = 5, scale = 0)
	public Integer getNumFojas() {
		return this.numFojas;
	}

	public void setNumFojas(Integer numFojas) {
		this.numFojas = numFojas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_RECEPC", length = 10)
	public Date getFecRecepc() {
		return this.fecRecepc;
	}

	public void setFecRecepc(Date fecRecepc) {
		this.fecRecepc = fecRecepc;
	}

	@Column(name = "DES_OBSERV")
	public String getDesObserv() {
		return this.desObserv;
	}

	public void setDesObserv(String desObserv) {
		this.desObserv = desObserv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_INICIO", length = 10)
	public Date getFecInicio() {
		return this.fecInicio;
	}

	public void setFecInicio(Date fecInicio) {
		this.fecInicio = fecInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ENCARGATURA", nullable = false, length = 26)
	public Date getFecEncargatura() {
		return this.fecEncargatura;
	}

	public void setFecEncargatura(Date fecEncargatura) {
		this.fecEncargatura = fecEncargatura;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_CREACION", nullable = false, length = 26)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICACION", nullable = false, length = 26)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "IND_ESTADO", nullable = false, length = 1)
	public char getIndEstado() {
		return this.indEstado;
	}

	public void setIndEstado(char indEstado) {
		this.indEstado = indEstado;
	}

/**	@Column(name = "COD_ESTADO")
	public Integer getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(Integer codEstado) {
		this.codEstado = codEstado;
	}
**/
	@Column(name = "COD_USUARIO", length = 15)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "COD_TIPCASO")
	public Integer getCodTipcaso() {
		return this.codTipcaso;
	}

	public void setCodTipcaso(Integer codTipcaso) {
		this.codTipcaso = codTipcaso;
	}

	@Column(name = "COD_PER_ASIG")
	public Integer getCodPerAsig() {
		return this.codPerAsig;
	}

	public void setCodPerAsig(Integer codPerAsig) {
		this.codPerAsig = codPerAsig;
	}

	@Column(name = "COD_ETAPAPD")
	public Integer getCodEtapapd() {
		return this.codEtapapd;
	}

	public void setCodEtapapd(Integer codEtapapd) {
		this.codEtapapd = codEtapapd;
	}

	@Column(name = "COD_ETAPASUBPD")
	public Integer getCodEtapasubpd() {
		return this.codEtapasubpd;
	}

	public void setCodEtapasubpd(Integer codEtapasubpd) {
		this.codEtapasubpd = codEtapasubpd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_PRESCRIP", length = 10)
	public Date getFecPrescrip() {
		return this.fecPrescrip;
	}

	public void setFecPrescrip(Date fecPrescrip) {
		this.fecPrescrip = fecPrescrip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REC_PER", length = 26)
	public Date getFecRecPer() {
		return this.fecRecPer;
	}

	public void setFecRecPer(Date fecRecPer) {
		this.fecRecPer = fecRecPer;
	}

	@Column(name = "FLAG_PRESC")
	public Integer getFlagPresc() {
		return this.flagPresc;
	}

	public void setFlagPresc(Integer flagPresc) {
		this.flagPresc = flagPresc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_RSL", length = 10)
	public Date getFechaRsl() {
		return this.fechaRsl;
	}

	public void setFechaRsl(Date fechaRsl) {
		this.fechaRsl = fechaRsl;
	}
	
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "expeMast")
	public Set<ExpeQuej> getExpeQuejs() {
		return this.expeQuejs;
	}

	public void setExpeQuejs(Set<ExpeQuej> expeQuejs) {
		this.expeQuejs = expeQuejs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expeMast")
	public Set<ExpePers> getExpePerses() {
		return this.expePerses;
	}

	public void setExpePerses(Set<ExpePers> expePerses) {
		this.expePerses = expePerses;
	}

	@Column(name = "COD_ESTADO")
	public Integer getCodEstado() {
		return codEstado;
	}

	public void setCodEstado(Integer codEstado) {
		this.codEstado = codEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expeMast")
	public Set<SeguMovi> getSeguMovimi() {
		return seguMovimi;
	}

	public void setSeguMovimi(Set<SeguMovi> seguMovimi) {
		this.seguMovimi = seguMovimi;
	}	
	
	
	

}
