package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExpeDque generated by hbm2java
 */
@Entity
@Table(name = "EXPE_DQUE", schema = "OC_OCMA")
public class ExpeDque implements java.io.Serializable {

	private int codQuejos;
	private String desApelli;
	private Integer flaPerson;
	private String desDirecc;
	private String desNotas;
	private DocuIden docuIden;
	private int codDocide;
	private String numDocide;
	private String numTelefono;
	private String desEmail;
	private Character flgOrigenCreacion;
	private Set<ExpeQuej> expeQuejs = new HashSet<ExpeQuej>(0);

	public ExpeDque() {
	}

	public ExpeDque(int codQuejos, int codDocide) {
		this.codQuejos = codQuejos;
		this.codDocide = codDocide;
	}

	public ExpeDque(int codQuejos, String desApelli, Integer flaPerson,
			String desDirecc, String desNotas, int codDocide, String numDocide,
			String numTelefono, String desEmail, Character flgOrigenCreacion,
			Set<ExpeQuej> expeQuejs) {
		this.codQuejos = codQuejos;
		this.desApelli = desApelli;
		this.flaPerson = flaPerson;
		this.desDirecc = desDirecc;
		this.desNotas = desNotas;
		this.codDocide = codDocide;
		this.numDocide = numDocide;
		this.numTelefono = numTelefono;
		this.desEmail = desEmail;
		this.flgOrigenCreacion = flgOrigenCreacion;
		this.expeQuejs = expeQuejs;
	}

	@Id
	@Column(name = "COD_QUEJOS", nullable = false)
	public int getCodQuejos() {
		return this.codQuejos;
	}

	public void setCodQuejos(int codQuejos) {
		this.codQuejos = codQuejos;
	}

	@Column(name = "DES_APELLI", length = 50)
	public String getDesApelli() {
		return this.desApelli;
	}

	public void setDesApelli(String desApelli) {
		this.desApelli = desApelli;
	}

	@Column(name = "FLA_PERSON")
	public Integer getFlaPerson() {
		return this.flaPerson;
	}

	public void setFlaPerson(Integer flaPerson) {
		this.flaPerson = flaPerson;
	}

	@Column(name = "DES_DIRECC", length = 50)
	public String getDesDirecc() {
		return this.desDirecc;
	}

	public void setDesDirecc(String desDirecc) {
		this.desDirecc = desDirecc;
	}

	@Column(name = "DES_NOTAS", length = 100)
	public String getDesNotas() {
		return this.desNotas;
	}

	public void setDesNotas(String desNotas) {
		this.desNotas = desNotas;
	}

	@Column(name = "COD_DOCIDE", nullable = false)
	public int getCodDocide() {
		return this.codDocide;
	}

	public void setCodDocide(int codDocide) {
		this.codDocide = codDocide;
	}

	@Column(name = "NUM_DOCIDE", length = 14)
	public String getNumDocide() {
		return this.numDocide;
	}

	public void setNumDocide(String numDocide) {
		this.numDocide = numDocide;
	}

	@Column(name = "NUM_TELEFONO", length = 50)
	public String getNumTelefono() {
		return this.numTelefono;
	}

	public void setNumTelefono(String numTelefono) {
		this.numTelefono = numTelefono;
	}

	@Column(name = "DES_EMAIL", length = 50)
	public String getDesEmail() {
		return this.desEmail;
	}

	public void setDesEmail(String desEmail) {
		this.desEmail = desEmail;
	}

	@Column(name = "FLG_ORIGEN_CREACION", length = 1)
	public Character getFlgOrigenCreacion() {
		return this.flgOrigenCreacion;
	}

	public void setFlgOrigenCreacion(Character flgOrigenCreacion) {
		this.flgOrigenCreacion = flgOrigenCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expeDque")
	public Set<ExpeQuej> getExpeQuejs() {
		return this.expeQuejs;
	}

	public void setExpeQuejs(Set<ExpeQuej> expeQuejs) {
		this.expeQuejs = expeQuejs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DOCIDE", nullable = false, insertable = false, updatable = false)
	public DocuIden getDocuIden() {
		return docuIden;
	}

	public void setDocuIden(DocuIden docuIden) {
		this.docuIden = docuIden;
	}
	
	

}
