package pe.gob.ocma.entities.oc_ocma;

// Generated 01/08/2014 04:47:50 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PersEsta generated by hbm2java
 */
@Entity
@Table(name = "PERS_ESTA", schema = "OC_OCMA")
public class PersEsta implements java.io.Serializable {

	private int codEstper;
	private String desEstado;
	private String desAbrevi;
	private Integer flaEstado;

	public PersEsta() {
	}

	public PersEsta(int codEstper) {
		this.codEstper = codEstper;
	}

	public PersEsta(int codEstper, String desEstado, String desAbrevi,
			Integer flaEstado) {
		this.codEstper = codEstper;
		this.desEstado = desEstado;
		this.desAbrevi = desAbrevi;
		this.flaEstado = flaEstado;
	}

	@Id
	@Column(name = "COD_ESTPER", nullable = false)
	public int getCodEstper() {
		return this.codEstper;
	}

	public void setCodEstper(int codEstper) {
		this.codEstper = codEstper;
	}

	@Column(name = "DES_ESTADO", length = 25)
	public String getDesEstado() {
		return this.desEstado;
	}

	public void setDesEstado(String desEstado) {
		this.desEstado = desEstado;
	}

	@Column(name = "DES_ABREVI", length = 2)
	public String getDesAbrevi() {
		return this.desAbrevi;
	}

	public void setDesAbrevi(String desAbrevi) {
		this.desAbrevi = desAbrevi;
	}

	@Column(name = "FLA_ESTADO")
	public Integer getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Integer flaEstado) {
		this.flaEstado = flaEstado;
	}

}
