package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeguReso generated by hbm2java
 */
@Entity
@Table(name = "SEGU_RESO", schema = "OC_OCMA")
public class SeguReso implements java.io.Serializable {

	private SeguResoId id;
	private ExpePers expePers;
	private SeguEnca seguEnca;
	private ExpeEsta expeEsta;
	private int codResinf;
	private Date fecMovimi;
	private Integer numFojas;
	private String desNotas;
	private Character flaUltmov;
	private Integer codEstsan;
	private Integer codDistritoOrigenMp;
	private Integer codIntmp;
	private String codUsuarioCreacion;
	private Date fecCreacion;
	private String codUsuarioModificacion;
	private Date fecModificacion;
	private String nombreDoc;
	private String rutaDoc;

	public SeguReso() {
	}

	public SeguReso(SeguResoId id, ExpePers expePers, SeguEnca seguEnca,
			ExpeEsta expeEsta, int codResinf) {
		this.id = id;
		this.expePers = expePers;
		this.seguEnca = seguEnca;
		this.expeEsta = expeEsta;
		this.codResinf = codResinf;
	}

	public SeguReso(SeguResoId id, ExpePers expePers, SeguEnca seguEnca,
			ExpeEsta expeEsta, int codResinf, Date fecMovimi, Integer numFojas,
			String desNotas, Character flaUltmov, Integer codEstsan,
			Integer codDistritoOrigenMp, Integer codIntmp,
			String codUsuarioCreacion, Date fecCreacion,
			String codUsuarioModificacion, Date fecModificacion,
			String nombreDoc, String rutaDoc) {
		this.id = id;
		this.expePers = expePers;
		this.seguEnca = seguEnca;
		this.expeEsta = expeEsta;
		this.codResinf = codResinf;
		this.fecMovimi = fecMovimi;
		this.numFojas = numFojas;
		this.desNotas = desNotas;
		this.flaUltmov = flaUltmov;
		this.codEstsan = codEstsan;
		this.codDistritoOrigenMp = codDistritoOrigenMp;
		this.codIntmp = codIntmp;
		this.codUsuarioCreacion = codUsuarioCreacion;
		this.fecCreacion = fecCreacion;
		this.codUsuarioModificacion = codUsuarioModificacion;
		this.fecModificacion = fecModificacion;
		this.nombreDoc = nombreDoc;
		this.rutaDoc = rutaDoc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codDistritoOrigen", column = @Column(name = "COD_DISTRITO_ORIGEN", nullable = false)),
			@AttributeOverride(name = "codIntexp", column = @Column(name = "COD_INTEXP", nullable = false)),
			@AttributeOverride(name = "codIntper", column = @Column(name = "COD_INTPER", nullable = false)),
			@AttributeOverride(name = "numSecuen", column = @Column(name = "NUM_SECUEN", nullable = false)) })
	public SeguResoId getId() {
		return this.id;
	}

	public void setId(SeguResoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_DISTRITO_ORIGEN", referencedColumnName = "COD_DISTRITO_ORIGEN", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "COD_INTEXP", referencedColumnName = "COD_INTEXP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "COD_INTPER", referencedColumnName = "COD_INTPER", nullable = false, insertable = false, updatable = false) })
	public ExpePers getExpePers() {
		return this.expePers;
	}

	public void setExpePers(ExpePers expePers) {
		this.expePers = expePers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ENCARG", nullable = false)
	public SeguEnca getSeguEnca() {
		return this.seguEnca;
	}

	public void setSeguEnca(SeguEnca seguEnca) {
		this.seguEnca = seguEnca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ESTADO", nullable = false)
	public ExpeEsta getExpeEsta() {
		return this.expeEsta;
	}

	public void setExpeEsta(ExpeEsta expeEsta) {
		this.expeEsta = expeEsta;
	}

	@Column(name = "COD_RESINF", nullable = false)
	public int getCodResinf() {
		return this.codResinf;
	}

	public void setCodResinf(int codResinf) {
		this.codResinf = codResinf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_MOVIMI", length = 10)
	public Date getFecMovimi() {
		return this.fecMovimi;
	}

	public void setFecMovimi(Date fecMovimi) {
		this.fecMovimi = fecMovimi;
	}

	@Column(name = "NUM_FOJAS")
	public Integer getNumFojas() {
		return this.numFojas;
	}

	public void setNumFojas(Integer numFojas) {
		this.numFojas = numFojas;
	}

	@Column(name = "DES_NOTAS", length = 200)
	public String getDesNotas() {
		return this.desNotas;
	}

	public void setDesNotas(String desNotas) {
		this.desNotas = desNotas;
	}

	@Column(name = "FLA_ULTMOV", length = 1)
	public Character getFlaUltmov() {
		return this.flaUltmov;
	}

	public void setFlaUltmov(Character flaUltmov) {
		this.flaUltmov = flaUltmov;
	}

	@Column(name = "COD_ESTSAN")
	public Integer getCodEstsan() {
		return this.codEstsan;
	}

	public void setCodEstsan(Integer codEstsan) {
		this.codEstsan = codEstsan;
	}

	@Column(name = "COD_DISTRITO_ORIGEN_MP")
	public Integer getCodDistritoOrigenMp() {
		return this.codDistritoOrigenMp;
	}

	public void setCodDistritoOrigenMp(Integer codDistritoOrigenMp) {
		this.codDistritoOrigenMp = codDistritoOrigenMp;
	}

	@Column(name = "COD_INTMP")
	public Integer getCodIntmp() {
		return this.codIntmp;
	}

	public void setCodIntmp(Integer codIntmp) {
		this.codIntmp = codIntmp;
	}

	@Column(name = "COD_USUARIO_CREACION", length = 20)
	public String getCodUsuarioCreacion() {
		return this.codUsuarioCreacion;
	}

	public void setCodUsuarioCreacion(String codUsuarioCreacion) {
		this.codUsuarioCreacion = codUsuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_CREACION", length = 26)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Column(name = "COD_USUARIO_MODIFICACION", length = 20)
	public String getCodUsuarioModificacion() {
		return this.codUsuarioModificacion;
	}

	public void setCodUsuarioModificacion(String codUsuarioModificacion) {
		this.codUsuarioModificacion = codUsuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICACION", length = 26)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "NOMBRE_DOC", length = 50)
	public String getNombreDoc() {
		return this.nombreDoc;
	}

	public void setNombreDoc(String nombreDoc) {
		this.nombreDoc = nombreDoc;
	}

	@Column(name = "RUTA_DOC", length = 100)
	public String getRutaDoc() {
		return this.rutaDoc;
	}

	public void setRutaDoc(String rutaDoc) {
		this.rutaDoc = rutaDoc;
	}

}
