package pe.gob.ocma.entities.oc_ocma;

// Generated 22/11/2013 04:30:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SeguEnca generated by hbm2java
 */
@Entity
@Table(name = "SEGU_ENCA", schema = "OC_OCMA")
public class SeguEnca{

	private Integer codEncarg;
	private DistriJud distriJud;
	private String desEncarg;
	private String desAbrevi;
	private int codDespac;
	private Character flaGeneral;
	private Integer flaEstado;
	private String descripcion;
	private Set<SeguReso> seguResos = new HashSet<SeguReso>(0);
	private Set<ExpeMast> expeMasts = new HashSet<ExpeMast>(0);
	private Set<Socmovimiento> socencarg = new HashSet<Socmovimiento>(0);

	public SeguEnca() {
	}

	@Id
	@Column(name = "COD_ENCARG", nullable = false)
	public Integer getCodEncarg() {
		return this.codEncarg;
	}

	public void setCodEncarg(Integer codEncarg) {
		this.codEncarg = codEncarg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_DISTRI", nullable = false)
	public DistriJud getDistriJud() {
		return this.distriJud;
	}

	public void setDistriJud(DistriJud distriJud) {
		this.distriJud = distriJud;
	}

	@Column(name = "DES_ENCARG", length = 100)
	public String getDesEncarg() {
		return this.desEncarg;
	}

	public void setDesEncarg(String desEncarg) {
		this.desEncarg = desEncarg;
	}

	@Column(name = "DES_ABREVI", length = 6)
	public String getDesAbrevi() {
		return this.desAbrevi;
	}

	public void setDesAbrevi(String desAbrevi) {
		this.desAbrevi = desAbrevi;
	}

	@Column(name = "COD_DESPAC", nullable = false)
	public int getCodDespac() {
		return this.codDespac;
	}

	public void setCodDespac(int codDespac) {
		this.codDespac = codDespac;
	}

	@Column(name = "FLA_GENERAL", length = 1)
	public Character getFlaGeneral() {
		return this.flaGeneral;
	}

	public void setFlaGeneral(Character flaGeneral) {
		this.flaGeneral = flaGeneral;
	}

	@Column(name = "FLA_ESTADO")
	public Integer getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Integer flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seguEnca")
	public Set<SeguReso> getSeguResos() {
		return this.seguResos;
	}

	public void setSeguResos(Set<SeguReso> seguResos) {
		this.seguResos = seguResos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seguEnca")
	public Set<ExpeMast> getExpeMasts() {
		return this.expeMasts;
	}

	public void setExpeMasts(Set<ExpeMast> expeMasts) {
		this.expeMasts = expeMasts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socencarg")
	public Set<Socmovimiento> getSocencarg() {
		return socencarg;
	}

	public void setSocencarg(Set<Socmovimiento> socencarg) {
		this.socencarg = socencarg;
	}
	
	

}
