package pe.gob.ocma.entities.oc_ocma;

// Generated 21/08/2014 08:40:05 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaTipoMovDjId generated by hbm2java
 */
@Embeddable
public class TablaTipoMovDjId implements java.io.Serializable {

	private int codMov;
	private int codDj;

	public TablaTipoMovDjId() {
	}

	public TablaTipoMovDjId(int codMov, int codDj) {
		this.codMov = codMov;
		this.codDj = codDj;
	}

	@Column(name = "COD_MOV", nullable = false)
	public int getCodMov() {
		return this.codMov;
	}

	public void setCodMov(int codMov) {
		this.codMov = codMov;
	}

	@Column(name = "COD_DJ", nullable = false)
	public int getCodDj() {
		return this.codDj;
	}

	public void setCodDj(int codDj) {
		this.codDj = codDj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TablaTipoMovDjId))
			return false;
		TablaTipoMovDjId castOther = (TablaTipoMovDjId) other;

		return (this.getCodMov() == castOther.getCodMov())
				&& (this.getCodDj() == castOther.getCodDj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodMov();
		result = 37 * result + this.getCodDj();
		return result;
	}

}
