package pe.gob.ocma.entities.oc_ocma;

// Generated 07/07/2014 02:35:49 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TablaDjTipoObservacion generated by hbm2java
 */
@Entity
@Table(name = "TABLA_DJ_TIPO_OBSERVACION", schema = "OC_OCMA")
public class TablaDjTipoObservacion implements java.io.Serializable {

	private int codTipoObs;
	private String desTipoObs;
	private char flaEstado;

	public TablaDjTipoObservacion() {
	}

	public TablaDjTipoObservacion(int codTipoObs, String desTipoObs,
			char flaEstado) {
		this.codTipoObs = codTipoObs;
		this.desTipoObs = desTipoObs;
		this.flaEstado = flaEstado;
	}

	@Id
	@Column(name = "COD_TIPO_OBS", nullable = false)
	public int getCodTipoObs() {
		return this.codTipoObs;
	}

	public void setCodTipoObs(int codTipoObs) {
		this.codTipoObs = codTipoObs;
	}

	@Column(name = "DES_TIPO_OBS", nullable = false, length = 250)
	public String getDesTipoObs() {
		return this.desTipoObs;
	}

	public void setDesTipoObs(String desTipoObs) {
		this.desTipoObs = desTipoObs;
	}

	@Column(name = "FLA_ESTADO", nullable = false, length = 1)
	public char getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(char flaEstado) {
		this.flaEstado = flaEstado;
	}

}
