package pe.gob.ocma.entities.oc_ocma;

// Generated 07/07/2014 02:35:49 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaDjAyuda generated by hbm2java
 */
@Entity
@Table(name = "TABLA_DJ_AYUDA", schema = "OC_OCMA")
public class TablaDjAyuda implements java.io.Serializable {

	private TablaDjAyudaId id;
	private String desAyuda;
	private String desControl;

	public TablaDjAyuda() {
	}

	public TablaDjAyuda(TablaDjAyudaId id, String desAyuda, String desControl) {
		this.id = id;
		this.desAyuda = desAyuda;
		this.desControl = desControl;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codBloque", column = @Column(name = "COD_BLOQUE", nullable = false)),
			@AttributeOverride(name = "codAyuda", column = @Column(name = "COD_AYUDA", nullable = false)) })
	public TablaDjAyudaId getId() {
		return this.id;
	}

	public void setId(TablaDjAyudaId id) {
		this.id = id;
	}

	@Column(name = "DES_AYUDA", nullable = false)
	public String getDesAyuda() {
		return this.desAyuda;
	}

	public void setDesAyuda(String desAyuda) {
		this.desAyuda = desAyuda;
	}

	@Column(name = "DES_CONTROL", nullable = false, length = 250)
	public String getDesControl() {
		return this.desControl;
	}

	public void setDesControl(String desControl) {
		this.desControl = desControl;
	}

}
