package pe.gob.ocma.entities.oc_ocma;

// Generated 07/07/2014 02:35:49 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TablaDjEstado generated by hbm2java
 */
@Entity
@Table(name = "TABLA_DJ_ESTADO", schema = "OC_OCMA")
public class TablaDjEstado implements java.io.Serializable {
	
	
	private int codEstadoDj;
	private String desEstadoDj;
	private String desColorRgb;
	private Character flaEstado;
	private String desObservacionEstado;
	private String desIcono;
	private String desClaseColor;
	private Set<DjMaster> masterEstados = new HashSet<DjMaster>(0);
	

	public TablaDjEstado() {
	}

	/*
	public TablaDjEstado(int codEstadoDj, String desEstadoDj) {
		this.codEstadoDj = codEstadoDj;
		this.desEstadoDj = desEstadoDj;
	}

	public TablaDjEstado(int codEstadoDj, String desEstadoDj,
			String desColorRgb, Character flaEstado,
			String desObservacionEstado, String desIcono, String desClaseColor) {
		this.codEstadoDj = codEstadoDj;
		this.desEstadoDj = desEstadoDj;
		this.desColorRgb = desColorRgb;
		this.flaEstado = flaEstado;
		this.desObservacionEstado = desObservacionEstado;
		this.desIcono = desIcono;
		this.desClaseColor = desClaseColor;
	}*/

	@Id
	@Column(name = "COD_ESTADO_DJ", nullable = false)
	public int getCodEstadoDj() {
		return this.codEstadoDj;
	}

	public void setCodEstadoDj(int codEstadoDj) {
		this.codEstadoDj = codEstadoDj;
	}

	@Column(name = "DES_ESTADO_DJ", nullable = false, length = 150)
	public String getDesEstadoDj() {
		return this.desEstadoDj;
	}

	public void setDesEstadoDj(String desEstadoDj) {
		this.desEstadoDj = desEstadoDj;
	}

	@Column(name = "DES_COLOR_RGB", length = 50)
	public String getDesColorRgb() {
		return this.desColorRgb;
	}

	public void setDesColorRgb(String desColorRgb) {
		this.desColorRgb = desColorRgb;
	}

	@Column(name = "FLA_ESTADO", length = 1)
	public Character getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Character flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "DES_OBSERVACION_ESTADO")
	public String getDesObservacionEstado() {
		return this.desObservacionEstado;
	}

	public void setDesObservacionEstado(String desObservacionEstado) {
		this.desObservacionEstado = desObservacionEstado;
	}

	@Column(name = "DES_ICONO", length = 50)
	public String getDesIcono() {
		return this.desIcono;
	}

	public void setDesIcono(String desIcono) {
		this.desIcono = desIcono;
	}

	@Column(name = "DES_CLASE_COLOR", length = 100)
	public String getDesClaseColor() {
		return this.desClaseColor;
	}

	public void setDesClaseColor(String desClaseColor) {
		this.desClaseColor = desClaseColor;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterEstados")
	public Set<DjMaster> getMasterEstados() {
		return masterEstados;
	}
	
	public void setMasterEstados(Set<DjMaster> masterEstados) {
		this.masterEstados = masterEstados;
	}
	
	

}
