package pe.gob.ocma.entities.oc_ocma;

// Generated 07/07/2014 02:35:49 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaDjAyudaId generated by hbm2java
 */
@Embeddable
public class TablaDjAyudaId implements java.io.Serializable {

	private int codBloque;
	private int codAyuda;

	public TablaDjAyudaId() {
	}

	public TablaDjAyudaId(int codBloque, int codAyuda) {
		this.codBloque = codBloque;
		this.codAyuda = codAyuda;
	}

	@Column(name = "COD_BLOQUE", nullable = false)
	public int getCodBloque() {
		return this.codBloque;
	}

	public void setCodBloque(int codBloque) {
		this.codBloque = codBloque;
	}

	@Column(name = "COD_AYUDA", nullable = false)
	public int getCodAyuda() {
		return this.codAyuda;
	}

	public void setCodAyuda(int codAyuda) {
		this.codAyuda = codAyuda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TablaDjAyudaId))
			return false;
		TablaDjAyudaId castOther = (TablaDjAyudaId) other;

		return (this.getCodBloque() == castOther.getCodBloque())
				&& (this.getCodAyuda() == castOther.getCodAyuda());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodBloque();
		result = 37 * result + this.getCodAyuda();
		return result;
	}

}
