package pe.gob.ocma.entities.oc_ocma;

// Generated 21/08/2014 08:40:05 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TablaTipoMovDj generated by hbm2java
 */
@Entity
@Table(name = "TABLA_TIPO_MOV_DJ", schema = "OC_OCMA")
public class TablaTipoMovDj implements java.io.Serializable {

	private TablaTipoMovDjId id;
	private Character flaEstado;
	private String numDocumento;
	private String desObservacion;
	private String fecPresent;
	private Date fecMov;
	private char codTipoMov;
	private String codUsucre;
	private String codUsumod;
	private Integer annioReg;

	public TablaTipoMovDj() {
	}

	public TablaTipoMovDj(TablaTipoMovDjId id, Date fecMov, char codTipoMov) {
		this.id = id;
		this.fecMov = fecMov;
		this.codTipoMov = codTipoMov;
	}

	public TablaTipoMovDj(TablaTipoMovDjId id, Character flaEstado,
			String numDocumento, String desObservacion, String fecPresent,
			Date fecMov, char codTipoMov, String codUsucre, String codUsumod,
			Integer annioReg) {
		this.id = id;
		this.flaEstado = flaEstado;
		this.numDocumento = numDocumento;
		this.desObservacion = desObservacion;
		this.fecPresent = fecPresent;
		this.fecMov = fecMov;
		this.codTipoMov = codTipoMov;
		this.codUsucre = codUsucre;
		this.codUsumod = codUsumod;
		this.annioReg = annioReg;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codMov", column = @Column(name = "COD_MOV", nullable = false)),
			@AttributeOverride(name = "codDj", column = @Column(name = "COD_DJ", nullable = false)) })
	public TablaTipoMovDjId getId() {
		return this.id;
	}

	public void setId(TablaTipoMovDjId id) {
		this.id = id;
	}

	@Column(name = "FLA_ESTADO", length = 1)
	public Character getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Character flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "NUM_DOCUMENTO", length = 6)
	public String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	@Column(name = "DES_OBSERVACION", length = 4000)
	public String getDesObservacion() {
		return this.desObservacion;
	}

	public void setDesObservacion(String desObservacion) {
		this.desObservacion = desObservacion;
	}

	@Column(name = "FEC_PRESENT", length = 10)
	public String getFecPresent() {
		return this.fecPresent;
	}

	public void setFecPresent(String fecPresent) {
		this.fecPresent = fecPresent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_MOV", nullable = false, length = 10)
	public Date getFecMov() {
		return this.fecMov;
	}

	public void setFecMov(Date fecMov) {
		this.fecMov = fecMov;
	}

	@Column(name = "COD_TIPO_MOV", nullable = false, length = 1)
	public char getCodTipoMov() {
		return this.codTipoMov;
	}

	public void setCodTipoMov(char codTipoMov) {
		this.codTipoMov = codTipoMov;
	}

	@Column(name = "COD_USUCRE", length = 15)
	public String getCodUsucre() {
		return this.codUsucre;
	}

	public void setCodUsucre(String codUsucre) {
		this.codUsucre = codUsucre;
	}

	@Column(name = "COD_USUMOD", length = 15)
	public String getCodUsumod() {
		return this.codUsumod;
	}

	public void setCodUsumod(String codUsumod) {
		this.codUsumod = codUsumod;
	}

	@Column(name = "ANNIO_REG")
	public Integer getAnnioReg() {
		return this.annioReg;
	}

	public void setAnnioReg(Integer annioReg) {
		this.annioReg = annioReg;
	}

}
