package pe.gob.ocma.entities.ubigeojud;

// Generated 02/09/2013 10:37:52 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ujtcedjud generated by hbm2java
 */
@Entity
@Table(name = "UJTCEDJUD", schema = "UBIGEOJUD")
public class Ujtcedjud implements java.io.Serializable {

	private int codCedJud;
	private Ujtprojud ujtprojud;
	private String descripcion;
	private String direccion;
	private boolean habilitado;

	public Ujtcedjud() {
	}

	public Ujtcedjud(int codCedJud, Ujtprojud ujtprojud, String descripcion,
			String direccion, boolean habilitado) {
		this.codCedJud = codCedJud;
		this.ujtprojud = ujtprojud;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.habilitado = habilitado;
	}

	@Id
	@Column(name = "codCedJud", nullable = false)
	public int getCodCedJud() {
		return this.codCedJud;
	}

	public void setCodCedJud(int codCedJud) {
		this.codCedJud = codCedJud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codProJud", nullable = false)
	public Ujtprojud getUjtprojud() {
		return this.ujtprojud;
	}

	public void setUjtprojud(Ujtprojud ujtprojud) {
		this.ujtprojud = ujtprojud;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "direccion", nullable = false, length = 150)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
