package pe.gob.ocma.entities.ubigeojud;

// Generated 02/09/2013 10:37:52 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ujtdisjud generated by hbm2java
 */
@Entity
@Table(name = "UJTDISJUD", schema = "UBIGEOJUD", uniqueConstraints = @UniqueConstraint(columnNames = "descripcion"))
public class Ujtdisjud implements java.io.Serializable {

	private short codDisJud;
	private String descripcion;
	private String direccion;
	private boolean habilitado;
	private Set<Ujtprojud> ujtprojuds = new HashSet<Ujtprojud>(0);

	public Ujtdisjud() {
	}

	public Ujtdisjud(short codDisJud, String descripcion, String direccion,
			boolean habilitado) {
		this.codDisJud = codDisJud;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.habilitado = habilitado;
	}

	public Ujtdisjud(short codDisJud, String descripcion, String direccion,
			boolean habilitado, Set<Ujtprojud> ujtprojuds) {
		this.codDisJud = codDisJud;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.habilitado = habilitado;
		this.ujtprojuds = ujtprojuds;
	}

	@Id
	@Column(name = "codDisJud", nullable = false)
	public short getCodDisJud() {
		return this.codDisJud;
	}

	public void setCodDisJud(short codDisJud) {
		this.codDisJud = codDisJud;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "direccion", nullable = false, length = 150)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ujtdisjud")
	public Set<Ujtprojud> getUjtprojuds() {
		return this.ujtprojuds;
	}

	public void setUjtprojuds(Set<Ujtprojud> ujtprojuds) {
		this.ujtprojuds = ujtprojuds;
	}

}
