package pe.gob.ocma.entities.ubigeojud;

// Generated 02/09/2013 10:37:52 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ujtprojud generated by hbm2java
 */
@Entity
@Table(name = "UJTPROJUD", schema = "UBIGEOJUD")
public class Ujtprojud implements java.io.Serializable {

	private short codProJud;
	private Ujtdisjud ujtdisjud;
	private String descripcion;
	private boolean habilitado;
	private Set<Ujtcedjud> ujtcedjuds = new HashSet<Ujtcedjud>(0);

	public Ujtprojud() {
	}

	public Ujtprojud(short codProJud, Ujtdisjud ujtdisjud, String descripcion,
			boolean habilitado) {
		this.codProJud = codProJud;
		this.ujtdisjud = ujtdisjud;
		this.descripcion = descripcion;
		this.habilitado = habilitado;
	}

	public Ujtprojud(short codProJud, Ujtdisjud ujtdisjud, String descripcion,
			boolean habilitado, Set<Ujtcedjud> ujtcedjuds) {
		this.codProJud = codProJud;
		this.ujtdisjud = ujtdisjud;
		this.descripcion = descripcion;
		this.habilitado = habilitado;
		this.ujtcedjuds = ujtcedjuds;
	}

	@Id
	@Column(name = "codProJud", nullable = false)
	public short getCodProJud() {
		return this.codProJud;
	}

	public void setCodProJud(short codProJud) {
		this.codProJud = codProJud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codDisJud", nullable = false)
	public Ujtdisjud getUjtdisjud() {
		return this.ujtdisjud;
	}

	public void setUjtdisjud(Ujtdisjud ujtdisjud) {
		this.ujtdisjud = ujtdisjud;
	}

	@Column(name = "descripcion", nullable = false, length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ujtprojud")
	public Set<Ujtcedjud> getUjtcedjuds() {
		return this.ujtcedjuds;
	}

	public void setUjtcedjuds(Set<Ujtcedjud> ujtcedjuds) {
		this.ujtcedjuds = ujtcedjuds;
	}

}
