package pe.gob.ocma.entities.persona;

// Generated 02/09/2013 10:33:21 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Petdocperson generated by hbm2java
 */
@Entity
@Table(name = "PETDOCPERSON", schema = "PERSONA")
public class Petdocperson implements java.io.Serializable {

	private long codDocPerson;
	private Petpersona petpersona;
	private Pettipdoc pettipdoc;
	private String numDocumento;
	private boolean habilitado;

	public Petdocperson() {
	}

	public Petdocperson(long codDocPerson, Petpersona petpersona,
			Pettipdoc pettipdoc, String numDocumento, boolean habilitado) {
		this.codDocPerson = codDocPerson;
		this.petpersona = petpersona;
		this.pettipdoc = pettipdoc;
		this.numDocumento = numDocumento;
		this.habilitado = habilitado;
	}

	@Id
	@Column(name = "codDocPerson", nullable = false)
	public long getCodDocPerson() {
		return this.codDocPerson;
	}

	public void setCodDocPerson(long codDocPerson) {
		this.codDocPerson = codDocPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codPersona", nullable = false)
	public Petpersona getPetpersona() {
		return this.petpersona;
	}

	public void setPetpersona(Petpersona petpersona) {
		this.petpersona = petpersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codTipDoc", nullable = false)
	public Pettipdoc getPettipdoc() {
		return this.pettipdoc;
	}

	public void setPettipdoc(Pettipdoc pettipdoc) {
		this.pettipdoc = pettipdoc;
	}

	@Column(name = "numDocumento", nullable = false, length = 20)
	public String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
