package pe.gob.ocma.entities.persona;

// Generated 02/09/2013 10:33:21 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Petpersona generated by hbm2java
 */
@Entity
@Table(name = "PETPERSONA", schema = "PERSONA")
public class Petpersona implements java.io.Serializable {

	private long codPersona;
	private short codTabMae;
	private String nombre;
	private Pettipdoc pettipdoc;
	private String numDocumento;
	private String direccion;
	private String telefono;
	private String correo;
	private String nota;
	private Petpernatu petpernatu;
	private Petperjuri petperjuri;
	private Set<Petdocperson> petdocpersons = new HashSet<Petdocperson>(0);

	public Petpersona() {
		petpernatu = new Petpernatu();
		petperjuri = new Petperjuri();
		pettipdoc = new Pettipdoc();
	}

	public Petpersona(long codPersona, short codTabMae, String nombre,
			String direccion, String telefono, String correo) {
		this.codPersona = codPersona;
		this.codTabMae = codTabMae;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "petpersona")
	public Petpernatu getPetpernatu() {
		return petpernatu;
	}

	public void setPetpernatu(Petpernatu petpernatu) {
		this.petpernatu = petpernatu;
	}

	@Id
	@Column(name = "codPersona", nullable = false)
	public long getCodPersona() {
		return this.codPersona;
	}

	public void setCodPersona(long codPersona) {
		this.codPersona = codPersona;
	}

	@Column(name = "codTabMae", nullable = false)
	public short getCodTabMae() {
		return this.codTabMae;
	}

	public void setCodTabMae(short codTabMae) {
		this.codTabMae = codTabMae;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codTipDoc", nullable = false)
	public Pettipdoc getPettipdoc() {
		return pettipdoc;
	}

	public void setPettipdoc(Pettipdoc pettipdoc) {
		this.pettipdoc = pettipdoc;
	}

	@Column(name = "numDocumento", nullable = false, length = 20)
	public String getNumDocumento() {
		return numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = true, length = 150)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", nullable = false, length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correo", nullable = false, length = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "nota")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@OneToOne(fetch = FetchType.LAZY,mappedBy="petpersona")
	public Petperjuri getPetperjuri() {
		return this.petperjuri;
	}

	public void setPetperjuri(Petperjuri petperjuri) {
		this.petperjuri = petperjuri;
	}	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petpersona")
	public Set<Petdocperson> getPetdocpersons() {
		return this.petdocpersons;
	}

	public void setPetdocpersons(Set<Petdocperson> petdocpersons) {
		this.petdocpersons = petdocpersons;
	}

}
