package pe.gob.ocma.entities.persona;

// Generated 02/09/2013 10:33:21 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.gob.ocma.entities.seguridad.Setusuario;

/**
 * Petpernatu generated by hbm2java
 */
@Entity
@Table(name = "PETPERNATU", schema = "PERSONA")
public class Petpernatu implements java.io.Serializable {

	private long codPerNatu;
	private Petpersona petpersona;
	private Setusuario setusuario;
	private String apellido;
	private String nombre;
	private short codTabMae;
	private Date fecNacimien;
	private String telMovil;

	public Petpernatu() {				
	}

	public Petpernatu(long codPerNatu, Petpersona petpersona, String apellido,
			String nombre, short codTabMae) {
		this.codPerNatu = codPerNatu;
		this.petpersona = petpersona;
		this.apellido = apellido;
		this.nombre = nombre;
		this.codTabMae = codTabMae;
	}

	public Petpernatu(long codPerNatu, Petpersona petpersona, String apellido,
			String nombre, short codTabMae, Date fecNacimien, String telMovil) {
		this.codPerNatu = codPerNatu;
		this.petpersona = petpersona;
		this.apellido = apellido;
		this.nombre = nombre;
		this.codTabMae = codTabMae;
		this.fecNacimien = fecNacimien;
		this.telMovil = telMovil;
	}

	@Id
	@Column(name = "codPerNatu", nullable = false)
	public long getCodPerNatu() {
		return this.codPerNatu;
	}

	public void setCodPerNatu(long codPerNatu) {
		this.codPerNatu = codPerNatu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codPersona", nullable = false)
	public Petpersona getPetpersona() {
		return this.petpersona;
	}

	public void setPetpersona(Petpersona petpersona) {
		this.petpersona = petpersona;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "petpernatu")
	public Setusuario getSetusuario() {
		return setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "apellido", nullable = false, length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codTabMae", nullable = false)
	public short getCodTabMae() {
		return this.codTabMae;
	}

	public void setCodTabMae(short codTabMae) {
		this.codTabMae = codTabMae;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecNacimien", length = 10)
	public Date getFecNacimien() {
		return this.fecNacimien;
	}

	public void setFecNacimien(Date fecNacimien) {
		this.fecNacimien = fecNacimien;
	}

	@Column(name = "telMovil", length = 12)
	public String getTelMovil() {
		return this.telMovil;
	}

	public void setTelMovil(String telMovil) {
		this.telMovil = telMovil;
	}

}
