package pe.gob.ocma.entities.persona;

// Generated 02/09/2013 10:33:21 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Petperjuri generated by hbm2java
 */
@Entity
@Table(name = "PETPERJURI", schema = "PERSONA")
public class Petperjuri implements java.io.Serializable {

	private long codPerJuri;
	private Petpersona petpersona;
	private String nombre;
	private String nomRepresen;
	private String numFax;
	private String sitioWeb;

	public Petperjuri() {
	}

	public Petperjuri(long codPerJuri, Petpersona petpersona, String nombre,
			String nomRepresen, String numFax, String sitioWeb) {
		this.codPerJuri = codPerJuri;
		this.petpersona = petpersona;
		this.nombre = nombre;
		this.nomRepresen = nomRepresen;
		this.numFax = numFax;
		this.sitioWeb = sitioWeb;
	}

	@Id
	@Column(name = "codPerJuri", nullable = false)
	public long getCodPerJuri() {
		return this.codPerJuri;
	}

	public void setCodPerJuri(long codPerJuri) {
		this.codPerJuri = codPerJuri;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codPersona", nullable = false)
	public Petpersona getPetpersona() {
		return this.petpersona;
	}

	public void setPetpersona(Petpersona petpersona) {
		this.petpersona = petpersona;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "nomRepresen", nullable = false, length = 100)
	public String getNomRepresen() {
		return this.nomRepresen;
	}

	public void setNomRepresen(String nomRepresen) {
		this.nomRepresen = nomRepresen;
	}

	@Column(name = "numFax", nullable = false, length = 16)
	public String getNumFax() {
		return this.numFax;
	}

	public void setNumFax(String numFax) {
		this.numFax = numFax;
	}

	@Column(name = "sitioWeb", nullable = false, length = 150)
	public String getSitioWeb() {
		return this.sitioWeb;
	}

	public void setSitioWeb(String sitioWeb) {
		this.sitioWeb = sitioWeb;
	}

}
