package pe.gob.ocma.entities.persona;

// Generated 02/09/2013 10:33:21 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import pe.gob.ocma.entities.generico.Gettabmae;

/**
 * Pettipdoc generated by hbm2java
 */
@Entity
@Table(name = "PETTIPDOC", schema = "PERSONA", uniqueConstraints = {
		@UniqueConstraint(columnNames = "desAbrev"),
		@UniqueConstraint(columnNames = "descripcion") })
public class Pettipdoc implements java.io.Serializable {

	private short codTipDoc;
	private Gettabmae gettabmae;
	private short codTabMae;
	private String desAbrev;
	private String descripcion;
	private short orden;
	private boolean porDefecto;
	private boolean habilitado;
	private Set<Petdocperson> petdocpersons = new HashSet<Petdocperson>(0);

	public Pettipdoc() {
	}

	public Pettipdoc(short codTipDoc, short codTabMae, String desAbrev,
			String descripcion, short orden, boolean porDefecto,
			boolean habilitado) {
		this.codTipDoc = codTipDoc;
		this.codTabMae = codTabMae;
		this.desAbrev = desAbrev;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.habilitado = habilitado;
	}

	public Pettipdoc(short codTipDoc, short codTabMae, String desAbrev,
			String descripcion, short orden, boolean porDefecto,
			boolean habilitado, Set<Petdocperson> petdocpersons) {
		this.codTipDoc = codTipDoc;
		this.codTabMae = codTabMae;
		this.desAbrev = desAbrev;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.habilitado = habilitado;
		this.petdocpersons = petdocpersons;
	}

	@Id
	@Column(name = "codTipDoc", nullable = false)
	public short getCodTipDoc() {
		return this.codTipDoc;
	}

	public void setCodTipDoc(short codTipDoc) {
		this.codTipDoc = codTipDoc;
	}

	@ManyToOne
	@JoinColumn(name = "codTabMae", nullable = false, insertable = false, updatable = false)
	public Gettabmae getGettabmae() {
		return gettabmae;
	}

	public void setGettabmae(Gettabmae gettabmae) {
		this.gettabmae = gettabmae;
	}

	@Column(name = "codTabMae", nullable = false)
	public short getCodTabMae() {
		return this.codTabMae;
	}

	public void setCodTabMae(short codTabMae) {
		this.codTabMae = codTabMae;
	}

	@Column(name = "desAbrev", unique = true, nullable = false, length = 10)
	public String getDesAbrev() {
		return this.desAbrev;
	}

	public void setDesAbrev(String desAbrev) {
		this.desAbrev = desAbrev;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "porDefecto", nullable = false)
	public boolean isPorDefecto() {
		return this.porDefecto;
	}

	public void setPorDefecto(boolean porDefecto) {
		this.porDefecto = porDefecto;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pettipdoc")
	public Set<Petdocperson> getPetdocpersons() {
		return this.petdocpersons;
	}

	public void setPetdocpersons(Set<Petdocperson> petdocpersons) {
		this.petdocpersons = petdocpersons;
	}

}
