package pe.gob.ocma.entities.web_ocma;

// Generated 29/09/2014 11:43:47 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Afp generated by hbm2java
 */
@Entity
@Table(name = "AFP", schema = "WEB_OCMA")
public class Afp implements java.io.Serializable {

	private int codAfp;
	private String desAfp;
	private char flaEstado;

	public Afp() {
	}

	public Afp(int codAfp, String desAfp, char flaEstado) {
		this.codAfp = codAfp;
		this.desAfp = desAfp;
		this.flaEstado = flaEstado;
	}

	@Id
	@Column(name = "COD_AFP", nullable = false)
	public int getCodAfp() {
		return this.codAfp;
	}

	public void setCodAfp(int codAfp) {
		this.codAfp = codAfp;
	}

	@Column(name = "DES_AFP", nullable = false, length = 75)
	public String getDesAfp() {
		return this.desAfp;
	}

	public void setDesAfp(String desAfp) {
		this.desAfp = desAfp;
	}

	@Column(name = "FLA_ESTADO", nullable = false, length = 1)
	public char getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(char flaEstado) {
		this.flaEstado = flaEstado;
	}

}
