package pe.gob.ocma.entities.web_ocma;

// Generated 30/07/2014 09:37:22 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import pe.gob.ocma.entities.oc_ocma.DjMaster;

/**
 * DistritoJudicial generated by hbm2java
 */
@Entity
@Table(name = "DISTRITO_JUDICIAL", schema = "WEB_OCMA")
public class DistritoJudicial implements java.io.Serializable {
	
	
	private int codDistritojudicial;
	private String desDistritojudicial;
	private String desDireccion;
	private char flaEstado;
	private String desCoordMapa;
	private String desRutaMapaProv;
	private String desRutaImgFondo;
	private String desRutaFlashFotos;
	private String desHistoria;
	private String desCapital;
	private Set<DjMaster> djmasterDist = new HashSet<DjMaster>(0);

	public DistritoJudicial() {
	}

	/*
	public DistritoJudicial(int codDistritojudicial,
			String desDistritojudicial, char flaEstado) {
		this.codDistritojudicial = codDistritojudicial;
		this.desDistritojudicial = desDistritojudicial;
		this.flaEstado = flaEstado;
	}

	public DistritoJudicial(int codDistritojudicial,
			String desDistritojudicial, String desDireccion, char flaEstado,
			String desCoordMapa, String desRutaMapaProv,
			String desRutaImgFondo, String desRutaFlashFotos,
			String desHistoria, String desCapital) {
		this.codDistritojudicial = codDistritojudicial;
		this.desDistritojudicial = desDistritojudicial;
		this.desDireccion = desDireccion;
		this.flaEstado = flaEstado;
		this.desCoordMapa = desCoordMapa;
		this.desRutaMapaProv = desRutaMapaProv;
		this.desRutaImgFondo = desRutaImgFondo;
		this.desRutaFlashFotos = desRutaFlashFotos;
		this.desHistoria = desHistoria;
		this.desCapital = desCapital;
	}*/

	@Id
	@Column(name = "COD_DISTRITOJUDICIAL", nullable = false)
	public int getCodDistritojudicial() {
		return this.codDistritojudicial;
	}

	public void setCodDistritojudicial(int codDistritojudicial) {
		this.codDistritojudicial = codDistritojudicial;
	}

	@Column(name = "DES_DISTRITOJUDICIAL", nullable = false, length = 80)
	public String getDesDistritojudicial() {
		return this.desDistritojudicial;
	}

	public void setDesDistritojudicial(String desDistritojudicial) {
		this.desDistritojudicial = desDistritojudicial;
	}

	@Column(name = "DES_DIRECCION", length = 100)
	public String getDesDireccion() {
		return this.desDireccion;
	}

	public void setDesDireccion(String desDireccion) {
		this.desDireccion = desDireccion;
	}

	@Column(name = "FLA_ESTADO", nullable = false, length = 1)
	public char getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(char flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Column(name = "DES_COORD_MAPA", length = 5000)
	public String getDesCoordMapa() {
		return this.desCoordMapa;
	}

	public void setDesCoordMapa(String desCoordMapa) {
		this.desCoordMapa = desCoordMapa;
	}

	@Column(name = "DES_RUTA_MAPA_PROV", length = 250)
	public String getDesRutaMapaProv() {
		return this.desRutaMapaProv;
	}

	public void setDesRutaMapaProv(String desRutaMapaProv) {
		this.desRutaMapaProv = desRutaMapaProv;
	}

	@Column(name = "DES_RUTA_IMG_FONDO", length = 250)
	public String getDesRutaImgFondo() {
		return this.desRutaImgFondo;
	}

	public void setDesRutaImgFondo(String desRutaImgFondo) {
		this.desRutaImgFondo = desRutaImgFondo;
	}

	@Column(name = "DES_RUTA_FLASH_FOTOS", length = 250)
	public String getDesRutaFlashFotos() {
		return this.desRutaFlashFotos;
	}

	public void setDesRutaFlashFotos(String desRutaFlashFotos) {
		this.desRutaFlashFotos = desRutaFlashFotos;
	}

	@Column(name = "DES_HISTORIA")
	public String getDesHistoria() {
		return this.desHistoria;
	}

	public void setDesHistoria(String desHistoria) {
		this.desHistoria = desHistoria;
	}

	@Column(name = "DES_CAPITAL")
	public String getDesCapital() {
		return this.desCapital;
	}

	public void setDesCapital(String desCapital) {
		this.desCapital = desCapital;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "djmasterDist")
	public Set<DjMaster> getDjmasterDist() {
		return djmasterDist;
	}
	
	public void setDjmasterDist(Set<DjMaster> djmasterDist) {
		this.djmasterDist = djmasterDist;
	}

}
