package pe.gob.ocma.entities.web_ocma;

// Generated 19/09/2014 11:18:41 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GrupoModulo generated by hbm2java
 */
@Entity
@Table(name = "GRUPO_MODULO", schema = "WEB_OCMA")
public class GrupoModulo implements java.io.Serializable {

	private GrupoModuloId id;

	public GrupoModulo() {
	}

	public GrupoModulo(GrupoModuloId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codGrupo", column = @Column(name = "COD_GRUPO", nullable = false, length = 10)),
			@AttributeOverride(name = "codModulo", column = @Column(name = "COD_MODULO", nullable = false)),
			@AttributeOverride(name = "codPrivilegio", column = @Column(name = "COD_PRIVILEGIO", nullable = false)) })
	public GrupoModuloId getId() {
		return this.id;
	}

	public void setId(GrupoModuloId id) {
		this.id = id;
	}

}
