package pe.gob.ocma.entities.web_ocma;

// Generated 19/09/2014 11:18:41 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IngresoAuditoriaId generated by hbm2java
 */
@Embeddable
public class IngresoAuditoriaId implements java.io.Serializable {

	private String codUsuario;
	private int codAuditoria;

	public IngresoAuditoriaId() {
	}

	public IngresoAuditoriaId(String codUsuario, int codAuditoria) {
		this.codUsuario = codUsuario;
		this.codAuditoria = codAuditoria;
	}

	@Column(name = "COD_USUARIO", nullable = false, length = 20)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "COD_AUDITORIA", nullable = false)
	public int getCodAuditoria() {
		return this.codAuditoria;
	}

	public void setCodAuditoria(int codAuditoria) {
		this.codAuditoria = codAuditoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IngresoAuditoriaId))
			return false;
		IngresoAuditoriaId castOther = (IngresoAuditoriaId) other;

		return ((this.getCodUsuario() == castOther.getCodUsuario()) || (this
				.getCodUsuario() != null && castOther.getCodUsuario() != null && this
				.getCodUsuario().equals(castOther.getCodUsuario())))
				&& (this.getCodAuditoria() == castOther.getCodAuditoria());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodUsuario() == null ? 0 : this.getCodUsuario()
						.hashCode());
		result = 37 * result + this.getCodAuditoria();
		return result;
	}

}
