package pe.gob.ocma.entities.web_ocma;

// Generated 04/11/2014 03:54:12 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonalAcademicaId generated by hbm2java
 */
@Embeddable
public class PersonalAcademicaId implements java.io.Serializable {

	private int codPersonal;
	private int codAcademica;
	private int codIntacademica;

	public PersonalAcademicaId() {
	}

	public PersonalAcademicaId(int codPersonal, int codAcademica,
			int codIntacademica) {
		this.codPersonal = codPersonal;
		this.codAcademica = codAcademica;
		this.codIntacademica = codIntacademica;
	}

	@Column(name = "COD_PERSONAL", nullable = false)
	public int getCodPersonal() {
		return this.codPersonal;
	}

	public void setCodPersonal(int codPersonal) {
		this.codPersonal = codPersonal;
	}

	@Column(name = "COD_ACADEMICA", nullable = false)
	public int getCodAcademica() {
		return this.codAcademica;
	}

	public void setCodAcademica(int codAcademica) {
		this.codAcademica = codAcademica;
	}

	@Column(name = "COD_INTACADEMICA", nullable = false)
	public int getCodIntacademica() {
		return this.codIntacademica;
	}

	public void setCodIntacademica(int codIntacademica) {
		this.codIntacademica = codIntacademica;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonalAcademicaId))
			return false;
		PersonalAcademicaId castOther = (PersonalAcademicaId) other;

		return (this.getCodPersonal() == castOther.getCodPersonal())
				&& (this.getCodAcademica() == castOther.getCodAcademica())
				&& (this.getCodIntacademica() == castOther.getCodIntacademica());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodPersonal();
		result = 37 * result + this.getCodAcademica();
		result = 37 * result + this.getCodIntacademica();
		return result;
	}

}
