package pe.gob.ocma.entities.web_ocma;

// Generated 04/11/2014 03:54:12 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonalAcademica generated by hbm2java
 */
@Entity
@Table(name = "PERSONAL_ACADEMICA", schema = "WEB_OCMA")
public class PersonalAcademica implements java.io.Serializable {

	private PersonalAcademicaId id;
	private String desEspecialidad;
	private String desCentroEstudios;
	private String desLugar;
	private String numColegiatura;
	private Integer codCvTitulo;
	private Integer codCvEstudiosup;
	private Integer codCvActividad;
	private Integer codCvParticipacion;
	private Date fecInicio;
	private Date fecFin;
	private Integer codCvMerito;
	private String desMerito;
	private Date fecCreacion;
	private Date fecModificacion;
	private Integer codSector;
	private Integer codCvNivel;
	private Integer numSemestre;
	private Integer numHoras;
	private Integer codCvNivelIdioma;
	private String desAnoInicio;
	private String desAnoFin;

	public PersonalAcademica() {
	}

	public PersonalAcademica(PersonalAcademicaId id, Date fecCreacion) {
		this.id = id;
		this.fecCreacion = fecCreacion;
	}

	public PersonalAcademica(PersonalAcademicaId id, String desEspecialidad,
			String desCentroEstudios, String desLugar, String numColegiatura,
			Integer codCvTitulo, Integer codCvEstudiosup,
			Integer codCvActividad, Integer codCvParticipacion, Date fecInicio,
			Date fecFin, Integer codCvMerito, String desMerito,
			Date fecCreacion, Date fecModificacion, Integer codSector,
			Integer codCvNivel, Integer numSemestre, Integer numHoras,
			Integer codCvNivelIdioma, String desAnoInicio, String desAnoFin) {
		this.id = id;
		this.desEspecialidad = desEspecialidad;
		this.desCentroEstudios = desCentroEstudios;
		this.desLugar = desLugar;
		this.numColegiatura = numColegiatura;
		this.codCvTitulo = codCvTitulo;
		this.codCvEstudiosup = codCvEstudiosup;
		this.codCvActividad = codCvActividad;
		this.codCvParticipacion = codCvParticipacion;
		this.fecInicio = fecInicio;
		this.fecFin = fecFin;
		this.codCvMerito = codCvMerito;
		this.desMerito = desMerito;
		this.fecCreacion = fecCreacion;
		this.fecModificacion = fecModificacion;
		this.codSector = codSector;
		this.codCvNivel = codCvNivel;
		this.numSemestre = numSemestre;
		this.numHoras = numHoras;
		this.codCvNivelIdioma = codCvNivelIdioma;
		this.desAnoInicio = desAnoInicio;
		this.desAnoFin = desAnoFin;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codPersonal", column = @Column(name = "COD_PERSONAL", nullable = false)),
			@AttributeOverride(name = "codAcademica", column = @Column(name = "COD_ACADEMICA", nullable = false)),
			@AttributeOverride(name = "codIntacademica", column = @Column(name = "COD_INTACADEMICA", nullable = false)) })
	public PersonalAcademicaId getId() {
		return this.id;
	}

	public void setId(PersonalAcademicaId id) {
		this.id = id;
	}

	@Column(name = "DES_ESPECIALIDAD", length = 120)
	public String getDesEspecialidad() {
		return this.desEspecialidad;
	}

	public void setDesEspecialidad(String desEspecialidad) {
		this.desEspecialidad = desEspecialidad;
	}

	@Column(name = "DES_CENTRO_ESTUDIOS", length = 120)
	public String getDesCentroEstudios() {
		return this.desCentroEstudios;
	}

	public void setDesCentroEstudios(String desCentroEstudios) {
		this.desCentroEstudios = desCentroEstudios;
	}

	@Column(name = "DES_LUGAR", length = 70)
	public String getDesLugar() {
		return this.desLugar;
	}

	public void setDesLugar(String desLugar) {
		this.desLugar = desLugar;
	}

	@Column(name = "NUM_COLEGIATURA", length = 5)
	public String getNumColegiatura() {
		return this.numColegiatura;
	}

	public void setNumColegiatura(String numColegiatura) {
		this.numColegiatura = numColegiatura;
	}

	@Column(name = "COD_CV_TITULO")
	public Integer getCodCvTitulo() {
		return this.codCvTitulo;
	}

	public void setCodCvTitulo(Integer codCvTitulo) {
		this.codCvTitulo = codCvTitulo;
	}

	@Column(name = "COD_CV_ESTUDIOSUP")
	public Integer getCodCvEstudiosup() {
		return this.codCvEstudiosup;
	}

	public void setCodCvEstudiosup(Integer codCvEstudiosup) {
		this.codCvEstudiosup = codCvEstudiosup;
	}

	@Column(name = "COD_CV_ACTIVIDAD")
	public Integer getCodCvActividad() {
		return this.codCvActividad;
	}

	public void setCodCvActividad(Integer codCvActividad) {
		this.codCvActividad = codCvActividad;
	}

	@Column(name = "COD_CV_PARTICIPACION")
	public Integer getCodCvParticipacion() {
		return this.codCvParticipacion;
	}

	public void setCodCvParticipacion(Integer codCvParticipacion) {
		this.codCvParticipacion = codCvParticipacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_INICIO", length = 10)
	public Date getFecInicio() {
		return this.fecInicio;
	}

	public void setFecInicio(Date fecInicio) {
		this.fecInicio = fecInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_FIN", length = 10)
	public Date getFecFin() {
		return this.fecFin;
	}

	public void setFecFin(Date fecFin) {
		this.fecFin = fecFin;
	}

	@Column(name = "COD_CV_MERITO")
	public Integer getCodCvMerito() {
		return this.codCvMerito;
	}

	public void setCodCvMerito(Integer codCvMerito) {
		this.codCvMerito = codCvMerito;
	}

	@Column(name = "DES_MERITO", length = 450)
	public String getDesMerito() {
		return this.desMerito;
	}

	public void setDesMerito(String desMerito) {
		this.desMerito = desMerito;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_CREACION", nullable = false, length = 26)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICACION", length = 26)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "COD_SECTOR")
	public Integer getCodSector() {
		return this.codSector;
	}

	public void setCodSector(Integer codSector) {
		this.codSector = codSector;
	}

	@Column(name = "COD_CV_NIVEL")
	public Integer getCodCvNivel() {
		return this.codCvNivel;
	}

	public void setCodCvNivel(Integer codCvNivel) {
		this.codCvNivel = codCvNivel;
	}

	@Column(name = "NUM_SEMESTRE")
	public Integer getNumSemestre() {
		return this.numSemestre;
	}

	public void setNumSemestre(Integer numSemestre) {
		this.numSemestre = numSemestre;
	}

	@Column(name = "NUM_HORAS")
	public Integer getNumHoras() {
		return this.numHoras;
	}

	public void setNumHoras(Integer numHoras) {
		this.numHoras = numHoras;
	}

	@Column(name = "COD_CV_NIVEL_IDIOMA")
	public Integer getCodCvNivelIdioma() {
		return this.codCvNivelIdioma;
	}

	public void setCodCvNivelIdioma(Integer codCvNivelIdioma) {
		this.codCvNivelIdioma = codCvNivelIdioma;
	}

	@Column(name = "DES_ANO_INICIO", length = 4)
	public String getDesAnoInicio() {
		return this.desAnoInicio;
	}

	public void setDesAnoInicio(String desAnoInicio) {
		this.desAnoInicio = desAnoInicio;
	}

	@Column(name = "DES_ANO_FIN", length = 4)
	public String getDesAnoFin() {
		return this.desAnoFin;
	}

	public void setDesAnoFin(String desAnoFin) {
		this.desAnoFin = desAnoFin;
	}

}
