package pe.gob.ocma.entities.web_ocma;

// Generated 29/09/2014 11:43:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonalInfo generated by hbm2java
 */
@Entity
@Table(name = "PERSONAL_INFO", schema = "WEB_OCMA")
public class PersonalInfo implements java.io.Serializable {

	private int codPersonal;
	private TablaEstadoCivil tablaEstadoCivil;
	private Date fecNacimiento;
	private String codDepartamentonac;
	private String codProvincianac;
	private String codDistritonac;
	private String desNacionalidad;
	private String numLmilitar;
	private String numBrevete;
	private String numPasaporte;
	private String numCarnetext;
	private Integer codGsanguineo;
	private int flaSexo;
	private String desDireccion;
	private String codDepartamento;
	private String codProvincia;
	private String codDistrito;
	private String numTelefono;
	private String numMovil;
	private String desEmail;
	private String desEmailLaboral;

	public PersonalInfo() {
	}

	public PersonalInfo(int codPersonal, TablaEstadoCivil tablaEstadoCivil,
			int flaSexo) {
		this.codPersonal = codPersonal;
		this.tablaEstadoCivil = tablaEstadoCivil;
		this.flaSexo = flaSexo;
	}

	public PersonalInfo(int codPersonal, TablaEstadoCivil tablaEstadoCivil,
			Date fecNacimiento, String codDepartamentonac,
			String codProvincianac, String codDistritonac,
			String desNacionalidad, String numLmilitar, String numBrevete,
			String numPasaporte, String numCarnetext, Integer codGsanguineo,
			int flaSexo, String desDireccion, String codDepartamento,
			String codProvincia, String codDistrito, String numTelefono,
			String numMovil, String desEmail, String desEmailLaboral) {
		this.codPersonal = codPersonal;
		this.tablaEstadoCivil = tablaEstadoCivil;
		this.fecNacimiento = fecNacimiento;
		this.codDepartamentonac = codDepartamentonac;
		this.codProvincianac = codProvincianac;
		this.codDistritonac = codDistritonac;
		this.desNacionalidad = desNacionalidad;
		this.numLmilitar = numLmilitar;
		this.numBrevete = numBrevete;
		this.numPasaporte = numPasaporte;
		this.numCarnetext = numCarnetext;
		this.codGsanguineo = codGsanguineo;
		this.flaSexo = flaSexo;
		this.desDireccion = desDireccion;
		this.codDepartamento = codDepartamento;
		this.codProvincia = codProvincia;
		this.codDistrito = codDistrito;
		this.numTelefono = numTelefono;
		this.numMovil = numMovil;
		this.desEmail = desEmail;
		this.desEmailLaboral = desEmailLaboral;
	}

	@Id
	@Column(name = "COD_PERSONAL", nullable = false)
	public int getCodPersonal() {
		return this.codPersonal;
	}

	public void setCodPersonal(int codPersonal) {
		this.codPersonal = codPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ESTADOCIVIL", nullable = false)
	public TablaEstadoCivil getTablaEstadoCivil() {
		return this.tablaEstadoCivil;
	}

	public void setTablaEstadoCivil(TablaEstadoCivil tablaEstadoCivil) {
		this.tablaEstadoCivil = tablaEstadoCivil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_NACIMIENTO", length = 10)
	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	@Column(name = "COD_DEPARTAMENTONAC", length = 2)
	public String getCodDepartamentonac() {
		return this.codDepartamentonac;
	}

	public void setCodDepartamentonac(String codDepartamentonac) {
		this.codDepartamentonac = codDepartamentonac;
	}

	@Column(name = "COD_PROVINCIANAC", length = 2)
	public String getCodProvincianac() {
		return this.codProvincianac;
	}

	public void setCodProvincianac(String codProvincianac) {
		this.codProvincianac = codProvincianac;
	}

	@Column(name = "COD_DISTRITONAC", length = 2)
	public String getCodDistritonac() {
		return this.codDistritonac;
	}

	public void setCodDistritonac(String codDistritonac) {
		this.codDistritonac = codDistritonac;
	}

	@Column(name = "DES_NACIONALIDAD", length = 100)
	public String getDesNacionalidad() {
		return this.desNacionalidad;
	}

	public void setDesNacionalidad(String desNacionalidad) {
		this.desNacionalidad = desNacionalidad;
	}

	@Column(name = "NUM_LMILITAR", length = 10)
	public String getNumLmilitar() {
		return this.numLmilitar;
	}

	public void setNumLmilitar(String numLmilitar) {
		this.numLmilitar = numLmilitar;
	}

	@Column(name = "NUM_BREVETE", length = 30)
	public String getNumBrevete() {
		return this.numBrevete;
	}

	public void setNumBrevete(String numBrevete) {
		this.numBrevete = numBrevete;
	}

	@Column(name = "NUM_PASAPORTE", length = 30)
	public String getNumPasaporte() {
		return this.numPasaporte;
	}

	public void setNumPasaporte(String numPasaporte) {
		this.numPasaporte = numPasaporte;
	}

	@Column(name = "NUM_CARNETEXT", length = 30)
	public String getNumCarnetext() {
		return this.numCarnetext;
	}

	public void setNumCarnetext(String numCarnetext) {
		this.numCarnetext = numCarnetext;
	}

	@Column(name = "COD_GSANGUINEO")
	public Integer getCodGsanguineo() {
		return this.codGsanguineo;
	}

	public void setCodGsanguineo(Integer codGsanguineo) {
		this.codGsanguineo = codGsanguineo;
	}

	@Column(name = "FLA_SEXO", nullable = false)
	public int getFlaSexo() {
		return this.flaSexo;
	}

	public void setFlaSexo(int flaSexo) {
		this.flaSexo = flaSexo;
	}

	@Column(name = "DES_DIRECCION", length = 100)
	public String getDesDireccion() {
		return this.desDireccion;
	}

	public void setDesDireccion(String desDireccion) {
		this.desDireccion = desDireccion;
	}

	@Column(name = "COD_DEPARTAMENTO", length = 2)
	public String getCodDepartamento() {
		return this.codDepartamento;
	}

	public void setCodDepartamento(String codDepartamento) {
		this.codDepartamento = codDepartamento;
	}

	@Column(name = "COD_PROVINCIA", length = 2)
	public String getCodProvincia() {
		return this.codProvincia;
	}

	public void setCodProvincia(String codProvincia) {
		this.codProvincia = codProvincia;
	}

	@Column(name = "COD_DISTRITO", length = 2)
	public String getCodDistrito() {
		return this.codDistrito;
	}

	public void setCodDistrito(String codDistrito) {
		this.codDistrito = codDistrito;
	}

	@Column(name = "NUM_TELEFONO", length = 15)
	public String getNumTelefono() {
		return this.numTelefono;
	}

	public void setNumTelefono(String numTelefono) {
		this.numTelefono = numTelefono;
	}

	@Column(name = "NUM_MOVIL", length = 15)
	public String getNumMovil() {
		return this.numMovil;
	}

	public void setNumMovil(String numMovil) {
		this.numMovil = numMovil;
	}

	@Column(name = "DES_EMAIL", length = 250)
	public String getDesEmail() {
		return this.desEmail;
	}

	public void setDesEmail(String desEmail) {
		this.desEmail = desEmail;
	}

	@Column(name = "DES_EMAIL_LABORAL", length = 250)
	public String getDesEmailLaboral() {
		return this.desEmailLaboral;
	}

	public void setDesEmailLaboral(String desEmailLaboral) {
		this.desEmailLaboral = desEmailLaboral;
	}

}
