package pe.gob.ocma.entities.web_ocma;

// Generated 04/11/2014 04:33:59 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TablaCvNivel generated by hbm2java
 */
@Entity
@Table(name = "TABLA_CV_NIVEL", schema = "WEB_OCMA")
public class TablaCvNivel implements java.io.Serializable {

	private int codCvNivel;
	private String desCvNivel;
	private char flaEstado;

	public TablaCvNivel() {
	}

	public TablaCvNivel(int codCvNivel, String desCvNivel, char flaEstado) {
		this.codCvNivel = codCvNivel;
		this.desCvNivel = desCvNivel;
		this.flaEstado = flaEstado;
	}

	@Id
	@Column(name = "COD_CV_NIVEL", nullable = false)
	public int getCodCvNivel() {
		return this.codCvNivel;
	}

	public void setCodCvNivel(int codCvNivel) {
		this.codCvNivel = codCvNivel;
	}

	@Column(name = "DES_CV_NIVEL", nullable = false, length = 35)
	public String getDesCvNivel() {
		return this.desCvNivel;
	}

	public void setDesCvNivel(String desCvNivel) {
		this.desCvNivel = desCvNivel;
	}

	@Column(name = "FLA_ESTADO", nullable = false, length = 1)
	public char getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(char flaEstado) {
		this.flaEstado = flaEstado;
	}

}
