package pe.gob.ocma.entities.web_ocma;

// Generated 19/09/2014 11:18:41 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", schema = "WEB_OCMA")
public class Usuario implements java.io.Serializable {

	private String codUsuario;
	private Integer codPersonal;
	private String desContrasena;
	private Integer codDistritojudicial;
	private Character flaCambioContraseniaInicio;
	private Character flaEstado;
	private Date fecCreacion;
	private Date fecModificacion;
	private String codUsomodificacion;
	private String desContrasenaLimpia;
	private String desUsuario;
	private String numCasilla;
	private Set<IngresoAuditoria> ingresoAuditorias = new HashSet<IngresoAuditoria>(
			0);
	private Set<Usuarioxgrupo> usuarioxgrupos = new HashSet<Usuarioxgrupo>(0);

	public Usuario() {
	}

	public Usuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	public Usuario(String codUsuario, Integer codPersonal,
			String desContrasena, Integer codDistritojudicial,
			Character flaCambioContraseniaInicio, Character flaEstado,
			Date fecCreacion, Date fecModificacion, String codUsomodificacion,
			String desContrasenaLimpia, String desUsuario, String numCasilla,
			Set<IngresoAuditoria> ingresoAuditorias,
			Set<Usuarioxgrupo> usuarioxgrupos) {
		this.codUsuario = codUsuario;
		this.codPersonal = codPersonal;
		this.desContrasena = desContrasena;
		this.codDistritojudicial = codDistritojudicial;
		this.flaCambioContraseniaInicio = flaCambioContraseniaInicio;
		this.flaEstado = flaEstado;
		this.fecCreacion = fecCreacion;
		this.fecModificacion = fecModificacion;
		this.codUsomodificacion = codUsomodificacion;
		this.desContrasenaLimpia = desContrasenaLimpia;
		this.desUsuario = desUsuario;
		this.numCasilla = numCasilla;
		this.ingresoAuditorias = ingresoAuditorias;
		this.usuarioxgrupos = usuarioxgrupos;
	}

	@Id
	@Column(name = "COD_USUARIO", nullable = false, length = 20)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "COD_PERSONAL")
	public Integer getCodPersonal() {
		return this.codPersonal;
	}

	public void setCodPersonal(Integer codPersonal) {
		this.codPersonal = codPersonal;
	}

	@Column(name = "DES_CONTRASENA", length = 50)
	public String getDesContrasena() {
		return this.desContrasena;
	}

	public void setDesContrasena(String desContrasena) {
		this.desContrasena = desContrasena;
	}

	@Column(name = "COD_DISTRITOJUDICIAL")
	public Integer getCodDistritojudicial() {
		return this.codDistritojudicial;
	}

	public void setCodDistritojudicial(Integer codDistritojudicial) {
		this.codDistritojudicial = codDistritojudicial;
	}

	@Column(name = "FLA_CAMBIO_CONTRASENIA_INICIO", length = 1)
	public Character getFlaCambioContraseniaInicio() {
		return this.flaCambioContraseniaInicio;
	}

	public void setFlaCambioContraseniaInicio(
			Character flaCambioContraseniaInicio) {
		this.flaCambioContraseniaInicio = flaCambioContraseniaInicio;
	}

	@Column(name = "FLA_ESTADO", length = 1)
	public Character getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(Character flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_CREACION", length = 26)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICACION", length = 26)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "COD_USOMODIFICACION", length = 20)
	public String getCodUsomodificacion() {
		return this.codUsomodificacion;
	}

	public void setCodUsomodificacion(String codUsomodificacion) {
		this.codUsomodificacion = codUsomodificacion;
	}

	@Column(name = "DES_CONTRASENA_LIMPIA", length = 20)
	public String getDesContrasenaLimpia() {
		return this.desContrasenaLimpia;
	}

	public void setDesContrasenaLimpia(String desContrasenaLimpia) {
		this.desContrasenaLimpia = desContrasenaLimpia;
	}

	@Column(name = "DES_USUARIO", length = 200)
	public String getDesUsuario() {
		return this.desUsuario;
	}

	public void setDesUsuario(String desUsuario) {
		this.desUsuario = desUsuario;
	}

	@Column(name = "NUM_CASILLA", length = 8)
	public String getNumCasilla() {
		return this.numCasilla;
	}

	public void setNumCasilla(String numCasilla) {
		this.numCasilla = numCasilla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<IngresoAuditoria> getIngresoAuditorias() {
		return this.ingresoAuditorias;
	}

	public void setIngresoAuditorias(Set<IngresoAuditoria> ingresoAuditorias) {
		this.ingresoAuditorias = ingresoAuditorias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Usuarioxgrupo> getUsuarioxgrupos() {
		return this.usuarioxgrupos;
	}

	public void setUsuarioxgrupos(Set<Usuarioxgrupo> usuarioxgrupos) {
		this.usuarioxgrupos = usuarioxgrupos;
	}

}
