package pe.gob.ocma.entities.web_ocma;

// Generated 19/09/2014 11:18:41 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioxgrupoId generated by hbm2java
 */
@Embeddable
public class UsuarioxgrupoId implements java.io.Serializable {

	private String codGrupo;
	private String codUsuario;

	public UsuarioxgrupoId() {
	}

	public UsuarioxgrupoId(String codGrupo, String codUsuario) {
		this.codGrupo = codGrupo;
		this.codUsuario = codUsuario;
	}

	@Column(name = "COD_GRUPO", nullable = false, length = 10)
	public String getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(String codGrupo) {
		this.codGrupo = codGrupo;
	}

	@Column(name = "COD_USUARIO", nullable = false, length = 20)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioxgrupoId))
			return false;
		UsuarioxgrupoId castOther = (UsuarioxgrupoId) other;

		return ((this.getCodGrupo() == castOther.getCodGrupo()) || (this
				.getCodGrupo() != null && castOther.getCodGrupo() != null && this
				.getCodGrupo().equals(castOther.getCodGrupo())))
				&& ((this.getCodUsuario() == castOther.getCodUsuario()) || (this
						.getCodUsuario() != null
						&& castOther.getCodUsuario() != null && this
						.getCodUsuario().equals(castOther.getCodUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodGrupo() == null ? 0 : this.getCodGrupo().hashCode());
		result = 37
				* result
				+ (getCodUsuario() == null ? 0 : this.getCodUsuario()
						.hashCode());
		return result;
	}

}
