package pe.gob.ocma.entities.web_ocma;

// Generated 19/09/2014 11:18:41 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuarioxgrupo generated by hbm2java
 */
@Entity
@Table(name = "USUARIOXGRUPO", schema = "WEB_OCMA")
public class Usuarioxgrupo implements java.io.Serializable {

	private UsuarioxgrupoId id;
	private Usuario usuario;

	public Usuarioxgrupo() {
	}

	public Usuarioxgrupo(UsuarioxgrupoId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codGrupo", column = @Column(name = "COD_GRUPO", nullable = false, length = 10)),
			@AttributeOverride(name = "codUsuario", column = @Column(name = "COD_USUARIO", nullable = false, length = 20)) })
	public UsuarioxgrupoId getId() {
		return this.id;
	}

	public void setId(UsuarioxgrupoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_USUARIO", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
