package pe.gob.ocma.entities.web_ocma;

// Generated 19/09/2014 11:18:41 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebPersonal generated by hbm2java
 */
@Entity
@Table(name = "WEB_PERSONAL", schema = "WEB_OCMA")
public class WebPersonal implements java.io.Serializable {

	private int codPersonal;
	private String desApPaterno;
	private String desApMaterno;
	private String desNombre;
	private int codDocidentidad;
	private String desNumiden;
	private String numEscalafon;
	private String numFotocheck;
	private Date fecIngreso;
	private String numBnacion;
	private String numRuc;
	private String codContab;
	private String numEssalud;
	private int codRegpension;
	private Integer codAfp;
	private String desUbicacion;
	private String desObservacion;
	private String desHistoria;
	private String desNmultired;
	private char flaEstado;
	private Date fecCreacion;
	private Date fecModificacion;
	private String numAfp;
	private String desFoto;
	private Date fecAsignacion;
	private String numCasilla;

	public WebPersonal() {
	}

	public WebPersonal(int codPersonal, String desApPaterno,
			String desApMaterno, String desNombre, int codDocidentidad,
			int codRegpension, char flaEstado, Date fecCreacion) {
		this.codPersonal = codPersonal;
		this.desApPaterno = desApPaterno;
		this.desApMaterno = desApMaterno;
		this.desNombre = desNombre;
		this.codDocidentidad = codDocidentidad;
		this.codRegpension = codRegpension;
		this.flaEstado = flaEstado;
		this.fecCreacion = fecCreacion;
	}

	public WebPersonal(int codPersonal, String desApPaterno,
			String desApMaterno, String desNombre, int codDocidentidad,
			String desNumiden, String numEscalafon, String numFotocheck,
			Date fecIngreso, String numBnacion, String numRuc,
			String codContab, String numEssalud, int codRegpension,
			Integer codAfp, String desUbicacion, String desObservacion,
			String desHistoria, String desNmultired, char flaEstado,
			Date fecCreacion, Date fecModificacion, String numAfp,
			String desFoto, Date fecAsignacion, String numCasilla) {
		this.codPersonal = codPersonal;
		this.desApPaterno = desApPaterno;
		this.desApMaterno = desApMaterno;
		this.desNombre = desNombre;
		this.codDocidentidad = codDocidentidad;
		this.desNumiden = desNumiden;
		this.numEscalafon = numEscalafon;
		this.numFotocheck = numFotocheck;
		this.fecIngreso = fecIngreso;
		this.numBnacion = numBnacion;
		this.numRuc = numRuc;
		this.codContab = codContab;
		this.numEssalud = numEssalud;
		this.codRegpension = codRegpension;
		this.codAfp = codAfp;
		this.desUbicacion = desUbicacion;
		this.desObservacion = desObservacion;
		this.desHistoria = desHistoria;
		this.desNmultired = desNmultired;
		this.flaEstado = flaEstado;
		this.fecCreacion = fecCreacion;
		this.fecModificacion = fecModificacion;
		this.numAfp = numAfp;
		this.desFoto = desFoto;
		this.fecAsignacion = fecAsignacion;
		this.numCasilla = numCasilla;
	}

	@Id
	@Column(name = "COD_PERSONAL", nullable = false)
	public int getCodPersonal() {
		return this.codPersonal;
	}

	public void setCodPersonal(int codPersonal) {
		this.codPersonal = codPersonal;
	}

	@Column(name = "DES_AP_PATERNO", nullable = false, length = 50)
	public String getDesApPaterno() {
		return this.desApPaterno;
	}

	public void setDesApPaterno(String desApPaterno) {
		this.desApPaterno = desApPaterno;
	}

	@Column(name = "DES_AP_MATERNO", nullable = false, length = 50)
	public String getDesApMaterno() {
		return this.desApMaterno;
	}

	public void setDesApMaterno(String desApMaterno) {
		this.desApMaterno = desApMaterno;
	}

	@Column(name = "DES_NOMBRE", nullable = false, length = 60)
	public String getDesNombre() {
		return this.desNombre;
	}

	public void setDesNombre(String desNombre) {
		this.desNombre = desNombre;
	}

	@Column(name = "COD_DOCIDENTIDAD", nullable = false)
	public int getCodDocidentidad() {
		return this.codDocidentidad;
	}

	public void setCodDocidentidad(int codDocidentidad) {
		this.codDocidentidad = codDocidentidad;
	}

	@Column(name = "DES_NUMIDEN", length = 20)
	public String getDesNumiden() {
		return this.desNumiden;
	}

	public void setDesNumiden(String desNumiden) {
		this.desNumiden = desNumiden;
	}

	@Column(name = "NUM_ESCALAFON", length = 6)
	public String getNumEscalafon() {
		return this.numEscalafon;
	}

	public void setNumEscalafon(String numEscalafon) {
		this.numEscalafon = numEscalafon;
	}

	@Column(name = "NUM_FOTOCHECK", length = 5)
	public String getNumFotocheck() {
		return this.numFotocheck;
	}

	public void setNumFotocheck(String numFotocheck) {
		this.numFotocheck = numFotocheck;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_INGRESO", length = 10)
	public Date getFecIngreso() {
		return this.fecIngreso;
	}

	public void setFecIngreso(Date fecIngreso) {
		this.fecIngreso = fecIngreso;
	}

	@Column(name = "NUM_BNACION", length = 12)
	public String getNumBnacion() {
		return this.numBnacion;
	}

	public void setNumBnacion(String numBnacion) {
		this.numBnacion = numBnacion;
	}

	@Column(name = "NUM_RUC", length = 11)
	public String getNumRuc() {
		return this.numRuc;
	}

	public void setNumRuc(String numRuc) {
		this.numRuc = numRuc;
	}

	@Column(name = "COD_CONTAB", length = 10)
	public String getCodContab() {
		return this.codContab;
	}

	public void setCodContab(String codContab) {
		this.codContab = codContab;
	}

	@Column(name = "NUM_ESSALUD", length = 15)
	public String getNumEssalud() {
		return this.numEssalud;
	}

	public void setNumEssalud(String numEssalud) {
		this.numEssalud = numEssalud;
	}

	@Column(name = "COD_REGPENSION", nullable = false)
	public int getCodRegpension() {
		return this.codRegpension;
	}

	public void setCodRegpension(int codRegpension) {
		this.codRegpension = codRegpension;
	}

	@Column(name = "COD_AFP")
	public Integer getCodAfp() {
		return this.codAfp;
	}

	public void setCodAfp(Integer codAfp) {
		this.codAfp = codAfp;
	}

	@Column(name = "DES_UBICACION")
	public String getDesUbicacion() {
		return this.desUbicacion;
	}

	public void setDesUbicacion(String desUbicacion) {
		this.desUbicacion = desUbicacion;
	}

	@Column(name = "DES_OBSERVACION")
	public String getDesObservacion() {
		return this.desObservacion;
	}

	public void setDesObservacion(String desObservacion) {
		this.desObservacion = desObservacion;
	}

	@Column(name = "DES_HISTORIA")
	public String getDesHistoria() {
		return this.desHistoria;
	}

	public void setDesHistoria(String desHistoria) {
		this.desHistoria = desHistoria;
	}

	@Column(name = "DES_NMULTIRED", length = 15)
	public String getDesNmultired() {
		return this.desNmultired;
	}

	public void setDesNmultired(String desNmultired) {
		this.desNmultired = desNmultired;
	}

	@Column(name = "FLA_ESTADO", nullable = false, length = 1)
	public char getFlaEstado() {
		return this.flaEstado;
	}

	public void setFlaEstado(char flaEstado) {
		this.flaEstado = flaEstado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_CREACION", nullable = false, length = 26)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICACION", length = 26)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "NUM_AFP", length = 20)
	public String getNumAfp() {
		return this.numAfp;
	}

	public void setNumAfp(String numAfp) {
		this.numAfp = numAfp;
	}

	@Column(name = "DES_FOTO", length = 100)
	public String getDesFoto() {
		return this.desFoto;
	}

	public void setDesFoto(String desFoto) {
		this.desFoto = desFoto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_ASIGNACION", length = 10)
	public Date getFecAsignacion() {
		return this.fecAsignacion;
	}

	public void setFecAsignacion(Date fecAsignacion) {
		this.fecAsignacion = fecAsignacion;
	}

	@Column(name = "NUM_CASILLA", length = 8)
	public String getNumCasilla() {
		return this.numCasilla;
	}

	public void setNumCasilla(String numCasilla) {
		this.numCasilla = numCasilla;
	}

}
