package pe.gob.ocma.entities.organosjurisd;

// Generated 21/11/2013 03:52:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import pe.gob.ocma.entities.ubigeo.Ubtprovincia;
import pe.gob.ocma.entities.ubigeojud.Ujtdisjud;

/**
 * Ojtdependen generated by hbm2java
 */
@Entity
@Table(name = "OJTDEPENDEN", schema = "ORGANOSJURISD")
public class Ojtdependen implements java.io.Serializable {

	private int codDependen;
	private Ojtespeciali ojtespeciali;
	private Ojtorgjurisd ojtorgjurisd;
	private Ojtnumdepen ojtnumdepen;
	private Ojtsubespe ojtsubespe;
	private String descripcion;
	private String nota;
	private Short codDisJud;
	private Ujtdisjud ujtdisjud;
	private Short codProJud;
	private Integer codCedJud;
	private String codDepartam;	
	private Ubtprovincia ubtprovincia;
	private String codUbiProv;
	private String codUbiDis;
	private String codUbiCenPob;
	private boolean habilitado;

	public Ojtdependen() {
	}
	
	@Id
	@Column(name = "codDependen", nullable = false)
	public int getCodDependen() {
		return this.codDependen;
	}

	public void setCodDependen(int codDependen) {
		this.codDependen = codDependen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codEspeciali", nullable = false)
	public Ojtespeciali getOjtespeciali() {
		return this.ojtespeciali;
	}

	public void setOjtespeciali(Ojtespeciali ojtespeciali) {
		this.ojtespeciali = ojtespeciali;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codOrgJurisd", nullable = false)
	public Ojtorgjurisd getOjtorgjurisd() {
		return this.ojtorgjurisd;
	}

	public void setOjtorgjurisd(Ojtorgjurisd ojtorgjurisd) {
		this.ojtorgjurisd = ojtorgjurisd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codNumDepen", nullable = false)
	public Ojtnumdepen getOjtnumdepen() {
		return this.ojtnumdepen;
	}

	public void setOjtnumdepen(Ojtnumdepen ojtnumdepen) {
		this.ojtnumdepen = ojtnumdepen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codSubEspe", nullable = false)
	public Ojtsubespe getOjtsubespe() {
		return this.ojtsubespe;
	}

	public void setOjtsubespe(Ojtsubespe ojtsubespe) {
		this.ojtsubespe = ojtsubespe;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "nota", length = 150)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "codDisJud", nullable = false)
	public Short getCodDisJud() {
		return this.codDisJud;
	}

	public void setCodDisJud(Short codDisJud) {
		this.codDisJud = codDisJud;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codDisJud", nullable = false , insertable = false, updatable = false)
	public Ujtdisjud getUjtdisjud() {
		return ujtdisjud;
	}
	
	public void setUjtdisjud(Ujtdisjud ujtdisjud) {
		this.ujtdisjud = ujtdisjud;
	}

	@Column(name = "codProJud")
	public Short getCodProJud() {
		return this.codProJud;
	}	

	public void setCodProJud(Short codProJud) {
		this.codProJud = codProJud;
	}

	@Column(name = "codCedJud")
	public Integer getCodCedJud() {
		return this.codCedJud;
	}

	public void setCodCedJud(Integer codCedJud) {
		this.codCedJud = codCedJud;
	}

	@Column(name = "codDepartam", nullable = false, length = 2)
	public String getCodDepartam() {
		return this.codDepartam;
	}

	public void setCodDepartam(String codDepartam) {
		this.codDepartam = codDepartam;
	}

	@Column(name = "codUbiProv", nullable = false, length = 4)
	public String getCodUbiProv() {
		return this.codUbiProv;
	}
	
	public void setCodUbiProv(String codUbiProv) {
		this.codUbiProv = codUbiProv;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codUbiProv", nullable = false, insertable = false, updatable = false)
	public Ubtprovincia getUbtprovincia() {
		return ubtprovincia;
	}

	public void setUbtprovincia(Ubtprovincia ubtprovincia) {
		this.ubtprovincia = ubtprovincia;
	}

	@Column(name = "codUbiDis", length = 6)
	public String getCodUbiDis() {
		return this.codUbiDis;
	}

	public void setCodUbiDis(String codUbiDis) {
		this.codUbiDis = codUbiDis;
	}

	@Column(name = "codUbiCenPob", length = 10)
	public String getCodUbiCenPob() {
		return this.codUbiCenPob;
	}

	public void setCodUbiCenPob(String codUbiCenPob) {
		this.codUbiCenPob = codUbiCenPob;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
