package pe.gob.ocma.entities.organosjurisd;

// Generated 21/11/2013 03:52:20 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ojtespeciali generated by hbm2java
 */
@Entity
@Table(name = "OJTESPECIALI", schema = "ORGANOSJURISD", uniqueConstraints = {
		@UniqueConstraint(columnNames = "desAbrev"),
		@UniqueConstraint(columnNames = "orden"),
		@UniqueConstraint(columnNames = "descripcion"),
		@UniqueConstraint(columnNames = "desCorta") })
public class Ojtespeciali implements java.io.Serializable {

	private short codEspeciali;
	private String desAbrev;
	private String desCorta;
	private String descripcion;
	private short orden;
	private boolean porDefecto;
	private Set<Ojtdependen> ojtdependens = new HashSet<Ojtdependen>(0);

	public Ojtespeciali() {
	}

	public Ojtespeciali(short codEspeciali, String desAbrev, String desCorta,
			String descripcion, short orden, boolean porDefecto) {
		this.codEspeciali = codEspeciali;
		this.desAbrev = desAbrev;
		this.desCorta = desCorta;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
	}

	public Ojtespeciali(short codEspeciali, String desAbrev, String desCorta,
			String descripcion, short orden, boolean porDefecto,
			Set<Ojtdependen> ojtdependens) {
		this.codEspeciali = codEspeciali;
		this.desAbrev = desAbrev;
		this.desCorta = desCorta;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.ojtdependens = ojtdependens;
	}

	@Id
	@Column(name = "codEspeciali", nullable = false)
	public short getCodEspeciali() {
		return this.codEspeciali;
	}

	public void setCodEspeciali(short codEspeciali) {
		this.codEspeciali = codEspeciali;
	}

	@Column(name = "desAbrev", unique = true, nullable = false, length = 6)
	public String getDesAbrev() {
		return this.desAbrev;
	}

	public void setDesAbrev(String desAbrev) {
		this.desAbrev = desAbrev;
	}

	@Column(name = "desCorta", unique = true, nullable = false, length = 30)
	public String getDesCorta() {
		return this.desCorta;
	}

	public void setDesCorta(String desCorta) {
		this.desCorta = desCorta;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", unique = true, nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "porDefecto", nullable = false)
	public boolean isPorDefecto() {
		return this.porDefecto;
	}

	public void setPorDefecto(boolean porDefecto) {
		this.porDefecto = porDefecto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ojtespeciali")
	public Set<Ojtdependen> getOjtdependens() {
		return this.ojtdependens;
	}

	public void setOjtdependens(Set<Ojtdependen> ojtdependens) {
		this.ojtdependens = ojtdependens;
	}

}
