package pe.gob.ocma.entities.organosjurisd;

// Generated 21/11/2013 03:52:20 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ojtnumdepen generated by hbm2java
 */
@Entity
@Table(name = "OJTNUMDEPEN", schema = "ORGANOSJURISD", uniqueConstraints = @UniqueConstraint(columnNames = "orden"))
public class Ojtnumdepen implements java.io.Serializable {

	private short codNumDepen;
	private String numOrdinal;
	private short orden;
	private boolean porDefecto;
	private boolean habilitado;
	private Set<Ojtdependen> ojtdependens = new HashSet<Ojtdependen>(0);

	public Ojtnumdepen() {
	}
	
	@Id
	@Column(name = "codNumDepen", nullable = false)
	public short getCodNumDepen() {
		return this.codNumDepen;
	}

	public void setCodNumDepen(short codNumDepen) {
		this.codNumDepen = codNumDepen;
	}

	@Column(name = "numOrdinal", nullable = false, length = 4)
	public String getNumOrdinal() {
		return this.numOrdinal;
	}

	public void setNumOrdinal(String numOrdinal) {
		this.numOrdinal = numOrdinal;
	}

	@Column(name = "orden", unique = true, nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "porDefecto", nullable = false)
	public boolean isPorDefecto() {
		return this.porDefecto;
	}

	public void setPorDefecto(boolean porDefecto) {
		this.porDefecto = porDefecto;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ojtnumdepen")
	public Set<Ojtdependen> getOjtdependens() {
		return this.ojtdependens;
	}

	public void setOjtdependens(Set<Ojtdependen> ojtdependens) {
		this.ojtdependens = ojtdependens;
	}

}
