package pe.gob.ocma.entities.organosjurisd;

// Generated 21/11/2013 03:52:20 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ojtorgjurisd generated by hbm2java
 */
@Entity
@Table(name = "OJTORGJURISD", schema = "ORGANOSJURISD", uniqueConstraints = {
		@UniqueConstraint(columnNames = "descripcion"),
		@UniqueConstraint(columnNames = "orden"),
		@UniqueConstraint(columnNames = "nombre") })
public class Ojtorgjurisd implements java.io.Serializable {

	private short codOrgJurisd;
	private String nombre;
	private String descripcion;
	private short orden;
	private boolean porDefecto;
	private Set<Ojtdependen> ojtdependens = new HashSet<Ojtdependen>(0);

	public Ojtorgjurisd() {
	}

	public Ojtorgjurisd(short codOrgJurisd, String nombre, String descripcion,
			short orden, boolean porDefecto) {
		this.codOrgJurisd = codOrgJurisd;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
	}

	public Ojtorgjurisd(short codOrgJurisd, String nombre, String descripcion,
			short orden, boolean porDefecto, Set<Ojtdependen> ojtdependens) {
		this.codOrgJurisd = codOrgJurisd;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.ojtdependens = ojtdependens;
	}

	@Id
	@Column(name = "codOrgJurisd", nullable = false)
	public short getCodOrgJurisd() {
		return this.codOrgJurisd;
	}

	public void setCodOrgJurisd(short codOrgJurisd) {
		this.codOrgJurisd = codOrgJurisd;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", unique = true, nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "porDefecto", nullable = false)
	public boolean isPorDefecto() {
		return this.porDefecto;
	}

	public void setPorDefecto(boolean porDefecto) {
		this.porDefecto = porDefecto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ojtorgjurisd")
	public Set<Ojtdependen> getOjtdependens() {
		return this.ojtdependens;
	}

	public void setOjtdependens(Set<Ojtdependen> ojtdependens) {
		this.ojtdependens = ojtdependens;
	}

}
