package pe.gob.ocma.entities.organosjurisd;

// Generated 21/11/2013 03:52:20 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ojtsubespe generated by hbm2java
 */
@Entity
@Table(name = "OJTSUBESPE", schema = "ORGANOSJURISD", uniqueConstraints = {
		@UniqueConstraint(columnNames = "orden"),
		@UniqueConstraint(columnNames = "descripcion") })
public class Ojtsubespe implements java.io.Serializable {

	private short codSubEspe;
	private String descripcion;
	private short orden;
	private boolean porDefecto;
	private boolean habilitado;
	private Set<Ojtdependen> ojtdependens = new HashSet<Ojtdependen>(0);

	public Ojtsubespe() {
	}

	public Ojtsubespe(short codSubEspe, String descripcion, short orden,
			boolean porDefecto, boolean habilitado) {
		this.codSubEspe = codSubEspe;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.habilitado = habilitado;
	}

	public Ojtsubespe(short codSubEspe, String descripcion, short orden,
			boolean porDefecto, boolean habilitado,
			Set<Ojtdependen> ojtdependens) {
		this.codSubEspe = codSubEspe;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
		this.habilitado = habilitado;
		this.ojtdependens = ojtdependens;
	}

	@Id
	@Column(name = "codSubEspe", nullable = false)
	public short getCodSubEspe() {
		return this.codSubEspe;
	}

	public void setCodSubEspe(short codSubEspe) {
		this.codSubEspe = codSubEspe;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", unique = true, nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "porDefecto", nullable = false)
	public boolean isPorDefecto() {
		return this.porDefecto;
	}

	public void setPorDefecto(boolean porDefecto) {
		this.porDefecto = porDefecto;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ojtsubespe")
	public Set<Ojtdependen> getOjtdependens() {
		return this.ojtdependens;
	}

	public void setOjtdependens(Set<Ojtdependen> ojtdependens) {
		this.ojtdependens = ojtdependens;
	}

}
