package pe.gob.ocma.entities.organosjurisd;

// Generated 21/11/2013 03:52:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ojttipdepen generated by hbm2java
 */
@Entity
@Table(name = "OJTTIPDEPEN", schema = "ORGANOSJURISD", uniqueConstraints = {
		@UniqueConstraint(columnNames = "descripcion"),
		@UniqueConstraint(columnNames = "nombre"),
		@UniqueConstraint(columnNames = "orden") })
public class Ojttipdepen implements java.io.Serializable {

	private char codTipDepen;
	private String nombre;
	private String descripcion;
	private short orden;
	private boolean porDefecto;

	public Ojttipdepen() {
	}

	public Ojttipdepen(char codTipDepen, String nombre, String descripcion,
			short orden, boolean porDefecto) {
		this.codTipDepen = codTipDepen;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.orden = orden;
		this.porDefecto = porDefecto;
	}

	@Id
	@Column(name = "codTipDepen", nullable = false, length = 1)
	public char getCodTipDepen() {
		return this.codTipDepen;
	}

	public void setCodTipDepen(char codTipDepen) {
		this.codTipDepen = codTipDepen;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", unique = true, nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "porDefecto", nullable = false)
	public boolean isPorDefecto() {
		return this.porDefecto;
	}

	public void setPorDefecto(boolean porDefecto) {
		this.porDefecto = porDefecto;
	}

}
